### ISSUE TITLE
Position of character encoding filter is wrong

### ISSUE THREAD

**Issue by gskjold** [Jasig/cas#1008]
Symptoms:
Posting username and/or password with non-ASCII character becomes garbage on backend. 
example: øæå

Fix:
Move characterEncodingFilter in web.xml before all other filters.

Why this works, I don't know. But after moving the filter, all data was received as expected.

**Comment by mmoayyed** [comment]
What CAS version are you using?

**Comment by mmoayyed** [comment]
Confirmed bug
