### ISSUE TITLE
jasig cas-4.0.x cas-server-webapp-support still broken requires workaround (on Ubuntu 14.04, with tomcat 7.0.52.0)

### ISSUE THREAD

**Issue by mbohun** [Jasig/cas#1018]
once i added `cas-server-webapp-support` as a dependency into the [pom.xml](https://github.com/mbohun/jasig-cas-4.0.1-overlay-template/blob/master/pom.xml#L62) cas threw an exception on deploy and wasn't working anymore; after some googling i found a description of this bug (fortunately with a workaround by including old version of spring packages); although the old bug reports claims the bug was fixed that seems to be not the case (certainly not with `tomcat 7.0.52.0`):  
- https://issues.jasig.org/browse/CAS-1380 (contains the workaround **only for cas-4.0.1**)
- https://github.com/Jasig/cas/pull/382

Note: jasig `cas-4.1.0-SNAPSHOT` has the same problem, but the workaround is not working for `cas-4.1.0-SNAPSHOT`.

Judging from the available info and the fact many jasig's demos use jetty; this bug might be tomcat specific, and or tomcat version + ubuntu version specific.

exception/error message:
```
2015-07-02 05:09:39,341 ERROR [org.jasig.cas.web.init.SafeDispatcherServlet] - <SafeDispatcherServlet:
The Spring DispatcherServlet we wrap threw on init.
But for our having caught this error, the servlet would not have initialized.>
java.lang.NoSuchMethodError: org.springframework.web.context.support.WebApplicationContextUtils.initServletPropertySources(Lorg/springframework/core/env/MutablePropertySources;Ljavax/servlet/ServletContext;Ljavax/servlet/ServletConfig;)V
        at org.springframework.web.context.support.StandardServletEnvironment.initPropertySources(StandardServletEnvironment.java:94)
        at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:644)
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:599)
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:665)
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:518)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:459)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.jasig.cas.web.init.SafeDispatcherServlet.init(SafeDispatcherServlet.java:76)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1279)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1192)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5210)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5493)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

tomcat version:
```
ubuntu@nci-cas4:~$ /usr/share/tomcat7/bin/version.sh 
Using CATALINA_BASE:   /usr/share/tomcat7
Using CATALINA_HOME:   /usr/share/tomcat7
Using CATALINA_TMPDIR: /usr/share/tomcat7/temp
Using JRE_HOME:        /usr/lib/jvm/java-7-oracle
Using CLASSPATH:       /usr/share/tomcat7/bin/bootstrap.jar:/usr/share/tomcat7/bin/tomcat-juli.jar
Server version: Apache Tomcat/7.0.52 (Ubuntu)
Server built:   Jul 24 2014 08:38:51
Server number:  7.0.52.0
OS Name:        Linux
OS Version:     3.13.0-52-generic
Architecture:   amd64
JVM Version:    1.7.0_80-b15
JVM Vendor:     Oracle Corporation
```

java version:
```
ubuntu@nci-cas4:~$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

os type/version:
```
ubuntu@nci-cas4:~$ cat /etc/*rel*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by mmoayyed** [comment]
Why do you add cas-server-webapp-support into the pom?

**Comment by mmoayyed** [comment]
I'll look into this, but generally you shouldn't need to. the dependency is there, built into the webapp

**Comment by mmoayyed** [comment]
Another update, that I constantly run CAS 4.1 SNAPSHOT with both JDK 7 and 8 as well as TC 7 and 8. As I mentioned, the support library is built into the webapp. You dont need to explicitly include it. But there may be a bug somewhere that if you do include it and change the scope to compile, issues may come up.

**Comment by mmoayyed** [comment]
Actually, the support webapp is defined at compile level:
https://github.com/Jasig/cas/blob/master/cas-server-webapp/pom.xml#L31

So the issue is probably with your overlay and some other dependency that is pulling in extra jars.

**Comment by mbohun** [comment]
probably?

The original bug report https://issues.jasig.org/browse/CAS-1380 author even provided you with a **minimal** pom.xml file to replicate/demonstrate the problem - there are no other dependencies to trigger the problem.

My project (pom.xml) file is available too: https://github.com/mbohun/jasig-cas-4.0.1-overlay-template (as in i do not have any dependencies that could cause this problem).

This is what happens when I remove the "workaround" and add `<scope>compile</scope>` to my pom.xml file:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building ala-cas 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-core/3.2.6.RELEASE/spring-core-3.2.6.RELEASE.jar
Downloading: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-webmvc/3.2.6.RELEASE/spring-webmvc-3.2.6.RELEASE.jar
Downloading: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-beans/3.2.6.RELEASE/spring-beans-3.2.6.RELEASE.jar
Downloading: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-web/3.0.5.RELEASE/spring-web-3.0.5.RELEASE.jar
Downloading: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-context/3.2.6.RELEASE/spring-context-3.2.6.RELEASE.jar
Downloaded: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-web/3.0.5.RELEASE/spring-web-3.0.5.RELEASE.jar (387 KB at 106.5 KB/sec)
Downloaded: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-webmvc/3.2.6.RELEASE/spring-webmvc-3.2.6.RELEASE.jar (623 KB at 163.0 KB/sec)
Downloaded: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-beans/3.2.6.RELEASE/spring-beans-3.2.6.RELEASE.jar (598 KB at 147.3 KB/sec)
Downloaded: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-core/3.2.6.RELEASE/spring-core-3.2.6.RELEASE.jar (851 KB at 209.5 KB/sec)
Downloaded: http://oss.sonatype.org/content/repositories/releases/org/springframework/spring-context/3.2.6.RELEASE/spring-context-3.2.6.RELEASE.jar (845 KB at 197.7 KB/sec)
[INFO]
```

see the **spring-web-3.0.5.RELEASE.jar** ?

**Comment by mbohun** [comment]
"Why do you add `cas-server-webapp-support` into the pom?"

well [this](https://github.com/AtlasOfLivingAustralia/ala-cas) is an existing CAS project (based on jasig cas-3.4.2) i am upgrading it to jasig cas-4.0.x and the existing code i am upgrading is using a custom version of `org/jasig/cas/web/flow/GenerateServiceTicketAction.java` and that in turn seems to be using `class CookieRetrievingCookieGenerator` from `cas-server-webapp-support`; if I remove `cas-server-webapp-support` from the pom.xml i end up with:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/hor22n/src/jasig-cas-4.0.1-overlay-template.git/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java:[28,33] cannot find symbol
  symbol:   class CookieRetrievingCookieGenerator
  location: package org.jasig.cas.web.support
[ERROR] /Users/hor22n/src/jasig-cas-4.0.1-overlay-template.git/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java:[51,13] cannot find symbol
  symbol:   class CookieRetrievingCookieGenerator
  location: class org.jasig.cas.web.flow.GenerateServiceTicketAction
[ERROR] /Users/hor22n/src/jasig-cas-4.0.1-overlay-template.git/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java:[99,64] cannot find symbol
  symbol:   class CookieRetrievingCookieGenerator
  location: class org.jasig.cas.web.flow.GenerateServiceTicketAction
[INFO] 3 errors 
```

**Comment by mmoayyed** [comment]
Run a mvn dependency:tree and see where those are coming from. I am not convinced the support library is causing the issue because it tied with the version of CAS used. It does not have its own Spring jars. All spring functionality is shared by all CAS modules.

**Comment by battags** [comment]
Just a note that your overlay template (linked above) references Spring 3.2.2 while 4.0.2 (which it looks like the template references) uses  <spring.version>3.2.6.RELEASE</spring.version>.

It doesn't solve the 3.0.5 problem (which I'm looking into now) but you may want to get those versions to match also :-)

**Comment by mmoayyed** [comment]
I ran a dependency tree on your project. There is no evidence of spring web 3.0.5. I also built the package and looked at all the jars. No evidence of spring web 3.0.5

**Comment by battags** [comment]
It appears to possibly be downloaded due to a reference in some other library but isn't actually included (at least as far the dependency:tree is concerned)

**Comment by ofranco** [comment]
I know it is a bit too late to reply to this question (ps : i don't want to re-open the bug), but i have the same problem in my cas war overlay (4.0.7). I need to add a small class with dependencies on cas-server-webapp-support and adding this dependencies results in fetching transitive dependencies for inspktr which add conflicting spring dependencies (spring-*-3.0.5). A workaround is to add the dependency without retrieving transitive ones :
   <dependency>
     <groupId>org.jasig.cas</groupId>
     <artifactId>cas-server-webapp-support</artifactId>
     <version>${cas.version}</version>
     <scope>compile</scope>
     
     <exclusions>
       <exclusion>
         <groupId>*</groupId>
         <artifactId>*</artifactId>
       </exclusion>
     </exclusions>
   </dependency>
