### ISSUE TITLE
Upgrade CAS 4.0.x to Pac4j 1.7.x

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1030]

**Comment by mmoayyed** [comment]
Adding @leleuj . Not sure you received the notice.

**Comment by leleuj** [comment]
I get it, it's in the TODO among other things ;-)

**Comment by mmoayyed** [comment]
Copy that!

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1037
