### ISSUE TITLE
Allow CAS to act as a SAML SP

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1033]
We should take advantage of pac4j. It already handles this type of integration well.

**Comment by mmoayyed** [comment]
Probably better done after https://github.com/Jasig/cas/issues/1046

**Comment by leleuj** [comment]
Since pac4j v1.5.0, you can already turn the CAS server into a SAML client.

And the CAS server 4.1 relies on pac4j v1.7.1 (https://github.com/Jasig/cas/blob/master/pom.xml#L1590) with the the new SAML support you backported from the version 1.8.0.

**Comment by mmoayyed** [comment]
I am waiting for the j2e module's release on this one. There are some filters I would like to be able to define in our Spring context and what exists today does not allow it. I marked this under 4.2 so that we can get to it in proper time, and maybe even use 1.8 by then

**Comment by leleuj** [comment]
I thought you wanted to delegate the authentication to a SAML IdP: can you elaborate a little more on how you want to use the j2e-pac4j filters? Thx

**Comment by mmoayyed** [comment]
yeah that's the idea. I was thinking to base that work off of the pac4j-j2e-demo where it uses RequiredAuthnFilters to handle redirects to the IdP.

**Comment by mmoayyed** [comment]
We could also consider how changes affect services. So instances, certain services may want to always redirect to an IDP, some may want to present the CAS UI with an additional link that redirects to the IDP.

**Comment by mmoayyed** [comment]
Do this after https://github.com/Jasig/cas/issues/1046

**Comment by leleuj** [comment]
@mmoayyed : after a discussion with a pac4j adopter, I realized that some people were not looking for a `j2e-pac4j` library, nor for a `spring-security-pac4j`, but for a `spring-webmvc-pac4j` library as they don't have a simple J2E web application, but a Spring MVC one: is it you case? does it make sense?

**Comment by mmoayyed** [comment]
I am not exactly sure what that would mean; a spring webmvc app is a j2ee app, right? What would they want in a webmvc version of pac4j? In the case of adding saml sp support to CAS, I think everything we have right now for j2e of pac4j should work just fine, but obviously, once we start work, we might find a few gaps.

**Comment by leleuj** [comment]
Let me elaborate a little more on this.

Currently, you have two options:

1) you have a simple J2EE webapp (with or without Spring), it means you have filters and servlets so when it comes to security, you can use `j2e-pac4j` library and you have a `RequiresAuthenticationFilter` to protect urls and a `CallbackFilter` to finish indirect authentication processes

2) you have a Spring Security webapp, it means you have a Spring security context and Spring Security filters, you can use `spring-security-pac4j` library and use the Spring Security `ClientAuthenticationFilter `to finish indirect authentication processes.

But let's imagine you have a Spring Web MVC webapp. Do you want to use the `j2e-pac4j` library and its "basic" filters or do you want to add the "complex" Spring Security library to your project?

I think none. What you want is the `spring-webmvc-pac4j` library with its `RequiresAuthentication` annotation (to be used on controllers) to secure urls and its `CallbackController` to finish indirect authentication processes.

Does it make more sense?

**Comment by mmoayyed** [comment]
Yes that makes sense. I imagine using native filters in a webmvc app wouldnt be too difficult if those filters can be created via Spring's delegate, but obviously, annotations would make it easier, and if since we are trying to move in that direction with cas as well, I imagine that would be very useful.

**Comment by leleuj** [comment]
Coo! That's the idea, I'm working on it.

**Comment by mmoayyed** [comment]
:+1:

**Comment by spaetow** [comment]
Would this cover a case like this:

Org uses CAS. Wants to continue using CAS, but has some users who want to authenticate to a Shib IdP (i.e. dropdown and choose the IdP). CAS then takes Shib response and generates CAS response to that... thoughts?

**Comment by mmoayyed** [comment]
Yes this is exactly that.

**Comment by leleuj** [comment]
I finally came to a solution based on a Spring MVC interceptor (instead of an annotation). Here is the version 1.0.0-SNAPSHOT: https://github.com/pac4j/spring-webmvc-pac4j

**Comment by mmoayyed** [comment]
Excellent. Very impressive. I imagine it would be much easier for CAS to use this sort of library.

**Comment by leleuj** [comment]
That's exactly the idea. When it will be released (in a few weeks), I'd like to propose to replace Spring Security by spring-webmvc-pac4j both in the CAS server and in the management webapp.

**Comment by mmoayyed** [comment]
I am for that idea. SS seems overkill for what we are using it.

**Comment by mmoayyed** [comment]
created #1250 

There is still work to be done to automate and make this even easier.

**Comment by mmoayyed** [comment]
I also think that buttons on the login page should show up automatically, if the URL is defined. Much like what we do with openid.

**Comment by mmoayyed** [comment]
Closing in favor https://github.com/Jasig/cas/issues/1250
