### ISSUE TITLE
The build could not read 1 project -> [Help 1]

### ISSUE THREAD

**Issue by thaednevol** [Jasig/cas#1036]
I downloaded the last source code from git, and when I do:

mvn3 -U -Dmaven.skip.test=true clean package install

Shows:

[INFO] Scanning for projects...
Downloading: http://developer.ja-sig.org/maven2/org/jasig/parent/jasig-parent/39/jasig-parent-39.pom
178b downloaded  (jasig-parent-39.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - RETRYING
Downloading: http://developer.ja-sig.org/maven2/org/jasig/parent/jasig-parent/39/jasig-parent-39.pom
178b downloaded  (jasig-parent-39.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - IGNORING
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

**Comment by mmoayyed** [comment]
What version of maven is this? 

The parent pom is at 40. The code you have appears to be stale.

**Comment by thaednevol** [comment]
I've done in two machines:

mvn -version
Apache Maven 2.2.1 (rdebian-17)
Java version: 1.8.0-ea
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: es_CO, platform encoding: UTF-8
OS name: "linux" version: "3.19.0-22-generic" arch: "amd64" Family: "unix"

mvn3 -version
/usr/lib/jvm/java
Apache Maven 3.0.3 (rNON-CANONICAL_2013-07-20_13-27_mockbuild; 2013-07-20 06:27:59-0500)
Maven home: /usr/share/maven3
Java version: 1.6.0_35, vendor: Sun Microsystems Inc.
Java home: /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-131.21.1.el6.x86_64", arch: "amd64", family: "unix"

**Comment by mmoayyed** [comment]
Well Maven2 and OpenJDK6 are no longer supposed. In fact, I dont think OpenJDK is supported at all. See the requirements doc for more info.

**Comment by mmoayyed** [comment]
http://jasig.github.io/cas/development/planning/Installation-Requirements.html

**Comment by thaednevol** [comment]
Sorry, but now I have:

mvn3 -version
/home/ehurtado/jdk1.7.0_79/
Apache Maven 3.0.3 (rNON-CANONICAL_2013-07-20_13-27_mockbuild; 2013-07-20 06:27:59-0500)
Maven home: /usr/share/maven3
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /home/ehurtado/jdk1.7.0_79/jre
Default locale: es_CO, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-131.21.1.el6.x86_64", arch: "amd64", family: "unix"

And:

rm -Rf ~/.m2/repository/

The problem persists

**Comment by thaednevol** [comment]
With this machine it builds correctly:

mvn -version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_51, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: es_CO, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-22-generic", arch: "amd64", family: "unix"

**Comment by mmoayyed** [comment]
Take a look at our Travis builds. Those are the environments we first and foremost support. Glad you were able to build. Make sure to always pull from master if you are building from source.
