### ISSUE TITLE
Documentation: sample Pooled LDAP Authentication is leaking thread on redeloyement

### ISSUE THREAD

**Issue by NicolasMarcotte** [Jasig/cas#1038]
The bean *abstractConnectionPool* described there http://jasig.github.io/cas/4.0.x/installation/LDAP-Authentication.html , should have this attribute : *destroy-method="close"* to avoid thread leak on redployement

**Comment by leleuj** [comment]
I remember I used this `close` method indeed to free the resources. Would you mind sending a PR on the doc for that?

**Comment by NicolasMarcotte** [comment]
I never built the doc but it should not be a problem.

**Comment by NicolasMarcotte** [comment]
see #1039
