### ISSUE TITLE
Run cas with the tomcat maven plugin

### ISSUE THREAD

**Issue by cybrown** [Jasig/cas#1042]
When I run the project with the tomcat maven plugin, I always have a 404 error, but with the same war, in a "real" tomcat, it works perfectly.

Is there a specific configuration to use CAS within the tomcat maven plugin ?

I have bootstraped my project from the maven overlay example.

**Comment by mmoayyed** [comment]
Dont think so, no. Make sure you have right context defined.

**Comment by mmoayyed** [comment]
The webapp in the master branch runs the cas webapp with the jetty plugin. That might inspire you a bit further. I dont think the tomcat plugin is able to run with a more recent tomcat version. Are you using the same tomcat version when the app is deployed for "real"?

**Comment by cybrown** [comment]
No indeed, I am using tomcat 7 for the plugin and 8 for the real one...
I will check the jetty configuration if this is not the problem, thank you.

**Comment by mmoayyed** [comment]
Pleasure.
