### ISSUE TITLE
Table of Contents shows undefined for Firefox

### ISSUE THREAD

**Issue by miketaylr** [Jasig/cas#1044]
Originally reported here: https://www.reddit.com/r/firefox/comments/3dqo6p/firefox_behaving_poorly_in_some_websites/

The reason is because `generateTableOfContentsForPage` uses non-standard `innerText`, rather than `textContent`.

Changing:

```
$('#tableOfContents').append("<li><a href='#" + this.id + "'>" + alignment +
          this.innerText + "</a></li>");
```

to

```
$('#tableOfContents').append("<li><a href='#" + this.id + "'>" + alignment +
          this.textContent + "</a></li>");
```

Will fix it for all modern browsers.

**Comment by mmoayyed** [comment]
This should be fixed. Thanks for the report. Let us know if you still experience issues.

**Comment by miketaylr** [comment]
Thanks for the quick fix!
