### ISSUE TITLE
Update CAS to use pac4j 1.8

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1046]
Allows us to take advantage of SAML functionality and a lot more. @leleuj I wasn't sure what the planned release date is, so I marked this as 4.2. We may get to it earlier than 4.2 though.

While the upgrade will be easy, it would be great to benefit from the REST capabilities added in this new pac4j version by proposing a `Pac4jAuthenticatorWrapperHandler` to wrap pac4j `Authenticator` (like JWT, Mongo) which are not available in the CAS server.

**Comment by leleuj** [comment]
I don't think pac4j 1.8 will be released before CAS server 4.1 (as I guess, it is now a matter of weeks / days). As a matter of facts, most of the SAML update has been done in pac4j 1.7.1, which is already integrated in CAS server 4.1.

pac4j 1.8 is about REST support and I'm not sure it will be as interesting as the version 1.7 for CAS.

**Comment by mmoayyed** [comment]
Ah, great. OK. I dont think we have any backward compatibility issues between 1.7 and 1.8 as far the SAML update goes right? We did that test that heavily, so it would be fitting. 

I think it's also a good idea, once 1.8 is released to advertise the REST client in CAS docs.

**Comment by mmoayyed** [comment]
btw do you have a tentative timeline on when 1.8 might come out?

**Comment by leleuj** [comment]
I'll finish this month the main new supports (LDAP, DB) then I'll work on implementations starting by J2E and Play to test pac4j v1.8. I hope to make the release in october / november.

**Comment by mmoayyed** [comment]
@leleuj Shall we upgrade to RC1 and test it with CAS? Could leave the pull open until GA goes out. The upgrade allows us to focus on functionality that pac4j provides.

**Comment by leleuj** [comment]
Yes, we could first upgrade to RC1 and then to GA. In addition to the `Pac4jAuthenticatorWrapperHandler` to wrap a pac4j `Authenticator`, it might be a good idea to turn the `cas-server-support-pac4j` module configuration easy (as you did for protocol and registry supports).

**Comment by mmoayyed** [comment]
Sounds good. Sure. I don't know if we can automate authentication handlers, but that needs to be worked out.

**Comment by mmoayyed** [comment]
Wait for https://github.com/pac4j/pac4j/issues/282 and #1197 and #1189 to close first.

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1217. Per previous discussion, I upgraded to pac4j 1.8, enabled automatic configuration and added the authentication handler that wraps a pac4j authenticator and profile creator.
