### ISSUE TITLE
Add support for hazelcast ticket registry

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1047]
The hazelcast ticket registry that is developed by Unicon is a very suitable candidate at this point to be included in CAS. The module has proved itself to be very robust, easy to use and easy to configure and maintain and in many ways, it entirely deprecates the previous ehcache integration.  

Consider creating a new hazelcast-integration-support module, or some such and include the integration.@dima767 will follow up.

**Comment by mmoayyed** [comment]
I marked this as 4.1, because I think we can definitely stuff this in, as all code/docs are already available and it's just a matter of pulling it all together.

**Comment by dima767** [comment]
This will be entirely this code -> https://github.com/unicon-cas-addons/cas-addon-hazelcast-ticket-registry with conventional auto-configuration. Do not expect many "configuration knobs".
