### ISSUE TITLE
Cannot serialize ticket with EhcacheTicketRegistry

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1049]
See https://issues.jasig.org/browse/CAS-1494

**Comment by Ammar0** [comment]
I am using version "4.0.3" of CAS server.

**Comment by Ammar0** [comment]
Steps to reproduce the bug:
1. Use EhcacheTicketRegistry (http://jasig.github.io/cas/4.0.x/installation/Ehcache-Ticket-Registry.html)
2. Uncomment the "authenticationMetaDataPopulators" bean in "deployerConfigContext.xml" file

**Comment by mmoayyed** [comment]
OK, thanks. Will you be able to post a pull request? I think you already had the solution in the original JIRA, right?

**Comment by Ammar0** [comment]
Done !
I sent you a PR.
