### ISSUE TITLE
Failed to evaluate expression 'ROLE_ADMIN'

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1051]
On the cas-management-webapp, I have the following error:

```

[WARNING] /cas-management/
java.lang.IllegalArgumentException: Failed to evaluate expression 'ROLE_ADMIN'
	at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:14)
	at org.springframework.security.web.access.expression.WebExpressionVoter.vote(WebExpressionVoter.java:36)
```

```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 0): Property or field 'ROLE_ADMIN' cannot be found on object of type 'org.springframework.security.web.access.expression.WebSecurityExpressionRoot' - maybe not public?
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:226)
```

I fixed the problem by using: `access="hasRole('${cas-management.securityContext.serviceProperties.adminRoles}')"` in the `securityContext.xml` file: https://github.com/Jasig/cas/blob/master/cas-management-webapp/src/main/webapp/WEB-INF/spring-configuration/securityContext.xml#L47

Can someone confirm the issue?

**Comment by leleuj** [comment]
That's not the only problem I encounter: the CAS endpoint has changed in Spring Security with version 4.0: it's now `/login/cas` instead of `/j_spring_cas_security_check` -> Contacting Rob: https://jira.spring.io/browse/SEC-3053

**Comment by leleuj** [comment]
As we moved Spring Security from v3 to v4, it is necessary to take a look at: http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html

**Comment by mmoayyed** [comment]
Yes, this is already taken into account via this issue #496 

If you want to check out what's currently done, see https://github.com/uNICON/CAS/tree/mgmt-webapp

**Comment by leleuj** [comment]
OK. Waiting for your PR accordingly...

**Comment by mmoayyed** [comment]
We are very close. This is going to be a pretty big PR in fact and most of it is UX based. I am hoping we can finalize this by end of July and cut an RC1

**Comment by leleuj** [comment]
I can imagine it's a pretty big change. I wasn't sure you could make it. That's why I propose to drop the management webapp as editing JSON services is also fairly easy.

**Comment by mmoayyed** [comment]
I am in favor of that idea. We could push the app outside of the core project and move it over to another jasig sponsored project. I am just worried that it may not get enough attention afterwards. Could you please post a message to the cas user list and see how people feel about the move? is the app useful at all?

**Comment by leleuj** [comment]
Done. We'll see the feedbacks.

**Comment by rkorn86** [comment]
Im not on the mailing list, but i would love to see a nice management app, maybe dropping jsp and using jsf 2.2 instead. It would also be nice if the management app is able to handle the pluggable service store. So that either writing json files on disk or saving services via jpa is possible, by just changing the servicemanager in properties file.
I will have a closer look at the unicon branch tomorrow and build my custom overlay on top of it.
Thank you guys so far for your hard work :+1:

**Comment by mmoayyed** [comment]
Yes, service stores are pluggable. If you could test out the branch and let us know if you run into issues, that would be superb.

**Comment by rkorn86** [comment]
Issues are disabled in your fork. Should I open new Issues here or just comment them here?

For the last option: `javax.el.PropertyNotFoundException: Property 'enabled' not found on type org.jasig.cas.services.RegexRegisteredService`
```
57:             <tr id="row${status.index}"${param.id eq service.id ? ' class="added"' : ''}>
58:                 <td id="${service.id}" class="td1">${service.name}</td>
59:                 <td class="td2">${fn:length(service.serviceId) < 100 ? service.serviceId : fn:substring(service.serviceId, 0, 100)}</td>
60:                 <td class="ac td3"><img src="images/${service.enabled}.gif"
61:                                         alt="${service.enabled ? 'Enabled' : 'Disabled'}"/></td>
62:                 <td class="ac td4"></td>
63:                 <td class="ac td5"><img src="images/${service.ssoEnabled}.gif"
```

In `org.jasig.cas.web.flow.ServiceAuthorizationCheck` the `isEnabled` check was changed to `registeredService.getAccessStrategy().isServiceAccessAllowed()` so I guess `service.accessStrategy.serviceAccessAllowed` will be a propper jstl replacement.

**Comment by rkorn86** [comment]
Issues are disabled in your fork. Should I open new Issues here or just comment them here?
For the last option: 

1. I stored my services in /etc/cas/services/ in JSON Format. CAS-Server finds them showing the following output:
```
2015-07-28 09:01:39,895 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Reloading registered services.>
2015-07-28 09:01:39,904 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 3 services.>
```
However, management-app shows empty services warning and is displaying 3 (default?) services instead.
I have configured `service.registry.config.location=file:/etc/cas/services/` in cas-management.properties exactly like in my cas.properties.
PS: `file:/` prefix is needed in change of SPRING 3 -> 4. 

2. Editing and saving one of the default (and even a completely new) service results in ` Form validation has failed. Please fix the errors before attempting to save again.` without highlighting the field, that is missing or wrong.

**Comment by mmoayyed** [comment]
We are still in the process of adding CRUD operations to the form. None of that is working at the moment, and should be addressed this week. We are focusing on the new UI at the moment and mapping JSON services to the form. Please watch the repo and I will keep you posted. I'll open up issues for the fork as well. Thanks for lending a hand in testing this.

**Comment by mmoayyed** [comment]
Closing this in favor of https://github.com/Jasig/cas/issues/1051
