### ISSUE TITLE
Problem with Java 8 and CAS v4.0.3: Update Spring version to 3.2.9 due to Spring issue SPR-11719

### ISSUE THREAD

**Issue by philippberger** [Jasig/cas#1056]
There is a problem in running CAS v4.0.3 with Java 8. Please update the Spring version to 3.2.9 due to Spring issue SPR-11719 (https://jira.spring.io/browse/SPR-11719).

**Comment by leleuj** [comment]
OK. Would you mind proposing a pull request for this upgrade on branch 4.0.x?

**Comment by philippberger** [comment]
Sure!
