### ISSUE TITLE
Add support for Token-based JWT authentication

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1060]
@epierce, could I have permission to grab the code you have here and adapt it to CAS4? Would you rather do that? I have recently run across a few use cases that could have benefited from this module very much and I'd like it to be part of CAS. 

https://github.com/epierce/cas-server-extension-token

**Comment by leleuj** [comment]
Shouldn't we use a more standard token format like JWT?

It makes me think that maybe we could wrap pac4j `Authenticator` (Mongo and JWT supports are available in pac4j but do not exist in the CAS server) in some `Pac4jAuthenticatorWrapperHandler`?

After the upgrade to pac4j v1.8.0.

**Comment by mmoayyed** [comment]
Both good ideas. Happy to work with available solutions. We should tackle this after the upgrade is complete.

**Comment by leleuj** [comment]
I updated the description of https://github.com/Jasig/cas/issues/1046 to track this new `Pac4jAuthenticatorWrapperHandler` idea.

**Comment by leleuj** [comment]
Upgrading to pac4j v1.8: https://github.com/Jasig/cas/pull/1217. This will allow the use of a JWT authenticator.

**Comment by mmoayyed** [comment]
@leleuj I think I may have found an issue with the Jwt authentication in pac4j. 

The Jwt authenticator/ProfileCreator uses the sub field in the JWT as the typedid to locate the user profile class. What should be the correct format for sub? 

If this is my JWT:

```json
{
    "iss": "Online JWT Builder",
    "iat": 1449935804,
    "exp": 1481471804,
    "aud": "www.example.com",
    "sub": "jrocket@example.com",
    "GivenName": "Johnny",
    "Surname": "Rocket",
    "Email": "jrocket@example.com",
    "Role": [
        "Manager",
        "Project Administrator"
    ]
}
``` 

then pac4j would never be able to build the profile for me. The `ProfileHelper.buildProfile` does not correctly process the sub field, because it expects `#` field, and I am not sure how to specify one without creating my own creator.

Does that make sense? Is this something pac4j should handle for me, or is it expected of me to create my own profile creator?

**Comment by mmoayyed** [comment]
I found the `JwtGenerator`. Will try with that and see what works. I am assuming I should pass an HttpProfile to the generator?

**Comment by leleuj** [comment]
Currently, the `JwtAuthenticator` only validates JWT tokens which have been generated by the `JwtGenerator` which takes a `HttpProfile` as input.

We can certainly improved this behaviour to handle JWT tokens which have not been created by the `JwtGenerator` and return a default `HttpProfile` with identifier and attributes. Does it make sense?

**Comment by mmoayyed** [comment]
Yes it does. In theory, I should be able to use any service/component to create my JWT.

**Comment by leleuj** [comment]
Right. I see: https://github.com/pac4j/pac4j/issues/394 I guess we'll have a pac4j v1.8.2 soon ;-) Will handle this week unless you beat me...

**Comment by mmoayyed** [comment]
I might :) I am attempting to focus on https://github.com/Jasig/cas/pull/1343 for now. Once this finalizes, I will switch back to pac4j goodness.

**Comment by mmoayyed** [comment]
For now, if we are able to document what deployers should do and what values they should provide when creating their own JWT, I think that would be fine. This will free up folks to be forced to using a java framework to create JWTs which will have us gain broader adoption.

**Comment by leleuj** [comment]
You're right: if we want to target 100% of the deployers, we need to explain how JWT tokens should be generated but I'm pretty sure most of the deployers will use the `JwtGenerator` as it makes things easy.

**Comment by mmoayyed** [comment]
True, but it also has the requirement that a deployer knows how to write Java code, (which is somewhat unlikely) whereas I can go online and find a JWT generator and create one very easily, or consider that a deployer may know Python better than Java, and setting up a pac4j development environment to use that specific class is a bit too much. 

Ideally, we should not have to explain, and we should not require a specific generator. JWTs should simply work regardless of how they are generated and by which component.

**Comment by leleuj** [comment]
Yes, but you need to setup the secret keys and choose the hashing / encryption algorithms. In all cases, I will improve the `JwtAuthenticator`.
