### ISSUE TITLE
Add support for DuoSecurity AuthN

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1074]
Partially related to #572

There exists a DuoAuthenticationHandler as part of CAS MFA. Bring that module over to core,  as initiative to start supporting MFA. Note that this simply provides a handler; foundation support for MFA will still need to be hashed out and designed. We are doing this one step at a time.

@dima767 may get around to this issue. A separate CAS module with support for DuoSecurity makes sense. Also related to #1070

**Comment by dima767** [comment]
Would love to have `4.1` released so the `master` branch could start marching towards `4.2`

**Comment by drumadrian** [comment]
Does this mean there will be a separate module for DuoSecurity in the next release?

**Comment by dima767** [comment]
Maven module, yes, but just the basic Duo AuthenticationHandler implementation. The entire mfa machinery would need to be built elsewhere.

**Comment by drumadrian** [comment]
sounds cool.  Thanks!  I'm still very new to CAS so I'm working on customizing the Maven overlay for initial setup.

**Comment by mmoayyed** [comment]
@dima767 should be ready for this one. we are also now on Spring 4.2 in master :)

**Comment by mmoayyed** [comment]
Let's go with `cas-server-integration-duo`
