### ISSUE TITLE
Publish CAS Events

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1080]
Allow CAS to publish events based on Spring, specific to the following cases:

- Establishing of an SSO session
- Destruction of an SSO session
- Generation of a Service Ticket
- Validation of a Service Ticket
- Adding/Removing Services

(The list above closely follows the inspektr AUDIT events) 

Should probably happen once we upgrade to Spring 4.2. This opens up a possibility to register Spring's `ApplicationListener`s for event(s) of interest and proceed with custom computation(s) based on those events.

**Comment by mmoayyed** [comment]
https://spring.io/blog/2015/02/11/better-application-events-in-spring-framework-4-2

**Comment by mmoayyed** [comment]
https://github.com/Unicon/cas-addons/tree/master/src/main/java/net/unicon/cas/addons/info/events

**Comment by leleuj** [comment]
What's the goal of publishing all these events? Compared to the audit logs?

**Comment by mmoayyed** [comment]
The audit log is purely for auditing and tracking purposes. It makes upper management happy basically, and allows the CAS deployer to keep track of sometimes strange login activity. 

This feature on the other hand is targetted towards the CAS developer. It is the case where you would want to gather stats about a particular CAS event and do something about them later. While the audit log has a fixed and clear format, this will be in the hands of the deployer to decide what should be saved, how and where in a very decoupled manner without ties to any hardcore APIs. It has other use cases, such as keeping track of login history to be used with MFA use cases.

**Comment by mmoayyed** [comment]
Depends on https://github.com/Jasig/cas/issues/1084

**Comment by mmoayyed** [comment]
Should be done after #1192 closes. The event support should be in its own module.

**Comment by mmoayyed** [comment]
another example of this use case is, cache listeners for hazelcast for instance can start to publish events when tgts expire. so that the logout  manager can then be invoked without so wiring the logout module to the hazelcast module. 

or think about gathering stats on casimpl so that we could later do risk based authn.

**Comment by mmoayyed** [comment]
working on this issue next.
