### ISSUE TITLE
how to integrate a  authority system to cas?

### ISSUE THREAD

**Issue by mlc0202** [Jasig/cas#1088]
hello,I want to achieve a authority system in order to manage users,roles and functions uniformly in cas ,i consider it should be expanded by one point ,but i find none,so,if i import a authority system,what shoud i do?

**Comment by mmoayyed** [comment]
If you need a comprehensive authorization platform, you want to check out the Internet2 Grouper project. If you need to manage identities, you need a person registry. There is OpenRegistry, CPR and many other person registries. 

You may also want to check out the TIER project. 

Please use the CAS mailing lists for additional questions.
