### ISSUE TITLE
Consenting to Attribute Release

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1090]
https://wiki.jasig.org/display/CAS/CAS+4.2+Roadmap#CAS4.2Roadmap-ConsentingtoAttributeRelease

Provide an optional webflow to allow CAS to display a list of attributes that may be released to the application. Provide an option for the user to accept the release and a way to CAS to remember the user's choice.

**Comment by leleuj** [comment]
Shouldn't we rely on OAuth support for that?

**Comment by mmoayyed** [comment]
I think we should possibly refactor OAuth to delegate to this new screen. Folks that run OAuth could use consent, but those that don't cant rely on OAuth. We are turning this into a CAS feature, and not so much an OAuth feature.

**Comment by mmoayyed** [comment]
Deferring to #514  for now.
