### ISSUE TITLE
Fix Travis build

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1099]
Seems to fail during `mvn corbertura:cobertura ...`:

```
Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0:report (default-cli) on project cas-server: Build error: Either repository token or service with job id must be defined
```

Generated locally, but the Travis logs are truncated and the real error is not displayed.

**Comment by mmoayyed** [comment]
I started to experiment with Travis and turned on sudo: false. so far so good

**Comment by mmoayyed** [comment]
We may also want to remove http://developer.jasig.org/repo/content/groups/m2-legacy/

**Comment by leleuj** [comment]
Yes, I think this repository is used also during the release. Without any success.

**Comment by mmoayyed** [comment]
Build is fixed. I will remove cobertura and the legacy repo next and experiment again

**Comment by leleuj** [comment]
Do you intent to replace corbertura by something else or simply drop it?

**Comment by mmoayyed** [comment]
Well, I dont really know of a good replacement. I'll look around to see what exists, but otherwise we may just drop it.

**Comment by mmoayyed** [comment]
The cobertura plugin has issues; It cant at times parse the try-resource syntax, and it also complains about missing dependencies during instrumentation. It works to the point that it no longer crashes the build and runs, and submits test coverage data, partially. I will leave it there, and have opened up several issues for the plugin project owners.

**Comment by mmoayyed** [comment]
This is working fine now. The legacy repo is needed only for spnego module because of some dead dependencies that are not in central. I'll keep the issue open and monitor travis for a bit. Looks like Hazelcast tests are failing because of travis's environment somehow.

**Comment by mmoayyed** [comment]
Done.
