### ISSUE TITLE
4.1.0-RC1 fails to deploy

### ISSUE THREAD

**Issue by dima767** [Jasig/cas#1104]
* JDK: `java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)`

* Tomcat: `7.0.62`

* CAS: `4.1.0-RC1`

* Overlay: vanilla overlay with no customizations

After building and deployinmg to TC, getting the following exception, failing to deploy it:

```
...

Caused by: java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/LightClassmapListener
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
...
```

**Comment by mmoayyed** [comment]
@leleuj When you created the release, did you run the cobertura plugin? I think you did because RC1 is now instrumented with references to cobertura. That plugin should never be run directly. Did it somehow end up part of the release process?

**Comment by mmoayyed** [comment]
I think we might have to redo the release again, because this is obviously broken very badly.

**Comment by leleuj** [comment]
Indeed, it seems so. Though, I used `<cobertura.skip>true</cobertura.skip>` in the `nocheck` profile. Taking a look at the build logs, I see: `[INFO] Instrumentation was successful.`. So the plugin was not really disabled and instrumentation must have happened.
The RC1 won't be of any use. Thus, I won't make any announcement. I'll commit the changes in the release process and cut a RC2 next week with the cobertura plugin disabled.

**Comment by mmoayyed** [comment]
How is that plugin activated in the release process? Which set of steps or phases trigger it?

**Comment by mmoayyed** [comment]
As far as I know, the only way that plugin gets activated is if it's explicitly invoked on the command line and its goal called out. Otherwise, there is no need to skip it. It's only used by the CI build system to report test coverage, and should not be run automatically. I don't think any changes to the build are required unless a phase in the release cycle triggers that plugin, which would be very very odd.

**Comment by leleuj** [comment]
I need to investigate, but I only ran: `mvn release:clean release:prepare` and `mvn release:perform`.

**Comment by mmoayyed** [comment]
@leleuj Would you rather I take a look and see if I can make sense of this? and if so, cut RC2? I'll be out travelling for the next couple of days, and so today is my only open window to assist.

**Comment by leleuj** [comment]
Any analysis will be helpful. Thanks.

**Comment by mmoayyed** [comment]
Sure. I'll take a look later today.

**Comment by mmoayyed** [comment]
I was able to duplicate the problem. Disabled cobertura for the release, released RC2 and tested it. All systems go.

**Comment by leleuj** [comment]
Thanks. Great!

**Comment by leleuj** [comment]
Just updated the documentation: https://github.com/Jasig/cas/commit/4cd182937b71d6c9ff6454d4095df62c93489bc3
