### ISSUE TITLE
How to get additional parameter when i use RESTFul Api 

### ISSUE THREAD

**Issue by LiuCao** [Jasig/cas#1106]
I follow this (http://jasig.github.io/cas/development/protocol/REST-Protocol.html) tutorial done, and all through. But I would like to submit additional arguments, and save the parameters submitted to a user table.(Because I see this "POST / cas / v1 / tickets HTTP / 1.0 username = battags & password = password & additionalParam1 = paramvalue ")
I want to save the mobile device ID, and do push notifications with MQTT.
We hope to get everyone's help
THX!

**Comment by leleuj** [comment]
Please use the CAS mailing lists for any questions: http://jasig.github.io/cas/Mailing-Lists.html. Thanks.
