### ISSUE TITLE
Ask how the client has multiple domain names use cas?

### ISSUE THREAD

**Issue by abcijkxyz** [Jasig/cas#1116]
My site use multiple domain names point to the same Web App,
Whether it is a single sign-on service or web application.
Fixed domain name can not be written in the configuration inside,
Ask how to use the cas, can an example?

**Comment by mmoayyed** [comment]
Are you asking about the CAS client  or CAS server?

**Comment by mmoayyed** [comment]
Please use the cas mailing lists for further questions.
