### ISSUE TITLE
Support Service-based Authentication

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1119]
CAS presently supports a RequiredHandlers array in its Service Registry. This is used to ensure the collection handlers that should successfully pass before access to service is granted.

Expand this concept into an abstraction with the following options:

1. The ServiceRegistry should support a field for authentication strategy
2. Available strategies may be:

- Default: default behavior where all handlers are tried and CAS would roll over to the next one in the list
- Required Handlers: same as above
- Chosen Handlers: similar to above, except these are the handlers that should be selected by CAS and run only for that service, so that rollover functionality is intercepted to only choose handlers a service supports, that talk to a specific account store. 
- Alternative CAS Server
- WS-FED Server
- SAML IdP
- Custom authentication token as a minimum for MFA purposes

**Comment by mmoayyed** [comment]
Depends on #1085 and https://github.com/Jasig/cas/issues/1033

**Comment by leleuj** [comment]
So your idea is to always have the same authentication manager and drive the way authentication happens based on this strategy, isn't it?

**Comment by mmoayyed** [comment]
Exactly. I can speculate that AuthN Manager API may need to change, but in a broader perspective, I would like the following options:

1. A service that requests authentication from CAS dictates that requests should always be routed to an external WS-FED IDP. Right now, adopters have to muck with the webflow to make this happen. (Of course other configuration is needed to make it all work later)

2. A service that requests authentication from CAS dictates that requests should always be routed to an external CAS Server. Right now, adopters have to muck with the webflow to make this happen. (Of course other configuration is needed to make it all work later)

3. A service that requests authentication from CAS dictates that requests should always be routed to an external SAML IDP. Right now, adopters have to muck with the webflow to make this happen. (Of course other configuration is needed to make it all work later)

4. A service may dictate to CAS that it should always use AuthN Handler XYZ when authenticating users. Rather than looping through everything, a specific handler will be chosen instead. I have had many reports on this use case, where user account stores are spread far and wide and the looping behavior causes undesired effects when it comes to resolving principals specially when these account stores are not exactly "organized" and there is duplication and overlap. 

5. I am also thinking about authentication methods for MFA. A service may dictate that it should always use Duo Security, or YubiKey for 2FA authentication. An adopter could indicate that access to this service must always go through 2FA. (There is also the use case where MFA is triggers based on a user attribute for a Principal but I am leaving that out for now). This use case is inspired by the CAS MFA work Unicon has done, a project that has gained substantial momentum and adoption and there is strong interest to build similar if not exact functionality into CAS itself. 

The above strategies are not mutually exclusive. One may be able to mix and match, so we should that gotcha into consideration during the design.

**Comment by mmoayyed** [comment]
Note that at least for Item 5 above, the same AuthN Manager will not be enough. Additional refactoring may be required to separate the authentication from the CAS interface and the ticket granting logic. I am evaluating the CAS MFA work one piece at a time and my goal is to slowly build up the needed components based on that work to realize MFA in CAS itself.
