### ISSUE TITLE
Update CAS Protocol to include parameter info on validation format

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1125]
CAS Protocol should be updated to include a new parameter for service ticket validation, which would indicate the output response type of the validation result. This would be a `format` parameter to the `serviceValidate` endpoint, that is optional, with values such as XML and JSON.

**Comment by leleuj** [comment]
Glad we find some agreement. I think it must be discussed (at least shared) on the mailing list.

**Comment by mmoayyed** [comment]
Sure. I'll publish a post, but given recent rate of activity and everyone's schedule, I am inclined to move on lazy consensus if there are no responses.

**Comment by leleuj** [comment]
Sure.
