### ISSUE TITLE
Broken links in 4.1.x/Upgrade-Guide.md

### ISSUE THREAD

**Issue by robertoschwald** [Jasig/cas#1127]
http://jasig.github.io/cas/4.1.x/planning/Upgrade-Guide.html

 - Release-Policy.md is missing
 - Maven-Overlay-Installation.html location needs to be fixed

Will provide a PR.

**Comment by robertoschwald** [comment]
Release-Policy.md I couldn't find in the sources. It is available on http://jasig.github.io/cas/developer/Release-Policy.html. Any hints? The other links are already fixed locally. 
Note: I accidentially pushed my forked fix branch for the issue to the repo and immediately removed it as I noticed it. (Thanks to my Tower git tool, grr. Sorry.)

**Comment by robertoschwald** [comment]
Found it directly in gh-pages. Assuming it's for direct edititing.

**Comment by mmoayyed** [comment]
Yes it is.

**Comment by mmoayyed** [comment]
Merged via #1128
