### ISSUE TITLE
The proxy service how to configure the server?

### ISSUE THREAD

**Issue by MetSystem** [Jasig/cas#1138]
Unable to get PGT
1. The cas server for ST
2. Take ST application PGT
What do you need the cas server side configuration

pgtUrl  
Unable to get the cas server for me  pgtId and pgtIou param
```cs
https://wiki.jasig.org/display/CAS/Proxy+CAS+Walkthrough
Step Three: dig out the PGT
Now our first application knows who the user is and has a Proxy Granting Ticket IOU. To find the real PGT we look in the apache access log for foo.bar.com and hunt out the request made by CAS to deliver the PGT:

foo.bar.com - - [10/Dec/2003:09:28:15 +0000] "GET
/pgtCallback?pgtIou=PGTIOU-85-8PFx8qipjkWYDbuBbNJ1roVu4yeb9WJIRdngg7fzl523Eti2td
&pgtId=PGT-330-CSdUc5fCBz3g8KDDiSgO5osXfLMj9sRDAI0xDLg7jPn8gZaDqS HTTP/1.1" 200 13079
```

**Comment by mmoayyed** [comment]
Please use the CAS mailing lists to explain what you are trying to do and what error messages you receive.

**Comment by MetSystem** [comment]
I, according to the cas protocol custom single sign-on access to the site WebA, WebA repositioned to cas certification, verification after a successful return to WebA, WebA request cas by address 
 http://www.cas.com/serviceValidate?Ticket=ST-956-Lyg0BdLkgdrBO9W17bXS&service=http://WebA&pgtUrl=http://WebA/pgtCallback to obtain PGT
, cas back to http://WebA/pgtCallback, I can't get at http://WebA/pgtCallback
```cs
String pgtIou = Request. The QueryString [" pgtIou "];
String pgtId = Request. The QueryString [" pgtId "];
```
Cas didn't give me pgtIou pgtId

**Comment by MetSystem** [comment]
```xml


<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
	<cas:authenticationFailure code='INVALID_PROXY_CALLBACK'>
		The supplied proxy callback url &#039;http://localhost:21593/MyWebSite/ProxyService.aspx&#039; could not be authenticated.
	</cas:authenticationFailure>
</cas:serviceResponse>
```

**Comment by MetSystem** [comment]
@mmoayyed 
How can I solve this problem
