### ISSUE TITLE
The proxy service how to configure the server????

### ISSUE THREAD

**Issue by MetSystem** [Jasig/cas#1140]
I, according to the cas protocol custom single sign-on access to the site WebA, WebA repositioned to cas certification, verification after a successful return to WebA, WebA request cas by address 
 http://www.cas.com/serviceValidate?Ticket=ST-956-Lyg0BdLkgdrBO9W17bXS&service=http://WebA&pgtUrl=http://WebA/pgtCallback to obtain PGT
, cas back to http://WebA/pgtCallback, I can't get at http://WebA/pgtCallback
```cs
String pgtIou = Request. The QueryString [" pgtIou "];
String pgtId = Request. The QueryString [" pgtId "];
```
Cas didn't give me pgtIou pgtId

```xml
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
	<cas:authenticationFailure code='INVALID_PROXY_CALLBACK'>
		The supplied proxy callback url &#039;http://localhost:21593/MyWebSite/ProxyService.aspx&#039; could not be authenticated.
	</cas:authenticationFailure>
</cas:serviceResponse>
```

If the cas server to configure this, this configuration is added to the where?
```xml
<property name="attributeReleasePolicy">
    <bean class="org.jasig.cas.services.ReturnAllowedAttributeReleasePolicy"
            p:authorizedToReleaseProxyGrantingTicket="true" />
</property>
```
from http://jasig.github.io/cas/4.1.x/installation/Configuring-Proxy-Authentication.html#cas20proxyhandler

**Comment by mmoayyed** [comment]
You need to authorize proxy for the application:
http://jasig.github.io/cas/4.1.x/installation/Service-Management.html#configure-proxy-authentication-policy

If you need the PGT in the response directly:
http://jasig.github.io/cas/4.1.x/installation/Configuring-Proxy-Authentication.html

Please use the CAS mailing list for questions. This area is reserved for bug reports and issue tracking.

**Comment by MetSystem** [comment]
deployerConfigContext.xml 
add
```cs
<bean class="org.jasig.cas.services.RegexRegisteredService"
         p:id="10000001" p:name="HTTP and IMAP"
         p:description="Allows HTTP(S) and IMAP(S) protocols"
         p:serviceId="^(https?|imaps?)://.*" p:evaluationOrder="10000001">
    <property name="proxyPolicy">
        <bean class="org.jasig.cas.services.RegexMatchingRegisteredServiceProxyPolicy"
            c:pgtUrlPattern="^https?://.*" />
    </property>
</bean>
```
Tomcat is unable to start.

**Comment by MetSystem** [comment]
remove
```xml
<property name="proxyPolicy">
        <bean class="org.jasig.cas.services.RegexMatchingRegisteredServiceProxyPolicy"
            c:pgtUrlPattern="^https?://.*" />
    </property>
```
Tomcat to normal boot

**Comment by MetSystem** [comment]
```cs
Please use the CAS mailing list for questions. 
```
I'm sorry
I don't know where is the feedback, only know a lot.

**Comment by mmoayyed** [comment]
See the "Mailing Lists" at the top of the documentation page.

Or:
http://jasig.github.io/cas/Mailing-Lists.html

**Comment by MetSystem** [comment]
And I don't know this configuration which is added to what part of the documents and files.

**Comment by MetSystem** [comment]
1.authorize proxy for the application
2.PGT in the response directly
This is the demo?
