### ISSUE TITLE
Translations of missing username / password field not working

### ISSUE THREAD

**Issue by frittentheke** [Jasig/cas#1148]
There seems to be an issue with the translations of username or password missing error messages. 

The message key is simply different in the messages.properties and messages_$LANG.properties files.

 required.username vs. username.required / required.password vs. password.required.

**Comment by mmoayyed** [comment]
We don't actively maintain any of the language bundles. The only one that is actually maintained is messages.properties. You are welcome to submit PRs with translations.

**Comment by frittentheke** [comment]
It's not a missing translation, it's the message key that mismatches between English and ALL translation files.

I shall do a pull request if that helps.

**Comment by mmoayyed** [comment]
Please do. We also dont maintain the keys :) All those files are completely ignored, and only maintained by people who really understand the language. Values or otherwise regardless.

**Comment by mmoayyed** [comment]
https://github.com/Jasig/cas/pull/1149
