### ISSUE TITLE
Move Inspektr AUDIT logs into a separate log file

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1154]
Presently, AUDIT logs are bundled inside the cas.log or console, etc. There should be a separate log file that specifically focuses on audit data. While audit data can still be shown in the general cas.log file, the new casAudit log file should only contain relevant inspektr data.

**Comment by frittentheke** [comment]
Totally agreed, that's what I configured immediately after installation.

Also please consider doing a single line per transaction logged, as that's much easier to parse and use for i.e. fail2ban.

**Comment by mmoayyed** [comment]
Sure. We have thought about providing alternate syntax for inspektr. Feel free to log an issue. @dima767  might get to it.

**Comment by mmoayyed** [comment]
See https://github.com/Jasig/inspektr/issues/3#issuecomment-141419058 for single-line format

**Comment by dima767** [comment]
Can't you just configure whatever the logging engine is being used (slf4j) destination based on inspektr's package category? I've done that and it appropriately routes audit log events to a sep. file configured.

**Comment by mmoayyed** [comment]
Yes, and that's the change.

**Comment by dima767** [comment]
Ah, sure. I view the world through the externalized config lenses and not embeded-in-war configs. OK, nothing to see here. Carry on ;-)

**Comment by mmoayyed** [comment]
:)

You may want to think about this https://github.com/Jasig/inspektr/issues/3#issuecomment-141419058 and adding support for JSON, YAML and other alternative formats that would be useful and easier to parse. Most of that data is fed into other external systems, and ought to be easy enough to parse.
