### ISSUE TITLE
Too many redirects error

### ISSUE THREAD

**Issue by fhperuchi** [Jasig/cas#1156]
Hi!

I am using JASIG CAS version 4.0.4 on a Elastic Beanstalk environment with Tomcat version 7. I have an app responsible for doing the authentication for my application that uses JASIG CAS Maven overlay and I configured the Memcached integration module. I am using Memcached via Amazon ElastiCache.

When I configure the load balacing for use just one machine for the authentication application and one machine for my application that will be authenticated by the authentication application, it works fine. But if I increase the machine number to 2 for the application that will be authenticated by the authentication application, I got the error below:

Browser error:
This webpage has a redirect loop
ERR_TOO_MANY_REDIRECTS

Elastic Beanstalk (Tomcat) error log:
2015-09-18 12:52:19,633 INFO [org.jasig.cas.client.proxy.ProxyGrantingTicketStorageImpl] - No Proxy Ticket found for PGTIOU-116-NB4CoStX5jsb6cynFgOP-cotador-auth.sulamerica.com.br
2015-09-18 12:52:19,633 INFO [org.jasig.cas.client.proxy.ProxyGrantingTicketStorageImpl] - No Proxy Ticket found for PGTIOU-116-NB4CoStX5jsb6cynFgOP-cotador-auth.sulamerica.com.br

Below my Maven (pom.xml) and CAS configuration files. Please, can you help me?

**pom.xml**

                 <dependency>
			<groupId>org.jasig.cas</groupId>
			<artifactId>cas-server-webapp</artifactId>
			<version>4.0.4</version>
			<type>war</type>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>org.jasig.cas</groupId>
			<artifactId>cas-server-core</artifactId>
			<version>4.0.4</version>
		</dependency>

		<dependency>
			<groupId>org.jasig.cas</groupId>
			<artifactId>cas-server-integration-restlet</artifactId>
			<version>4.0.4</version>
		</dependency>

		<dependency>
			<groupId>org.jasig.cas</groupId>
			<artifactId>cas-server-integration-memcached</artifactId>
			<version>4.0.4</version>
            <exclusions>
                <exclusion>
                    <groupId>net.spy</groupId>
                    <artifactId>spymemcached</artifactId>
                </exclusion>
            </exclusions>
		</dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>elasticache-java-cluster-client</artifactId>
            <version>1.0.61.0</version>
        </dependency>

**ticketRegistry.xml**

<beans>

    <bean id="ticketRegistry"
          class="org.jasig.cas.ticket.registry.MemCacheTicketRegistry"
          c:client-ref="memcachedClient"
          c:ticketGrantingTicketTimeOut="${tgt.maxTimeToLiveInSeconds}"
          c:serviceTicketTimeOut="${st.timeToKillInSeconds}" />

    <bean id="memcachedClient" class="net.spy.memcached.spring.MemcachedClientFactoryBean"
          p:servers="${memcached.servers}"
          p:protocol="${memcached.protocol}"
          p:locatorType="${memcached.locatorType}"
          p:failureMode="${memcached.failureMode}"
          p:transcoder-ref="kryoTranscoder">
        <property name="hashAlg">
            <util:constant static-field="net.spy.memcached.DefaultHashAlgorithm.${memcached.hashAlgorithm}" />
        </property>
    </bean>

    <bean id="kryoTranscoder"
          class="org.jasig.cas.ticket.registry.support.kryo.KryoTranscoder"
          init-method="initialize"
          c:initialBufferSize="8192" />
</beans>

**cas.properties**

sulamerica.auth.defaultSuccessUrl=https://my_host
server.name=https://my_host
server.prefix=${server.name}
cas.securityContext.status.allowedSubnet=0.0.0.0/0

cas.themeResolver.defaultThemeName=cas-theme-default
cas.viewResolver.basename=default_views

host.name=cotador-auth.sulamerica.com.br

tgt.maxTimeToLiveInSeconds=28800
tgt.timeToKillInSeconds=7200

st.timeToKillInSeconds=10

log4j.config.location=classpath:log4j.xml

password.policy.warnAll=false
password.policy.warningDays=30
password.policy.url=https://password.example.edu/change

memcached.servers=host_elasticache_cache_cluster:11211
memcached.hashAlgorithm=FNV1_64_HASH
memcached.protocol=BINARY
memcached.locatorType=ARRAY_MOD
memcached.failureMode=Redistribute

**Comment by leleuj** [comment]
Please ask your question on the mailing lists: http://jasig.github.io/cas/Mailing-Lists.html

As the problem seems to come from the number of servers, I would warn you about the necessity of using session affinity with the CAS server 4.0.x

**Comment by fhperuchi** [comment]
leleuj, I got this erro below when I clicked the link Subscribe (https://lists.wisc.edu/read/all_forums/subscribe?name=cas-user) to "CAS Community Discussion List (cas-user)"

Server Unavailable
Could not log you in because the server could not be reached.

:(

**Comment by leleuj** [comment]
Indeed. You shall try the Google group: https://groups.google.com/forum/?fromgroups#!forum/cas-user

**Comment by fhperuchi** [comment]
Thanks. I posted this error there.
