### ISSUE TITLE
issue with login throttling with InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter

### ISSUE THREAD

**Issue by jasonchw** [Jasig/cas#1173]
Hi there,

I was trying to enable login throttling with InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter, but found that the value stored in the AUD_USER column in COM_AUDIT_TRAIL table is "username+password", which doesn't match the value created in InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.constructUsername(final HttpServletRequest request, final String usernameParameter) method ("[username: username]"). I knew I can override the constructUsername() myself, but I think it is better to modify the code in InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter class to avoid confusion.

Thanks,
Jason

**Comment by mmoayyed** [comment]
Hi, this certainly sounds like a bug. What version of CAS are you using? 4.0.x? 4.1.x? master?

**Comment by jasonchw** [comment]
I am using 4.1.0. But I think the same issue exists in master too.

**Comment by mmoayyed** [comment]
Would you be willing to cook up a pull request? If you do, target it towards master, and we'll merge it back into 4.1.x for a patch release.

**Comment by mmoayyed** [comment]
Looking into this one next.
