### ISSUE TITLE
X.509 Authentication is not working on CAS 4.1.0

### ISSUE THREAD

**Issue by luneo7** [Jasig/cas#1180]
Due to conflicting BouncyCastle versions I am getting the following error:

Failed to define class org.bouncycastle.asn1.DEREncodable in Module "deployment.cas.war:main" from Service Module Loader: java.lang.SecurityException: class "org.bouncycastle.asn1.DEREncodable"'s signer information does not match signer information of other classes in the same package.

I thought that I was doing something wrong, but when I invetigated the matter it seems to be the references and dependencies that exists in the CAS project to the BouncyCastle library that are causing this problem.

You see, the vt-crypt dependency from the cas-server-support-x509 pom file pulls in bcprov-jdk15-1.45.jar, the Spring 4.0.1 dependency pulls in bcprov-jdk15on-1.50.jar, but it is discarted in favor of bcprov-jdk15on-1.51.jar defined in CAS's parent pom file. So in the end two version of BouncyCastle are deployed, 1.45 and 1.51, thus it is necessary to investigate how to fix that.

**Comment by mmoayyed** [comment]
It is simply a matter of excluding those dependencies from the modules.

**Comment by luneo7** [comment]
It is not simply a matter of excluding one of those dependencies, I tested that. What happens is that vt-crypt is dependent of bouncycastle 1.45, and the rest of the application is dependent of bouncycastle of at least version 1.50 (for example the saml 4.1.0 module and spring 4.0.1), and there are drastic api changes between those versions. If you exclude one version of bouncycastle, you'll get another exception, I think that what needs to be done is to change cas-server-support-x509 to use cyptacular instead of vt-crypt, and adjust five files to use cryptacular (X509SubjectPrincipalResolver.java, CRLDistributionPointRevocationChecker.java, X509SubjectPrincipalResolverTests.java, CertUtils.java, support/X509CredentialsAuthenticationHandlerTests.java), or rewrite those file to use bouncycastle alone.

**Comment by mmoayyed** [comment]
OK, thank you for the clarification. I imagine you can duplicate the problem with 404 right?

**Comment by mmoayyed** [comment]
I have marked this as a bug, and will find a solution rather soon.

**Comment by luneo7** [comment]
Sorry, it is happening with 4.1.0 and not 4.0.1. I already corrected the issue title.

**Comment by luneo7** [comment]
I created a gist with the necessary modifications (patches) to change the vt-crypt dependency to cryptacular: https://gist.github.com/luneo7/2f4c7d8cf0863a524a8c

**Comment by mmoayyed** [comment]
Would you be able to submit a PR?

**Comment by luneo7** [comment]
Do you want me to do that on the master or the 4.1.x branch?

**Comment by mmoayyed** [comment]
Master please, and we'll merge it into 4.1 out of band.
