### ISSUE TITLE
different behaviour for memory ticket registry and cache based registry

### ISSUE THREAD

**Issue by mduszyk** [Jasig/cas#1183]
v4.1.0
The problem is that when CAS is configured to use default in memory ticket registry it behaves differently than if cache based registry like hazelcast is used. The difference in behaviour is related to logout, after logout service ticket obtained before logout (tgt delete) is invalid in case of memory registry while in second situation (hazelcast) it stays valid.

The problem is that code which talks to registry relays on java references. For instance the case of generating service ticket, it pulls tgt ticket from registry (obtains reference from java hashmap), then it generates service ticket which is added to internal tgt object's map. There is no separate call to registry to update tgt ticket because it was done on the same object which is already stored there (modification via reference). Problem happens when cache based registry is used, then tgt ticket is pulled and modified, but modification is not pushed back to cache. Another problem is that service tickets are not explicitly deleted when deleting tgt ticket.

**Comment by mduszyk** [comment]
Here are modifications I did to make it work the same way in both cases:
https://github.com/mduszyk/cas/commit/3d1ea75b001b57b3694596cd891f54fe91e53b64

**Comment by mmoayyed** [comment]
Reviewed. This is certainly a valid concern, but the reason you get a different behavior is because by defaults, tickets are cleaned by via the ticket registry cleaner. In cache-based ticket registries, ticket clean up is handled by the cache eviction policy, and while you may remove a TGT, it's ST children will not be deleted unless the cache decides to do so. Each cache works differently, and as you said, due to object references, the eviction policy of the cache may not do what you expect it to.

Your approach unfortunately wont work because it breaks SLO. 

Have you considered activating the default ticket registry cleaner for the cache-based registry? Does that work?

**Comment by mduszyk** [comment]
But even if I activate registry cleaner, it will be doing cleanups at some rate. This means that the delay between clean-ups will be the time it is possible to have the state where ST ticket is valid after TGT was deleted. This will never happen in case of memory registry because TGT delete action makes it go into the state where ST in invalid instantly.

Second, look at this line:
https://github.com/mduszyk/cas/commit/3d1ea75b001b57b3694596cd891f54fe91e53b64#diff-c40a1eb262f1360be5db8cc1f1ddfc59R331
here ST ticket is generated and added to TGT but this change never persists (only local object is modified - not data stored in cache), while the same code works when memory registry is used because this change is persisted in memory.

So even if I use ticket registry cleaner, make it clean quite often, I will still face second issue with cache based registry where ST map change won't be saved on TGT object.

**Comment by mduszyk** [comment]
There is another thing to consider:
https://github.com/mduszyk/cas/commit/3d1ea75b001b57b3694596cd891f54fe91e53b64#diff-d1fc9be1d5472f66d85ee7caf079c957L121
I removed ST ticket removal here, and this change can have significant impact on the case where memory registry is used. I am experimenting here so not sure if it has to be removed. But thing to consider is the locking on the ticket object. While this will work in case of single CAS instance and memory based registry where it will always return the same object, it will behave much differently in case of cache based registry because it won't return the same object here. In fact it will return different object each time ticketRegistry.getTicket is called, and even if it cached it this object would be local to particular CAS instance, so critical section here becomes local here to each request (diff ticket object for each request) or in best case it will be local to particular CAS instance not whole cluster (only if ticket registry would implement a way to local cache java objects).

**Comment by mmoayyed** [comment]
I understand, thanks for explaining. I overlooked the issue of local references to objects, and yes, synchronizing on the ticket itself in cache-based registries may return different objects. We'll have to a better look at the ticket registry API. Your changeset is very helpful. I think this sort of change needs to be pushed down to the ticket registry itself. As you proceed with experiments, let us know how it goes.

**Comment by listaction** [comment]
mmoayyed: sounds like some that affects all cas based consumers of cas which is recommended approach for ha - cas. Thanks for reviewing the change - hope there's an urgency to fix this.

**Comment by mmoayyed** [comment]
Yes, possibly. We are presently working on CAS configuration automation and #493 . Once those get sorted out, they allow us to focus on issues like this next. I would think this is something we want to address for 4.2, but depending on the changeset and schedule, it might end up in a patch release as well. Thank you all for reporting and your analysis. We have not received any particular problem reports on this particular issue, but it may be that we have not actually run into it yet.

**Comment by mduszyk** [comment]
Could you clarify one thing for me, what should happen to ST ticket when TGT is deleted? Should TGT delete trigger deletion of ST tickets? For instance JPA ticket registry deletes service tickets:
https://github.com/mduszyk/cas/blob/4.1.x/cas-server-support-jdbc/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java#L91
When memory registry is used it will delete ST tickets from TGT ticket (what makes ST invalid I think), but ST entries are not removed from registry. In case of cache based registry ST are not deleted at all. I would expect that ST are deleted when TGT is deleted.

Then if ST should be deleted together with TGT there is a problem with moving this logic into registry because CentralAuthenticationServiceImpl has 2 separate fields: serviceTicketRegistry and ticketRegistry. When I was testing they both were pointing to the same registry object but if they point to different registries then deletion of TGT together with ST will need to be done in layer on top of registry.

**Comment by mmoayyed** [comment]
>I would expect that ST tickets are deleted when TGT is deleted.
Yes, that is what I expect to happen. Your analysis is perfectly correct. However, I do think we should also remove `serviceTicketRegistry`. I have never in practice seen a use case for that feature, and never actually seen anybody turn it on. I think it was originally added for the JBoss Ticket registry caching, which is now removed and we no longer support. The feature is also not advertised in docs and it's very hidden unless you have looked around the internal configuration. So, I am inclined to remove that functionality and move the logic down to the registry. I do think that doing it separately on top of the registry could have severe performance issues with the JPA ticket registry for example because that will generate TONS of queries, 1 per each transaction!

**Comment by mmoayyed** [comment]
You are also correct that an ST always requires a TGT. Even if the ST is present in the cache, so long as the TGT is gone/expired, from the CAS perspective all its STs are considered invalid.

**Comment by mduszyk** [comment]
I did changes as we discussed here. Could you review?

Here are changesets:
https://github.com/Jasig/cas/commit/f9579b4b14a2dcf1625ef2898dad3f87f91e944b
https://github.com/Jasig/cas/commit/7d270eb841fdf952d2087ea155600eb361fba4ab

**Comment by mmoayyed** [comment]
Sure. Initial review is very promising. Thank you very much. Could I ask you to do a pull request please? That will help me get an idea of everything that is modified?

**Comment by mduszyk** [comment]
Pull request created:
https://github.com/Jasig/cas/pull/1189

Let me know your thoughts.

**Comment by mmoayyed** [comment]
Thanks. I wont be able to do anything serious with the PR before Friday, but I appreciate your effort.
