### ISSUE TITLE
status/config - "missing ) after argument list"

### ISSUE THREAD

**Issue by rkorn86** [Jasig/cas#1187]
When trying to open the `status/config` page i get the above error from config.js line 82 `var objects = $.parseJSON('....');`
What i can see, is a `'` in my config which breaks javascript and throws above error.
I use the following sql statement in deployerConfigContext.xml for `org.jasig.services.persondir.support.jdbc.MultiRowJdbcPersonAttributeDao`:
```
select 'SECTIONS' AS ATTR_NAME, IDM.VW_RZINTERN_SECTIONS.SECTION AS ATTR_VALUE
							from IDM.VW_RZINTERN_PERSONS 
							join IDM.VW_RZINTERN_SECTIONS_PERSONS ON IDM.VW_RZINTERN_SECTIONS_PERSONS.PERSONID = IDM.VW_RZINTERN_PERSONS.PERSONID
							join IDM.VW_RZINTERN_SECTIONS ON IDM.VW_RZINTERN_SECTIONS.SECTIONID =  IDM.VW_RZINTERN_SECTIONS_PERSONS.SECTIONID 
              				WHERE IDM.VW_RZINTERN_SECTIONS_PERSONS.ISDEFAULT = 0 AND {0}
```

**Comment by mmoayyed** [comment]
Thanks for the report. We are working on organizing the config screen much better, and make things happen in more RESTish way. Should have an update for this soon.

**Comment by mmoayyed** [comment]
We are planning to remove the runtime config from the report for now, and only focus on properties. The runtime config can be added later via something like Spring boot.
