### ISSUE TITLE
Break up monolithic modules to feature-based modules

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1192]
in order to automate feature config via drop-in modules and plug-n-play, we need to break down modules by feature so that explicit inclusion of a module in the overlay could imply the need for the feature. right now some modules have features bundled in the same module which makes it difficult to automate the config without knowing which feature is actually used.

**Comment by mmoayyed** [comment]
Will start with the JPA module to break it into two modules: one for ticket registry and one for service registry. Will do the same to the LDAP module. I think we'll keep this issue open as a parent issue for all modules that could be broken down. @leleuj makes sense?

**Comment by leleuj** [comment]
At a theoretical level, it makes sense, I'm just worrying about having too many modules and an increased build time.

**Comment by mmoayyed** [comment]
I doubt it would affect build time. If anything, the compiler would be running against the same number of classes, split across various modules. Maybe the time it takes to bootstrap the build increases, don't know. I'll investigate.

**Comment by mmoayyed** [comment]
Before:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.552 s
[INFO] Finished at: 2015-10-13T06:51:03-06:00
[INFO] Final Memory: 63M/647M
```

After:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apereo CAS JDBC Support ............................ SUCCESS [  7.082 s]
[INFO] Apereo CAS JPA Ticket Registry Support ............. SUCCESS [  8.766 s]
[INFO] Apereo CAS JPA Service Registry Support ............ SUCCESS [  5.056 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.292 s
[INFO] Finished at: 2015-10-13T06:49:25-06:00
[INFO] Final Memory: 63M/744M
```

So bootstrapping time adds a few more seconds to the build, but I think this is pretty negligent.

**Comment by mmoayyed** [comment]
Just for reference, a full CAS build takes about 21 minutes. This is inclusive of all checks, except javadocs.

**Comment by mmoayyed** [comment]
One advantage of this approach is that now, configuration of every module can be automated very easily. Before, we had both JPA service and ticket registries in the same module which made it very difficult to determine which one was actually used at runtime. Now, simply the inclusion of module should indicate that it's ready, so we don't have to do any fancy logic to determine whether the feature is used.

**Comment by leleuj** [comment]
Yes, this is fairly negligent till we do the release ;-)

**Comment by mmoayyed** [comment]
True :) 

At some point, we ought to think about automating that too somehow. Much like Travis and the build, it would be ideal if we could just press a button somewhere and it deployed everything so we wouldnt have to worry about time and perf.

**Comment by mmoayyed** [comment]
Moving onto SAML.

**Comment by mmoayyed** [comment]
@leleuj shall we also break up the core module?

**Comment by mmoayyed** [comment]
My vote is that we should break down the core module to:

1. core services
2. core tickets
3. core authentication
4. core audit
5. core logout
6. core monitor
7. core web
8. core protocol (validation)

Leave everything else be. 

This will make it tremendously easier to implement something like MFA., because an MFA module for instance can only pull what's needed (it does not need monitoring or logout components)

**Comment by mmoayyed** [comment]
I am also sort of treating these proposed modules as sub systems and features of the CAS server rather than impls. The more we do this kind of thing, the better we can move towards something like http://start.spring.io/ for CAS overlay.

**Comment by leleuj** [comment]
Wow! It's a tough split you propose, I'm so used to have all stuffs in the core. Though, the components you list makes sense.

Go ahead.

**Comment by mmoayyed** [comment]
Almost done here. Testing...

**Comment by mmoayyed** [comment]
Full mvn clean install without tests:

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:47 min
[INFO] Finished at: 2015-10-29T17:31:38-07:00
[INFO] Final Memory: 118M/247M
[INFO] ------------------------------------------------------------------------
```

**Comment by mmoayyed** [comment]
Startup time less than 30 seconds.
