### ISSUE TITLE
Add properties map to registered services

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1204]
Having had several conversations with people at the Technology Exchange conference, one feature that was very muched requested was the ability to add arbitrary attributes to a registered service. These attributes are basically considered extra metadata about the service that indicate things like contact phone number, email, etc or extra attributes that are used by extensions for custom functionality. I imagine this basically would be a properties map of type `Map<String, String>` that is stuffed into every service and allows adopters to customize and add values to each service as they need.

**Comment by dima767** [comment]
This needs to be Map<String, Object> to support all kinds of "rich" metadata. See cas-addons "extraAttributes" property.

**Comment by dima767** [comment]
Last comment did not come out properly. A Map of String, Object - that's what it should be

**Comment by mmoayyed** [comment]
Need to be careful about the Object part since it needs to be serializable. Cant be any arbitrary object.

**Comment by mmoayyed** [comment]
Cool, thanks. That makes perfect sense. I think we can live with collections.
