### ISSUE TITLE
Remove duplicate component scans from module definitions

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1211]
A number of modules in the Spring context happen to scan the context, while this is automatically done via the CAS webapp. Remove the duplicate scans.

**Comment by leleuj** [comment]
Yes, I realized there are many component scans even in the same module. So I assume I don't any component scan in a submodule as it's done in the CAS webapp.

**Comment by mmoayyed** [comment]
Must be done after #1192 closes.
