### ISSUE TITLE
Dockerize CAS

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1215]
Via https://docs.docker.com/docker-hub/builds/

CAS server already contains config for Jetty. The idea would be to:

1. Have docker download the cas overlay from a repo
2. Configure it, and allow for a structure such that the overlay can be customized
3. Ensure Java, JCE, and everything else is configured correctly.
4. Run the application, and auto build the image to docker hub. 

The changes could possibly go into a docker branch in the repo so that the hub can auto checkout and build it.

**Comment by leleuj** [comment]
Yes

**Comment by mmoayyed** [comment]
http://blog.docker.com/2015/11/upgraded-autobuild-docker-hub/?mkt_tok=3RkMMJWWfF9wsRonuqTMZKXonjHpfsX57uQoXKOwlMI%2F0ER3fOvrPUfGjI4ARMZqI%2BSLDwEYGJlv6SgFQ7LMMaZq1rgMXBk%3D

**Comment by mmoayyed** [comment]
https://hub.docker.com/r/apereo/cas/
