### ISSUE TITLE
Logback-Classic is pulled into the build

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1216]
@leleuj See https://travis-ci.org/Jasig/Jasig/cas/builds/85323784

Any ideas on where and how logback is pulled in? could it be pac4j?

**Comment by leleuj** [comment]
It might be, but there is no direct dependency yet to pac4j... I will take a look if Travis is nice enough to display anything on my browser...

**Comment by mmoayyed** [comment]
Thanks. You may need to experiment with the build process and remove the -q option to see what's causing this fail. Not a big deal, except that we can't generate javadocs for 4.1.x at this point because of this issue. Somewhere in the process, the build broke. :(

**Comment by mmoayyed** [comment]
Seems like this was a possible travis issue. So going to close this issue until it creeps up again.

**Comment by leleuj** [comment]
In any case, I will check logging dependencies on pac4j: https://github.com/pac4j/pac4j/issues/317
