### ISSUE TITLE
Replace Spring Security by spring-webmvc-pac4j

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1222]

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1232

This pull request is currently a work in progress, which works but should not be merged. It requires new improvments tracked for pac4j v1.8.1: https://github.com/pac4j/pac4j/issues/323, https://github.com/pac4j/pac4j/issues/324

**Comment by mmoayyed** [comment]
@leleuj Is this pull complete?

**Comment by mmoayyed** [comment]
Looks like this is the last actual issue for 4.2, right?

**Comment by leleuj** [comment]
Not yet, I'm still working on it. And pac4j v1.8.1 has not been release yet, it's a little longer that expected (I hope in 2 - 3 weeks).
Feel free to postpone this feature for 4.3 if you want to start cutting RC, even though I had in mind 4.2 will be delayed.

**Comment by mmoayyed** [comment]
We do have a bit of time still. At least  3 weeks. So I'll leave this be. I do have a few other changes in mind as well before cutting the RC so lets keep if open and see where progress takes us. 

If there is something I can do on the pac4j side, lmk.
