### ISSUE TITLE
Add more pac4j clients configurable by properties keys

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1223]
In the `cas-server-support-pac4j` module: highest priority to the SAML client...

**Comment by mmoayyed** [comment]
I vote that we autowire config for the testshib idp automatically. Most if not all deployments will only use one single IdP to interface with, and if we could have placeholders for keys and settings, the rest should be handled by CAS automatically.

**Comment by leleuj** [comment]
OK. Let's go for the SAML 2 client: https://github.com/Jasig/cas/pull/1228
