### ISSUE TITLE
Uptime doesn't work on the statistics page

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1229]
The page displays "NaN" instead of real numbers for the uptime.
![casstats](https://cloud.githubusercontent.com/assets/1038508/10631860/e990b2ca-77e0-11e5-8e11-ece91ef66579.jpg)

**Comment by mmoayyed** [comment]
Reviewing.

**Comment by mindblender** [comment]
Hi,
Is this happening all the time?  Could you possibly send me what the JSON response is for this page?  I want to confirm that the data is being passed thru correctly to the JavaScript method that handles the timer.

Let me know if you need help retrieving the JSON response.

-Jeff

**Comment by leleuj** [comment]
Unfortunately, it always happens for me. To be precise, the uptime in the blue panel has the problem while the uptime in the "Server info" is correct. It's a bit useless to have the same information in both places.
The only JSON request I see is for the threads. What do you want me to look at (in the "Network" panel in Chrome 46)?
