### ISSUE TITLE
HttpOnly / Secure not set when "removing" CAS cookies

### ISSUE THREAD

**Issue by AndrewRichardScully** [Jasig/cas#1230]
While the "HttpOnly" and "Secure" flags are present (if configured) when setting the CAS cookies (e.g. CASTGC and CASPRIVACY), they are not present when the cookie is removed.

This gets flagged up by some penetration testing tools (such as OWASP ZAP) although, since the response cookie value is actually blank, no sensitive data can be disclosed to the client (in the case of HttpOnly) / man-in-the-middle (int the case of Secure).

It would be better to have these flags for removal as well as creation (consistency).

This will likely involve overriding #removeCookie() within `org.jasig.cas.web.support.CookieRetrievingCookieGenerator.`

Link to discussion:
https://groups.google.com/forum/#!topic/jasig-cas-dev/_E1h9ijBpFA

**Comment by mmoayyed** [comment]
Backport to 4.0.x and 4.1.x

**Comment by mmoayyed** [comment]
@AndrewRichardScully next release cycle is tentatively scheduled for Nov 30. If you can submit a patch by then and earlier, it would be great! 

Please submit the patch for master. We'll backport it to the appropriate branches.

**Comment by AndrewRichardScully** [comment]
Looks like this has been sorted on Spring 4.2, please see https://groups.google.com/forum/#!topic/jasig-cas-dev/_E1h9ijBpFA.

Presumably, this devalues fixing the issue within the CAS code base? I was hoping that someone with knowledge of CAS's Spring compatibility could make a recommendation on how to proceed.

**Comment by mmoayyed** [comment]
The next CAS version will be on Spring 4.2 and later. I don't know if we can update 4.0 and 4.1 branches. If you can take the effort to investigate compatibility issues, we could probably incorporate those changes in, as well.
