### ISSUE TITLE
Build CAS via Gradle

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1233]
Based on discussion with @leleuj . Assigned to Jérôme for now. 

>Gradle build https://github.com/Unicon/cas/tree/CAS-1322-GRADLE

Note the last commit date. This needs to be brought up to speed. At the time, I had difficulty finding gradle plugins for some of the tasks we do with CAS, such as NOTICE, LICENSE, CS and FindBugs checking, and there is no way a maven plugin can be used with Gradle. Some of those issues may no longer be relevant now.

If you could port that branch over from Unicon over to Jasig as a separate topic branch, it might be easier for both and all of us to start working on that aspect and see how Gradle can help.

**Comment by dima767** [comment]
For the reference: https://docs.gradle.org/current/userguide/build_init_plugin.html

Also, there might just not be comparable Gradle plugins to that of the current Maven build. Could some of those plugins be re-thought and possible dropped out if that is the case?

**Comment by mmoayyed** [comment]
Definitely. Off the top of my head, we probably want to keep the following:

1. NOTICE
2. LICENSE
3. Checkstyle
4. Findbugs

The rest could easily be replaced or dropped. 

Gotta make sure the release plugin is rock solid.

**Comment by mmoayyed** [comment]
@leleuj I am working on adding the final touches to the build. Things may be unstable for a day or two.

**Comment by mmoayyed** [comment]
Javadocs are auto built and pushed. The only remaining bit is snapshot uploads which I am polishing right now and after that, we should be good. Will fix codeship and heroku thereafter.
