### ISSUE TITLE
Conversation trouble when logout  flow was not ended then a login flow started with the same execution id

### ISSUE THREAD

**Issue by RaphC** [Jasig/cas#1239]
Hi,

I'm facing a issue about cas logout/login flow. I'm using CAS protocol 3 with cas version 4.0.

I got the following error : 

<code>
2015/10/19 10:43:01.007 [http-bio-8082-exec-1351] ERROR c.b.p.c.l.MDCServletFilter - 9a7d418c026b46079ec53dcbd036ed45 - Exception thrown but not catched : Request processing failed; nested exception is org.springframework.webflow.definition.registry.NoSuchFlowDefinitionException: No flow definition 'logout' found org.springframework.webflow.definition.registry.NoSuchFlowDefinitionException: No flow definition 'logout' found
        at org.springframework.webflow.definition.registry.FlowDefinitionRegistryImpl.getFlowDefinitionHolder(FlowDefinitionRegistryImpl.java:126) ~[spring-webflow-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.webflow.definition.registry.FlowDefinitionRegistryImpl.getFlowDefinition(FlowDefinitionRegistryImpl.java:61) ~[spring-webflow-2.3.2.RELEASE.jar:2.3.2.RELEASE]
Wrapped by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.webflow.definition.registry.NoSuchFlowDefinitionException: No flow definition 'logout' found
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:948) ~[spring-webmvc-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:838) ~[spring-webmvc-3.2.6.RELEASE.jar:3.2.6.RELEASE]
</code>

I can reproduce the bug with the following 

I post my authentication form /cas/login. All is OK. I take the jsessionid
Then I post /cas/logout?service=XXXXX with the same jessionid. The logout-webflow was triggered The conversation with key e1s1 was started and stop at the logoutView state (so the conversation is not ended). The session is not destroyed.

<pre><code>
2015/10/25 07:29:08.077 [http-apr-8080-exec-3] DEBUG o.s.w.e.ViewState - 4763a78ecfcf408a89802d9b360b2254 - Entering state 'logoutView' of flow 'logout' 

2015/10/25 07:29:08.077 [http-apr-8080-exec-3] DEBUG o.s.w.c.i.SessionBindingConversationManager - 4763a78ecfcf408a89802d9b360b2254 - Putting conversation attribute 'name' with value logout 
2015/10/25 07:29:08.077 [http-apr-8080-exec-3] DEBUG o.s.w.c.i.SessionBindingConversationManager - 4763a78ecfcf408a89802d9b360b2254 - Putting conversation attribute 'caption' with value null 
2015/10/25 07:29:08.077 [http-apr-8080-exec-3] DEBUG o.s.w.c.i.SessionBindingConversationManager - 4763a78ecfcf408a89802d9b360b2254 - Putting conversation attribute 'description' with value null 
2015/10/25 07:29:08.077 [http-apr-8080-exec-3] DEBUG o.s.w.c.i.SessionBindingConversationManager - 4763a78ecfcf408a89802d9b360b2254 - Putting conversation attribute 'flowExecutionSnapshotGroup' with value org.springframework.webflow.execution.repository.impl.SimpleFlowExecutionSnapshotGroup@3fe47a6e 
2015/10/25 07:29:08.077 [http-apr-8080-exec-3] DEBUG o.s.w.e.i.FlowExecutionImpl - 4763a78ecfcf408a89802d9b360b2254 - Assigned key e1s1 
</code></pre>

If I try to post a /cas/login with the same session and the execution parameter set to e1s1. I got the previous error.

<pre><code>
2015/10/25 07:30:44.628 [http-apr-8080-exec-8] DEBUG o.s.w.s.DispatcherServlet - b9980e160d044742b4b60f88cd22a675 - Last-Modified value for [/cas/login] is: -1 
2015/10/25 07:30:44.628 [http-apr-8080-exec-8] DEBUG o.s.w.e.FlowExecutorImpl - b9980e160d044742b4b60f88cd22a675 - Resuming flow execution with key 'e1s1 
2015/10/25 07:30:44.628 [http-apr-8080-exec-8] DEBUG o.s.w.c.i.SessionBindingConversationManager - b9980e160d044742b4b60f88cd22a675 - Locking conversation 1 
2015/10/25 07:30:44.628 [http-apr-8080-exec-8] DEBUG o.s.w.e.r.i.DefaultFlowExecutionRepository - b9980e160d044742b4b60f88cd22a675 - Getting flow execution with key 'e1s1' 
2015/10/25 07:30:44.628 [http-apr-8080-exec-8] DEBUG o.s.w.d.r.FlowDefinitionRegistryImpl - b9980e160d044742b4b60f88cd22a675 - Getting FlowDefinition with id 'logout' 
2015/10/25 07:30:44.631 [http-apr-8080-exec-8] DEBUG o.s.w.c.i.SessionBindingConversationManager - b9980e160d044742b4b60f88cd22a675 - Unlocking conversation 1 
</code></pre>

It seems that conversationContainer used for a single session doesn't split login-webflow-conversation and logout-webflow ones.

It would be more safe if conversations are splitted by flow and logout conversations are cleaned up when a login-flow conversation started on the same CAS session.

My workaround is to replace 

````<view-state id="logoutView" view="casLogoutView" /> ````
by 
````<end-state id="logoutView" view="casLogoutView"/>````

**Comment by mmoayyed** [comment]
Could you submit a PR with the fix?

**Comment by RaphC** [comment]
Hi,

I didn't work on a definitive fix yet because it could be some side effects. I'll provide a PR later. I think also, even if it's not the root cause, that the logoutView state is not properly defined and should be an end-state as the conversation is finished when we access to the logoutView.

Don't you want I firstly provide a pull-request with this modification only?

**Comment by mmoayyed** [comment]
yes that would be fine. 

is there a reason you are grabbing the jsessionid ? the behavior your describe is expected.

**Comment by RaphC** [comment]
before I reproduce the issue I executed the logout POST with a chrome extension to test differents cases. Particularly to check if It was bound to a non thread-safe session issue.

**Comment by mmoayyed** [comment]
Cool. Look fwd to your PR.
