### ISSUE TITLE
Regex validation in cas-management UI always fails.

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1247]
The JavaScript validation of the regex in "Proxy Policy Options" always fails if non-empty. A pull-request with a fix will be added shortly.

https://github.com/Jasig/cas/pull/1246

reported by @fjollberg

**Comment by fjollberg** [comment]
Is it possible to get this into 4.1.2 as well?

**Comment by robertoschwald** [comment]
Yes, 4.1.2 would be great or a 4.2.0 release asap. I'm currently migrating some CAS projects from 3.x, but needed to postpone several times to wait for fixed versions of CAS as some former issues hit us as well.

**Comment by mmoayyed** [comment]
I'll check. If it's not there we can definitely backport it. 

As for releases, we can't do a 4.2 yet because we would need at least a month of RC time. But 4.1.2 and 4.0.7 should be out towards the end of next week as we do patch releases every month. Check out the milestones for the exact date.

**Comment by robertoschwald** [comment]
Great Misagh. I'll do that.

**Comment by mmoayyed** [comment]
As far as I can tell, this change is patched in 4.1.x:
https://github.com/Jasig/cas/commit/369e96212cd0cbf45fc0dcaca29ce41f4a6504eb

and will be available in 4.1.2 in a week or so.
