### ISSUE TITLE
Automate pac4j client config

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1250]
Clients need to be explicitly configured:
http://jasig.github.io/cas/development/integration/Delegate-Authentication.html

Lets auto detect clients based on properties and register them automatically, or update the docs.

**Comment by mmoayyed** [comment]
Looks like some of this is one. We just need to update the docs better. Add a CASClient  as well, and ensure UI can update itself dynamically if links are available to providers.

**Comment by leleuj** [comment]
Indeed, in case you define your Facebook, Twitter or SAML clients via properties, the `clients` bean is not necessary, the `Clients` object is automatically created.

So if we want to avoid manually creating a `Clients` object in the Spring context, it means we need to scan all beans in the context to find those which are clients (which implements the `IndirectClient` interface): are we in line?

OK to add a `CasClient` via properties and upgrade the UI automatically (I'll use images for the buttons).

**Comment by mmoayyed** [comment]
>So if we want to avoid manually creating a Clients object in the Spring context, it means we need to scan all beans in the context to find those which are clients (which implements the IndirectClient interface): are we in line?

Yes, ask the context for beans of all type X, and keep adding them to the collection. We should try to minimize the steps required down as much as possible.

Thanks for taking this one.

**Comment by mmoayyed** [comment]
End goal (not for the next release) would be to collect as many properties as possible, so that we can then try to decide how to manage them. Spring Cloud does present a few options that are very suitable to what we need. Maybe something to work on for the next release.

**Comment by mmoayyed** [comment]
@leleuj any progress on this?

**Comment by leleuj** [comment]
Not yet, pushing that issue on top of my TODO list, will work on it tomorrow.

**Comment by leleuj** [comment]
I restarted working on that. I'm also working on pac4j integration into Knox (security gateway for Hadoop) and it requires the same capability of creating clients based on properties so it leads me to create a new issue and PR for pac4j: https://github.com/pac4j/pac4j/issues/357

After its merge, I'll finish this one.

**Comment by leleuj** [comment]
Added the OpenID Connect client also (requested on Knox side) -> see: https://github.com/leleuj/pac4j/commit/6b1bb1a5d4892c3da936499649ad7650acdbbacf

**Comment by mmoayyed** [comment]
Great! Thanks for the update.

**Comment by leleuj** [comment]
Here is the PR: https://github.com/Jasig/cas/pull/1290
