### ISSUE TITLE
Auto-configure webflow changes for modules

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1255]
Presently, most modules attempt to auto-configure themselves via dynamic spring context inspection. There are a few modules that additionally require SWF changes, and these are now required to be done manually by the adopter. Examine the changeset and determine whether it's possible to auto-configure the webflow changes as well. 

An example would be CAS-MFA, where MFA modules such as Duo attempt to auto configure the flow to MFA functionality.

**Comment by leleuj** [comment]
That would be really helpful.

**Comment by mmoayyed** [comment]
Punting to 4.3 as it can better be done with MFA changes, etc with more time.

**Comment by mmoayyed** [comment]
One approach would be to create a new module that hosts an abstraction on top of the webflow with a dependency to spring webflow. Then we could create individual modules for each cas feature to inherit from that abstraction and auto register the webflow changes. This has the advantage that the webflow module can be independently and optionally deployed, should the cas deployer not want to automate the webflow changes in order to customize the behavior. It is important that this behavior remains optional for full extensibility and control, but perhaps, on by default.
