### ISSUE TITLE
CAS4 Logout Unsuccessfull

### ISSUE THREAD

**Issue by zxlaole** [Jasig/cas#1257]
Environment:
CAS-Sever-4.1.1 used http requireSecure="false
CAS-Client-3.4.1 
I use sourcecode compiled.
When my webapp use http is all right,could successfull login and logout.
But when my webapp with https,cas-server remain http,i can login successfull,but logout unsuccessfull,after logout show me has logined until closed the browser.I watched the log file,but dont has any helpful infomations.
Please answer me,thanks.

**Comment by leleuj** [comment]
Please use the mailing list to ask a question: http://jasig.github.io/cas/Mailing-Lists.html
