### ISSUE TITLE
Memcached-Repcached  TGT replication issue

### ISSUE THREAD

**Issue by sramli** [Jasig/cas#1260]
Hello ,

I'm running into a new issue with HA jasig Cas configuration :

CAS 4.0.6
memecached : 1.4.13
repcached : 2.3.1

I have 2 memcached instances with repcached installation , when I test the replication using telnet command line it looks like good in 2 directions , but when I try to make everything up by connecting me to my CAS server , it creates and add TGT ticket into one server succesfully , BUT the replication to the other server is not performed !!!

I still retrieve my TGT ticket in one server and I can't in the other one.

Any help pleaze , I m blocked !

Thx for advance.

**Comment by mmoayyed** [comment]
You want to subscribe and post these questions to the CAS mailing lists. This area is reserved for actual issues.
