### ISSUE TITLE
PrincipalAttributeRegisteredServiceUsernameProvider  ignores attribute release

### ISSUE THREAD

**Issue by iigorr** [Jasig/cas#1261]
Currently the `PrincipalAttributeRegisteredServiceUsernameProvider` completely ignores attribute release. When using it with `CachingPrincipalAttributesRepository` or a custom dynamic principal attribute repository, the behaviour is a bit odd as the resolved attributes are fetched, but the userNameProvider fails to find them as it only considers the (static) principal attributes.

I think it should be possible to pass an optional `PrincipalAttributesRepository` to `PrincipalAttributeRegisteredServiceUsernameProvider`

**Comment by mmoayyed** [comment]
Good find. Thanks for the report.

**Comment by mmoayyed** [comment]
Could you also share with us your CachingPrincipalAttributesRepository config?

**Comment by mmoayyed** [comment]
and what CAS version you are actually using?

**Comment by iigorr** [comment]
CAS version is 4.1.0.

```
<bean class="org.myorg.service.ExtendedRegexRegisteredService"
  p:id="0"
  p:name="Example"
  p:description="Example Description"
  p:serviceId="^https://localhost/.*$"
  p:evaluationOrder="10000001" >
    <property name="usernameAttributeProvider">
        <bean class="org.jasig.cas.services.PrincipalAttributeRegisteredServiceUsernameProvider" 
          c:usernameAttribute="myAppId" />
    </property>
    <property name="attributeReleasePolicy">
        <bean class="org.jasig.cas.services.ReturnAllowedAttributeReleasePolicy">
            <property name="allowedAttributes">
                <list>
                    <value>myAppId</value>
                </list>
            </property>
          <property name="principalAttributesRepository" ref="principalAttributesRepository" />
        </bean>
    </property>
</bean>

```

**Comment by mmoayyed** [comment]
Thanks. What is the function of ExtendedRegexRegisteredService? How is it extended?

**Comment by iigorr** [comment]
It is used to distinguish services coming from our Shibboleth. It does nothing fancy, just checks for the entityId parameter if present. Otherwise (like in this case) it works just the same as the RegexRegisteredService.

**Comment by mmoayyed** [comment]
Thanks. Checks the entityID parameter to see if the SP is authorized? or to decorate the login page? I think we have added support for both cases in master right now, so you may want to take advantage of that code.

**Comment by mmoayyed** [comment]
Got a PR coming up on this issue before we cut the final patch.
