### ISSUE TITLE
SAML2 skewAllowance setting

### ISSUE THREAD

**Issue by agaikwad** [Jasig/cas#1266]
Hello,
Currently in master (4.1.1) and SAML2/Google SSO we get error “Google Apps - This service cannot be accessed because your login credentials have expired. Please log in and try again.” (Have confirmed NTP is working correctly)

Looking at the saml response “NotOnOrAfter="2015-11-09T09:59:14.000Z"” is set to the current time. Which if I understand correctly means by the time it makes it to google a second has passed and the credentials have expired.

In our CAS 3.5.x deployment looking at the saml response “NotOnOrAfter="2016-11-09T10:03:00Z"” the date is set to 1 year ahead so the credentials don’t expire by the time it makes it to google’s servers.

Per Misagh a skewAllowance setting is missing from SAML2, hence creating an issue.

code:
4.1.x: https://github.com/Jasig/cas/blob/master/cas-server-support-saml-googleapps/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceResponseBuilder.java#L97

3.5.x: https://github.com/Jasig/cas/blob/3.5.x/cas-server-core/src/main/java/org/jasig/cas/authentication/principal/GoogleAccountsService.java#L178

**Comment by mmoayyed** [comment]
Just a correction: your 4.1 link above actually points to master and not 4.1. You want to look at the 4.1 branch.

**Comment by agaikwad** [comment]
Noted. This is probably the correct 4.1.x link:
https://github.com/Jasig/cas/blob/4.1.x/cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsService.java#L169
