### ISSUE TITLE
Cannot build, since upgrade to gradle - Dependency conflict on :cas-server-support-pac4j:compile

### ISSUE THREAD

**Issue by rkorn86** [Jasig/cas#1270]
Invoking gradle from my Jenkins via `GRADLE_USER_HOME=. ./gradlew assemble --parallel -q -DskipJavadocs=true` brings the following error.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cas-server-support-pac4j:compileAspect'.
> Could not resolve all dependencies for configuration ':cas-server-support-pac4j:compile'.
   > A conflict was found between the following modules:
      - org.slf4j:jcl-over-slf4j:1.7.12
      - org.slf4j:jcl-over-slf4j:1.7.5

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Im a newbie on gradle, so I hope the error is not on my side, even if your travis ci is building fine.
As additional info: Im using artifactory plugin in my jenkins setup for resolving and deploying artifacts.

**Comment by mmoayyed** [comment]
If Travis can build it, it works!

**Comment by mmoayyed** [comment]
You can try with `-DskipVersionConflict=true`

**Comment by rkorn86** [comment]
Thx, your workaround helped. I wonder why I do not see this flag on travis.

**Comment by mmoayyed** [comment]
Because Travis runs fine, and we should never able this flag. This is an issue specific to you.
