### ISSUE TITLE
Question about TGT destruction

### ISSUE THREAD

**Issue by RaphC** [Jasig/cas#1287]
Hi,

It seems that when we destroy a TGT we never destroy the foolowing ST which could be linked to ? Am I wrong ?

**Comment by mmoayyed** [comment]
Yes you are wrong. STs are destroyed along with TGTs.

**Comment by RaphC** [comment]
I don't see the ST destruction in the code. Can you show me ?

If a take the TerminateSessionAction of the  logout-weblow which is described like this 'Terminates the CAS SSO session by destroying the TGT (if any) and removing cookies related to the SSO session.', I can see that the TGT and  the session are destroyed but I don't see the corresponding ST if they exists.

<code>
this.centralAuthenticationService.destroyTicketGrantingTicket(tgtId)
this.ticketGrantingTicketCookieGenerator.removeCookie(response);
this.warnCookieGenerator.removeCookie(response);
</code>

Where does it processed ?

Thks

**Comment by mmoayyed** [comment]
When the TGT is destroyed it is removed from the registry. At that time all associated STs are destroyed and removed too. STs are also removed from the registry automatically when they expire. 

I don't know what CAS version u r on. Yours may not do this yet. 

Please use the mailing list for additional questions.

**Comment by RaphC** [comment]
OK, thanks for your response. I'll look at the version which implements this

**Comment by mmoayyed** [comment]
Here is how the default ticket registry does it for example:
https://github.com/Jasig/cas/blob/master/cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/DefaultTicketRegistry.java#L130

**Comment by RaphC** [comment]
Thanks for the details
