### ISSUE TITLE
CAS Management WebApp Jar not published anymore

### ISSUE THREAD

**Issue by rkorn86** [Jasig/cas#1292]
cas-management-webapp-4.2.0-20151118.165332-86.jar was the last JAR, which was published on https://oss.sonatype.org/content/repositories/snapshots/org/jasig/cas/cas-management-webapp/4.2.0-SNAPSHOT/  
I guess the reason is, that the jar is not getting signed and therefore not uploaded.
If you dont wish to publish the classes of the Management WebApp anyway, just ignore this issue (and I have to find a way, how to convince my jenkins, not to treat my missing locally signed jar as an error).

**Comment by mmoayyed** [comment]
Yes we dont. That was a fluke that happened while migrating to gradle. If you need those classes outside the war let us know and we can break it down.
