### ISSUE TITLE
Documentation: JSON Service Management needs a note about escaping regular expressions

### ISSUE THREAD

**Issue by BradGunnerSGT** [Jasig/cas#1305]
The JSON importer strips out the backslash `\` escape character from regular expressions. 

Please add a note to the documentation page for the the JSON Service Manager to let deployers know that they will need to "double-escape" and change their serviceID entries from: 

    "serviceId": "^https?://server\.domain\.edu(:\d+)?/",

to:

    "serviceId": "^https?://server\\.domain\\.edu(:\\d+)?/",

Without this extra escape character, the JSON parser throws an error since "\." and "\d" are not valid JSON escape sequences.

**Comment by mmoayyed** [comment]
Sure
