### ISSUE TITLE
Decouple authentication from CASImpl's TGTs

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1315]
Presently, in order to issue a TGT CASImpl expects credentials to authenticate first. This approach does not work when multiple flows are involved in the case of MFA where at the end of every flow, credentials need to be authenticated and at the end of the overall flow, TGT is granted. The API needs to be modified to allow this behavior where rather than credentials, an authentication context is passed to CASImpl.

**Comment by mmoayyed** [comment]
Almost done. Here are a few summaries:

1. The orchestration of authentication events is now overseen by `AuthenticationSupervisor`. This component will keep collecting authentication events and delegates them to the authentication manager.

2. Once asked, the `AuthenticationSupervisor` will attempt to build a finalized authentication context. It will look into the collection of authentication events, and will construct the final Authentication object that is a composite of all authentications and principals. Attributes are merged and handled.

3. The final result that is the context is passed to CASImpl.

**Comment by alexkolson** [comment]
This is awesome!! :+1:
