### ISSUE TITLE
Missing namespace in Service-Management.md for JPA

### ISSUE THREAD

**Issue by robertoschwald** [Jasig/cas#1319]
xmlns:util="http://www.springframework.org/schema/util" is missing. Will provide a PR.

**Comment by mmoayyed** [comment]
Thanks.

**Comment by mmoayyed** [comment]
Were you able to get the JPA ticket registry working?

**Comment by robertoschwald** [comment]
No, not yet, but I'm on the way...

**Comment by robertoschwald** [comment]
Tower Git client for OSX always selects the jasig origin repo as the default when publishing a branch, so It always chooses the jasig original repo. Deleted it from jasig and published into mine, based on 4.1.x branch (first one was based on tag 4.1.2, which doesn't work).
