### ISSUE TITLE
SAML2 Google Apps skewAllowance setting

### ISSUE THREAD

**Issue by agaikwad** [Jasig/cas#1322]
This is related to the closed issue #1266
I still get the your credentials have expired. I believe it may be because the skew value is not being applied to all the dates. In CAS 3.5.1 which I have in production all NotOnOrAfter values seem to be getting skewed by a year ahead. In the below log only one of two values are getting skewed.
```xml
<samlp:Status>
<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
</samlp:Status>
<Assertion ID="<<skdjfskjsdfslkjlksjdlfjskd>>" IssueInstant="2003-04-17T00:46:02.000Z" Version="2.0">
<Issuer>https://www.opensaml.org/IDP</Issuer>
<Subject>
<NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"><<personDetails>></NameID>
<SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
<SubjectConfirmationData InResponseTo="<<somerandomstringlksjdlfkjsflksdjflks>>" NotOnOrAfter="2015-11-24T15:39:00.000Z" Recipient="https://www.google.com/a/<<mydomain>>/acs"/>
</SubjectConfirmation>
</Subject>
<Conditions NotBefore="2003-04-17T00:46:02.000Z" NotOnOrAfter="2015-11-24T15:41:00.000Z">
<AudienceRestriction>
<Audience>https://www.google.com/a/<<mydomain>>/acs</Audience>
</AudienceRestriction>
</Conditions>
<AuthnStatement AuthnInstant="2015-11-24T15:39:00.000Z">
<AuthnContext>
<AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</AuthnContextClassRef>
</AuthnContext>
</AuthnStatement>
</Assertion>
</samlp:Response>
```

Thanks for your help.

**Comment by mmoayyed** [comment]
Which value is not skewed?

**Comment by agaikwad** [comment]
The current time when I ran this was: 2015-11-24T15:39:00.000Z
```xml
<SubjectConfirmationData InResponseTo="<<somerandomstringlksjdlfkjsflksdjflks>>" NotOnOrAfter="2015-11-24T15:39:00.000Z"
```
From what I can tell the above line is not skewed during my attempt while the below one is
```xml
<Conditions NotBefore="2003-04-17T00:46:02.000Z" NotOnOrAfter="2015-11-24T15:41:00.000Z">
```
There are only two differences I noticed between my production and CAS4.1
1. Not all NotOnOrAfter values were skewed in CAS4.1
2. The date format is different CAS 3.5.1 has 2015-01-17T00:46:02Z while CAS 4.1 has 2015-11-24T15:39:00.000Z (That is has the extra .000Z).

**Comment by mmoayyed** [comment]
What does your configuration look like for the saml argument extractor?

**Comment by mmoayyed** [comment]
Yes it looks like that is not skewed. Are you able to make the adjustments to the code and submit a PR?
Also are you sure that is ACTUALLY the root cause of the issue? Can you test the fix by modifying the code?

**Comment by agaikwad** [comment]
This is what my argumentextractor looks like
```
<bean id="samlArgumentExtractor" class="org.jasig.cas.support.saml.web.support.SamlArgumentExtractor" />    

    <bean id="casArgumentExtractor" class="org.jasig.cas.web.support.CasArgumentExtractor"/>

    <util:list id="argumentExtractors">
        <ref bean="samlArgumentExtractor" /> 
        <ref bean="casArgumentExtractor"/>
        <ref bean="googleAccountsArgumentExtractor" />
    </util:list>
    
    <bean id="googleAccountsArgumentExtractor" 
          class="org.jasig.cas.support.saml.web.support.GoogleAccountsArgumentExtractor"
          p:skewAllowance="${cas.saml.response.skewAllowance:0}"
          c:privateKey-ref="privateKeyFactoryBean"
          c:publicKey-ref="publicKeyFactoryBean" />

    <bean id="privateKeyFactoryBean" class="org.jasig.cas.util.PrivateKeyFactoryBean"
      p:location="classpath:private.p8"
      p:algorithm="RSA" />

    <bean id="publicKeyFactoryBean"	class="org.jasig.cas.util.PublicKeyFactoryBean"
      p:location="classpath:public.key"
      p:algorithm="RSA" />
```

Unfortunately no, I am not sure that is the issue. Like I said those were the only two differences I saw between production and test.

I am using your maven repository to pull down the cas-server-support-saml as a dependency. Can you tell me how I can edit that code instead to test if the change works? If you could point me in the right direction please...

**Comment by mmoayyed** [comment]
Are you actually specifying a skew?

```
 p:skewAllowance="${cas.saml.response.skewAllowance:0}"
```

This will default to 0 if you have not specified that property.

**Comment by mmoayyed** [comment]
You will need to make sure this line is using skewed time:

https://github.com/Jasig/cas/blob/4.1.x/cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsService.java#L195

Like the one above it. Compile, rebuild and test.

**Comment by mmoayyed** [comment]
If you are doing this via a maven overlay, you need to copy that file into your overlay at that exact path and then:

http://jasig.github.io/cas/4.1.x/installation/Maven-Overlay-Installation.html

Read "Custom and Third-Party Source"

**Comment by agaikwad** [comment]
Yes I am using a skew value (-120). It is adding two minutes to one of the NotOnOrAfter dates. I am looking at overlaying with custom source to over the saml library. I will let you know if it solves it.

**Comment by mmoayyed** [comment]
Thanks.

**Comment by mmoayyed** [comment]
Your skew value must be positive. Not negative.

**Comment by mmoayyed** [comment]
In fact, you made the assertion has expired by moving the expiration time 2 minutes ahead!

**Comment by mmoayyed** [comment]
Never mind, I am wrong.

**Comment by mmoayyed** [comment]
So this is a bug actually. You should use a negative value, but this will be changed in later versions to actually add to the datetime, and not subtract.
