### ISSUE TITLE
Update Commons Collection (332 or 41)

### ISSUE THREAD

**Issue by philippberger** [Jasig/cas#1331]
Update Commons Collection (332 or 41) due to https://blogs.apache.org/foundation/entry/apache_commons_statement_to_widespread

This should be done for all versions!

**Comment by mmoayyed** [comment]
- CAS does not use collections in a way that would allow one to produce or cause this issue.
- CAS 4.2 no longer uses collections.
- Spring libraries have all been updated for 4.1.x and 4.0.x to mitigate the possibility of this attack and are released.
- Thus, an upgrade would be nice but not an issue as far as we know. 

If you'd like to submit a PR to handle this, that would be most welcome.

**Comment by mmoayyed** [comment]
Closing for now, as this issue does not affect CAS.
