### ISSUE TITLE
integrate mongo  error

### ISSUE THREAD

**Issue by yahuvi** [Jasig/cas#1337]
When I integrate cas-server-integration-mongo module to cas-server-webapp  and cas-management-webapp,configuration file is ok and deploye the two project to tomcat,run tomcat,The error log as follows：
“Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jasig.cas.services.RegisteredService]: Specified class is an interface”，

When the cas-management-webapp's OAuthServletContextListener initializeServletApplicationContext ->addRegisteredServiceToServicesManager,MongoServiceRegistryDao add OAuthCallbackAuthorizeService is well,but  MongoServiceRegistryDao  find OAuthCallbackAuthorizeService has the above problem .

**Comment by mmoayyed** [comment]
Post logs and your configuration please.

**Comment by mmoayyed** [comment]
Also, we need to know where that error comes from: cas webapp or the management webapp?

**Comment by mmoayyed** [comment]
I ran test cases against mongolab, and could not duplicate the problem. Need more logs/config before we can diagnose.

**Comment by yahuvi** [comment]
The problem is config file——cas webapp's pom.xml ,I forget config dependency project.

**Comment by mmoayyed** [comment]
Cool. Thanks for reporting back.

**Comment by MoriTanosuke** [comment]
@yahuvi It's late, but do you still know which dependency you had to add to fix this?
