### ISSUE TITLE
Anonymous Username Attribute Provider in Services Management tool doesn't correctly persist/restore salt

### ISSUE THREAD

**Issue by frett** [Jasig/cas#1339]
When configuring the Anonymous Username Attribute Provider, the salt setting is not being correctly persisted/restored. Every time a user saves the form the salt value is rotated, this will lead to changing usernames for configured services utilizing this provider.

I stumbled across this bug in 4.2 while testing my current extensible Services Management UI work. I haven't checked to see if the problem exists in 4.1, but would assume it does.

**Comment by mmoayyed** [comment]
When was your last pull? Are you certain this exists in the latest commit?

**Comment by frett** [comment]
I noticed it originally in my factory/mapper branch (based off of https://github.com/jasig/cas/commit/adbdff2beb2f401dccb605f76af5e4982f973d29). So, I switched to that commit to eliminate my changes and set the bare minimum config (user added to user-details.properties and changed the cas.host setting) to make the built management war work.

I can test again against the latest master, but didn't see anything in commits that would appear to change that behavior. I also didn't do much debugging to narrow down the issue since it wasn't something I'm dependent on, but figured I would report it for others that may want to utilize that feature.

**Comment by mmoayyed** [comment]
I remember running into a problem with the salt very recently, where it was not properly encoded, or it was but it wasn't saved correctly. If you can do a merge with master in your pull and reconfirm, I can dig into it a bit more. I suspect it's already fixed in both master and 4.1, and should become available in 4.1.3.

**Comment by frett** [comment]
I just built the current master and I'm seeing the problem, tracing through a debugger now to see if I can narrow it down. It actually might be related to persisting/reloading at the ServicesDao layer, my current test is using the JsonServiceRegistryDao.

**Comment by mmoayyed** [comment]
Cool, thanks for confirming. Keep us posted please.

**Comment by frett** [comment]
it is in the `JsonServiceRegistryDao`. Most of the tests aren't actually testing deserializing objects in the JSON registry because they trigger a `save` followed by a `findServiceById`. This execution path keeps the saved `RegisteredService` in the in-memory Map and returns it in `findServiceById`.

adding a `load` call after the `save` at https://github.com/Jasig/cas/blob/master/cas-server-core-services/src/test/java/org/jasig/cas/services/JsonServiceRegistryDaoTests.java#L91 will force a reload of the `RegisteredServices` from disk and break the test.

**Comment by frett** [comment]
What I think is happening is that Jackson is serializing the salt as a `byte[]`, which is Base64 encoded. it's doing this because there is a `getSalt` method that returns a `byte[]`. 

When it is deserializing the salt it is deserializing it as a `String` because it has to directly write to the `salt` field. Deserializing a String doesn't trigger Base64 decoding.

**Comment by frett** [comment]
some Json annotations appear to fix it, PR incoming.
