### ISSUE TITLE
Unable to obtain ProxyTicket when using JpaTicketRegistry

### ISSUE THREAD

**Issue by frett** [Jasig/cas#1348]
CAS 4.1.0 switched to using the prefix "PGT" for proxy granting tickets, which was separate from "TGT" for ticket granting tickets. This is causing an issue with this logic in the `JpaTicketRegistry`: https://github.com/Jasig/cas/blob/master/cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java#L171

This logic tries to intelligently determine requests to get a TGT, but the simple comparison logic will only match TGT or PGT (if configured), but not both.

The quick fix is either to add in a `proxyGrantingTicketPrefix` option that is checked as well, or switch it to a set of possible prefixes (makes it extensible if the need for an additional TGT prefix is needed beyond just TGT & PGT).

**Comment by mmoayyed** [comment]
I like the second option. Likely, you need to account for PTs as well.

**Comment by frett** [comment]
I'll get a patch tossed together shortly

**Comment by mmoayyed** [comment]
Thanks.

**Comment by frett** [comment]
it looks like there might be some missing JPA annotations for PGTs and PTs in 4.2. I'll try and track that down at the same time.

**Comment by mmoayyed** [comment]
Probably, we need to add

```
@Entity
@DiscriminatorValue("pgt")
```

to those classes. Similar to how Oauth is mapped for the JPA service registry.

**Comment by frett** [comment]
yeah, and add `@DiscriminatorColumn("type")` to `TicketGrantingTicketImpl` and `ServiceTicketImpl

**Comment by frett** [comment]
we also need to add a `ProxyGrantingTicketDelegator` and probably a `ProxyTicketDelegator`
