### ISSUE TITLE
Configuring-LongTerm-Authentication documentation error

### ISSUE THREAD

**Issue by antonu17** [Jasig/cas#1351]
Error in http://jasig.github.io/cas/4.1.x/installation/Configuring-LongTerm-Authentication.html
In Webflow Configuration section, viewLoginForm action state code:

```xml
<view-state id="viewLoginForm" view="casLoginView" model="credential">
  <binder>
    <binding property="username" />
    <binding property="password" />
    <binding property="rememberMe" />
  </binder>
  <on-entry>
    <set name="viewScope.commandName" value="'credential'" />
  </on-entry>
  <transition on="submit" bind="true" validate="true" to="realSubmit">
    <evaluate expression="authenticationViaFormAction.doBind(flowRequestContext, flowScope.credential)" />
  </transition>
</view-state>
```

authenticationViaFormAction has no doBind method any more, because as of version 4.1+ (?) it extends org.springframework.webflow.action.FormAction no more. So correct one code is:
```xml
<view-state id="viewLoginForm" view="casLoginView" model="credential">
  <binder>
    <binding property="username" />
    <binding property="password" />
    <binding property="rememberMe" />
  </binder>
  <on-entry>
    <set name="viewScope.commandName" value="'credential'" />
  </on-entry>
  <transition on="submit" bind="true" validate="true" to="realSubmit"/>
</view-state>
```

**Comment by mmoayyed** [comment]
Thanks for the report. Would you be able to submit a patch to fix the docs?

**Comment by antonu17** [comment]
Sorry for my ignorance, but can you show me guide to patch submission? I think i could do it.

**Comment by mmoayyed** [comment]
Thanks. Make sure you are always pushing PRs from a topic branch.

**Comment by mmoayyed** [comment]
Here is the official guide just for reference http://jasig.github.io/cas/developer/Contributor-Guidelines.html
