### ISSUE TITLE
Improve documentation about enabling the OAuth protocol

### ISSUE THREAD

**Issue by edpichler** [Jasig/cas#1352]
Improve documentation about enabling the OAuth protocol.

The section "Add the needed CAS services" is completely wrong. I lost hours solving it. The docs said I need to register a bean with id "serviceRegistryDao" where it would never be created.

Also it's very difficult to someone answer in the mailing lst, there isn't too much discussion there. Anyway, this should be more clear on documentation.

**Comment by mmoayyed** [comment]
Which docs for which version? Could you provide a reference link? 

I'd let @leleuj comment, but I have not had an issue configuring Oauth with CAS. What specific issue did you run into? Which section of the docs should be updated?

**Comment by edpichler** [comment]
http://jasig.github.io/cas/4.1.x/installation/OAuth-OpenId-Authentication.html

Section "Add the needed CAS services" tell how to add the OAuth Registered services. If you follow it strictly, and debug the service manager, you will discover that it will not be registered. The default on the project is to register just services described on JSON files, because in file deployerConfigContext.xml already have a bean with id "serviceRegistryDao".

To get this work, I created JSON files with the services, instead of beans as it is informed on this section. But it's still not working, I'm facing problems with the callback URL, but this is another thing.

**Comment by mmoayyed** [comment]
Yes, that is all correct. What this is trying to teach you is that you need to register services with your services manager. The docs show you how to define those services in beans and xml, while the default actually is going to handle service registration in JSON. So you don't need to redefine your service registry. You just need to create the service in JSON format. So the docs are not wrong; they are just not relevant to the default config :) (which one could argue, that they are nonetheless wrong) 

We have fixed in later versions, but feel free to submit me a patch to fix this.

**Comment by edpichler** [comment]
@mmoayyed Thank you!

**Comment by mmoayyed** [comment]
I updated docs for master.

**Comment by leleuj** [comment]
The main idea is to add a CAS service to define an OAuth client application, it being loaded by JSON or another way (`serviceRegistryDao`).

@mmoayyed : in the current documentation: http://jasig.github.io/cas/4.1.x/protocol/OAuth-Protocol.html, I don't see any reference to this need to create a CAS service for each OAuth client.

**Comment by mmoayyed** [comment]
You want to see http://jasig.github.io/cas/4.1.x/installation/OAuth-OpenId-Authentication.html

**Comment by mmoayyed** [comment]
The page you refer to is a parent page, that describes all the aways OAuth functionality can be handled in CAS.

**Comment by leleuj** [comment]
But if I click on "OAuth protocol" on the right menu ("Integration") from http://jasig.github.io/cas/4.1.x/index.html, I get the page I mentioned: where do I click to get "yours"?

**Comment by mmoayyed** [comment]
On that very same page at the top, you will see the following paragraph:

```
You can configure the CAS server with:

- OAuth client support, which means authentication can be delegated through a link on the login page to a CAS, OpenID or OAuth provider.
- OAuthn server support, which means you will be able to communicate with your CAS server through the OAuth 2.0 protocol, using the Authorization Code grant type.
```

There are links for each bullet point that take you to the appropriate configuration.

**Comment by leleuj** [comment]
Yes, indeed. As I saw: "CAS OAuth Server Support", I thought I was on OAuth server support page. I think we should only have the first paragraph on this parent page...

**Comment by mmoayyed** [comment]
Fine with me. :) Feel free to make the change please

**Comment by leleuj** [comment]
I hope it makes things a little clearer: https://github.com/Jasig/cas/pull/1358
