### ISSUE TITLE
Documentation about how to get the Principal Attributes

### ISSUE THREAD

**Issue by edpichler** [Jasig/cas#1360]
I know I should post this problem on cas-users list, but there is difficult to someone answer, and despite of this, I want to relate another documentation problem. 

I also plan to contribute on documentation, but before being able to do this, I need to understand how it works so I can help.

It's really hard to understand how I read the Principal attributes from a CAS client application. Here
http://jasig.github.io/cas/4.1.x/integration/Attribute-Resolution.html is said that this is possible through CAS or SAML protocol. I'm trying to use CAS protocol, but I can't find what is the URL I need to access. All examples I found just tells me that I need to change my web.xml and use the already done CAS client libraries. I want to get the Principal Attributes from any REST application.

What is the URL endpoint to get the Principal Attributes? Where I can found this on documentation?

**Comment by mmoayyed** [comment]
The document your refer to shows you how attributes can be retrieved by CAS from a source. That is step 1. Step 2 is to allow those attributes to be released per application. Once you have resolved AND released the attributes, your CAS client needs to point to a particular endpoint. That endpoint is described by the CAS Protocol here http://jasig.github.io/cas/4.1.x/protocol/CAS-Protocol-Specification.html#attributes-cas-30

**Comment by leleuj** [comment]
The CAS protocol page: http://jasig.github.io/cas/4.1.x/protocol/CAS-Protocol.html as well as the SAML protocol page: http://jasig.github.io/cas/4.1.x/protocol/SAML-Protocol.html give you information.

**Comment by edpichler** [comment]
@mmoayyed Where is documentation about step 2 you refer?

**Comment by mmoayyed** [comment]
Menu on the left-hand side, "Attribute Release":
http://jasig.github.io/cas/4.1.x/integration/Attribute-Release.html

**Comment by edpichler** [comment]
@mmoayyed thank you, I will read it.
Guys, I confess I'm getting some difficulties to assembly these dispersed information of documentation. I hope I can contribute back to the project with what I had learn.

**Comment by mmoayyed** [comment]
Sounds good. Whatever makes it easier.

**Comment by edpichler** [comment]
@mmoayyed any new tip to me?

I configured the service to get all attributes, in this (unique on folder) json file:
![json](https://cloud.githubusercontent.com/assets/358696/11845010/ccfd1722-a3f8-11e5-8533-c1245d086a2a.png)

The static attributes are being processed.
![attributes](https://cloud.githubusercontent.com/assets/358696/11844980/b43f9714-a3f8-11e5-8d76-0caeff965a0c.png)

But the response still doesn't contains the attributes.
![junit](https://cloud.githubusercontent.com/assets/358696/11844981/b4489b02-a3f8-11e5-9765-45db885b44dd.png)

**Comment by mmoayyed** [comment]
Either you are not resolving attributes or your client is pointing to the wrong endpoint.

**Comment by edpichler** [comment]
@mmoayyed You are right. Now it finally worked.

I use CAS 4.1 and the endpoint shouldn't be **/serviceValidate** as it is in http://jasig.github.io/cas/4.1.x/protocol/CAS-Protocol-Specification.html#attributes-cas-30 section.

It must be  be **/p3/serviceValidate** as it is in http://jasig.github.io/cas/4.1.x/protocol/CAS-Protocol-Specification.html#p3servicevalidate-cas-30

Now it worked, but a lot of blank lines and empty space is being returned on response, between the XML lines.
 
![defaultprincipalfactory_java_-_cas-server_-____git_cas-easypnr_](https://cloud.githubusercontent.com/assets/358696/11846552/44cabe74-a400-11e5-9577-560ce8e307de.png)

**Comment by mmoayyed** [comment]
This is the page that gets rendered:
https://github.com/Jasig/cas/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/3.0/casServiceValidationSuccess.jsp

There are no extra lines in there, or it's something on your end most likely. I don't know what is your client, but if it's REST, you could use Pac4j's CAS REST client.

**Comment by mmoayyed** [comment]
> By the way, why these prefixes /v1/ or /p3/. The protocol I use is "version 3.0" on CAS 4.1, I think everything should be on /v3/.

You are using version 1 of the CAS rest API to talk to v3 of the CAS protocol.
