### ISSUE TITLE
gradle eclipse java.lang.String cannot be cast to org.gradle.api.JavaVersion

### ISSUE THREAD

**Issue by yahuvi** [Jasig/cas#1365]
I clone cas master source code from github and gradle eclipse via cmd,

error log following:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cas-management-webapp:eclipseJdt'.
> java.lang.String cannot be cast to org.gradle.api.JavaVersion

java and gradle version following:

C:\Users\SunYanhui>java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

C:\Users\SunYanhui>gradle -v

------------------------------------------------------------
Gradle 2.9
------------------------------------------------------------

Build time:   2015-11-17 07:02:17 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Windows 8.1 6.3 amd64

**Comment by mmoayyed** [comment]
See https://github.com/jhipster/generator-jhipster/issues/377
