### ISSUE TITLE
what is the browser requirement?

### ISSUE THREAD

**Issue by bikeshtricon** [Jasig/cas#1371]
what is the browser requirement for implementing cas client?
will it work on older browser ?

**Comment by mmoayyed** [comment]
This is an issue that should be reported to the cas client. Not the server. 

Also see http://jasig.github.io/cas/4.1.x/installation/User-Interface-Customization.html

**Comment by bikeshtricon** [comment]
"
Browser Support :
    Google Chrome
    Mozilla Firefox
    Apple Safari
    Microsoft Internet Explorer
"
Not specifying version

**Comment by mmoayyed** [comment]
As far as we are concerned, there isn't one but we obviously don't actively support FF 20, Chrome 20 or IE6.

**Comment by bikeshtricon** [comment]
Thanks for your reply 
what about 
Netscape Navigator & Apple Safari ?

**Comment by mmoayyed** [comment]
Only sure way is to try and see what happens.

**Comment by dima767** [comment]
Netscape Navigator?!!! This is a defunct proprietary browser that exists in the "museum of Internet". Wondering the reason for the question about it. @bikeshtricon - are you or anyone you know of using it?

**Comment by dima767** [comment]
And so I say that CAS server definitely "does not support" Netscape Navigator :-)
