### ISSUE TITLE
how to get shiro roles and  permissions attributes from cas server

### ISSUE THREAD

**Issue by cnicy** [Jasig/cas#1374]
when i use shiro-cas client buile web application
i want to get shiro roles and  permissions attributes from cas server
but the cas server can not response roles and  permissions 
so how to get shiro roles and  permissions attributes from cas server when i used below
https://github.com/apache/shiro/blob/1.2.x/support/cas/src/main/java/org/apache/shiro/cas/CasRealm.java#L162

**Comment by mmoayyed** [comment]
This is a question bet suited for the CAS user mailing list. You need to have CAS retrieve those roles and permissions, authorize them for release to your app and your client must point to the right endpoint.
