### ISSUE TITLE
Build error :      net.sf.ehcache.store.disk.DiskStorageFactory - Disk Write of item

### ISSUE THREAD

**Issue by gituser786** [Jasig/cas#1377]
when I build my project in local using cygwin64, I got subject error.

testAddToMyLibraryHashCodesAddsToAnExistingCacheEntry(com.pearson.ltg.ole.service.MyLibraryCacheServiceTest)  Time elapsed: 0.028 sec  <<< ERROR!
net.sf.ehcache.CacheException: java.io.FileNotFoundException: C:\cygwin64\tmp\myLibraryCache.data (Access is denied)

myLibraryCache.data  --> This  file is not available but its trying to access.  Not sure what it is...

**Comment by mmoayyed** [comment]
This is not a CAS issue, because that is not a CAS test and that is not a CAS file.

**Comment by gituser786** [comment]
I am trying to build my project in local using cygwin. I am getting file permission denial error. So requesting to get a help

**Comment by mmoayyed** [comment]
I understand, but that's not something we can help with here :( you should either post that question on the CAS mailing list or get in touch with cygwin folks who might know how to get around this issue.

**Comment by gituser786** [comment]
thank you
