### ISSUE TITLE
[CAS 4.x] Load Test or Performance Test 

### ISSUE THREAD

**Issue by richardwei2008** [Jasig/cas#1388]
Dear, is there an open resource about load test or performance test result on CAS 4? Or how can I carry out the test by myself? Is there a guidance?

Online published resources is quite simple.
https://isa.its.yale.edu/confluence/display/CAS/Test+Scenarios
https://issues.jasig.org/browse/CAS-131

Btw, what is the opinion from CAS community if organization plan to use CAS4.x in production environment?

**Comment by alexkolson** [comment]
Can't speak for the core dev team, but as a deployer we use [JMeter](http://jmeter.apache.org/) to run distributed load tests against our CAS instance.
