### ISSUE TITLE
TGC not being set. Documentation outdated/incomplete?

### ISSUE THREAD

**Issue by tduehr** [Jasig/cas#1392]
When logging in to a service via CAS, I get returned to the CAS login page and the TCG is not getting set.

The sso session cookie documentation is a bit sparse.
http://jasig.github.io/cas/development/installation/Configuring-SSO-Session-Cookie.html

And, the long term authentication documentation still refers to their old spring configuration in `ticketExpirationPolicies.xml` and `ticketGrantingTicketCookieGenerator.xml`
 http://jasig.github.io/cas/development/installation/Configuring-LongTerm-Authentication.html

My deployerConfigContext.xml
https://gist.github.com/anonymous/929bd0b7a78d703cae4e

Ldaptive is based on this PR:
https://github.com/vt-middleware/ldaptive/pull/62

pom.xml
https://gist.github.com/anonymous/1aa0eca4fc38fefdc790

**Comment by mmoayyed** [comment]
What is your CAS server url?

**Comment by mmoayyed** [comment]
This definitely needs to be corrected:
https://jasig.github.io/cas/development/installation/Configuring-LongTerm-Authentication.html

**Comment by tduehr** [comment]
~~~
server.name=https://sso.example.com
server.prefix=${server.name}/cas
~~~

**Comment by mmoayyed** [comment]
Does this happen when you use long-term authN or does it happen without it?

**Comment by mmoayyed** [comment]
Is your connection to the server "actually" secure? by default the cookie is not generated for insecure connections. I realize you have https there, but just wanted to make sure.

**Comment by tduehr** [comment]
Without long term authn.

I'm not getting a warning from the CAS UI about CAS being hosted insecure. The CA used should be trusted by the cas host and is trusted by my browser. I've tested with both the cas service management webapp(4.1.x) hosted on the same box by the same apache https proxy and a gitlab instance hosted on another host over HTTP.

**Comment by tduehr** [comment]
I also have HSTS set. Though, I seem to remember 4.1.x needing some flag somewhere to tell CAS it's definitely being served securely. That may be what's missing here...

**Comment by mmoayyed** [comment]
OK. There may be a bug somewhere. I am seeing a TGC in my local environment, so we just need to figure out the difference. 

Two things:

1. Could I ask you to post full DEBUG logs, stripping out sensitive data? 
2. When you say "TGC not set", do you mean you don't see the cookie, or you don't see an expected value?

The cookie by default is generated under secure connections. Controlled via `tgc.secure=true`

Defined here:
https://jasig.github.io/cas/development/installation/Configuring-SSO-Session-Cookie.html

The HSTS can be enabled via:
https://jasig.github.io/cas/development/planning/Security-Guide.html#cas-security-filter

I agree that docs seem sparse. Feel free to submit any improvements you think might help clarify.

**Comment by tduehr** [comment]
1. What do you want flagged for debug logging? `org.jasig.cas`? Nothing useful in that log, just normal `org.jasig.cas.authentication` logs from a successful ldap login.
2. The `set-cookie` header is not being sent.

I just ran across `tgc.secure` myself. This only controls the `Secure` flag on the cookie. There is no reason I see in `CookieRetrievingCookieGenerator` or `SendTicketGrantingTicketAction` that the cookie shouldn't be sent to the browser.

**Comment by tduehr** [comment]
log since the last redeploy:
https://gist.github.com/anonymous/8dd33344425e5dedaf67

**Comment by mmoayyed** [comment]
Yes, set org.jasig.cas to DEBUG. 

If you can, step into `CookieRetrievingCookieGenerator`. That's likely where the problem is, if any. That class is responsible for adding/retrieving cookies, and if it's doing its job correctly and your logs show that, the problem is somewhere else.

**Comment by mmoayyed** [comment]
> The set-cookie header is not being sent.

I don't know if this ever gets set. At least, I don't know enough to tell you accurately. What I can tell you is that the browser should show you this, in FF for example:

![image](https://cloud.githubusercontent.com/assets/1205228/12038487/c61864b2-ae15-11e5-9149-f234bdce719b.png)

**Comment by mmoayyed** [comment]
If you see the TGC like above, and yet that header is not presented for you, my question then would be: why do you need that header? what does that give you?

If you DO need it, you likely need to mod that class to have it set that header if there is a way to mod it. We rely on Spring to generate cookies, and so whatever they allow us to set, that's what we do.

**Comment by tduehr** [comment]
It's set to tell the browser to store the cookie. I'm watching the traffic in a proxy. There's no TGC cookie because there's no set-cookie header.

**Comment by mmoayyed** [comment]
OK that may explain it. Can you access the CAS server without the proxy and see if you still don't get the cookie?

**Comment by mmoayyed** [comment]
Chances are, either your proxy is misconfigured for secure connections somehow, or there is something in the request that `DefaultCasCookieValueManager` does not like. Next step would be to try this without the proxy, and see if you can still duplicate it. If not, then we know where to look better.

**Comment by tduehr** [comment]
I started trying through the proxy because the cookie wasn't being set.

**Comment by tduehr** [comment]
I added a debug print to the `SendTicketGrantingTicketAction` class. It's not being hit currently. No logging by anything other than ldap authentication is occurring.

**Comment by tduehr** [comment]
What authentication setup are you using?

**Comment by tduehr** [comment]
Here's a new log. This time I set `create.sso.missing.service` to false.

https://gist.github.com/anonymous/14830975ee86b262c336

**Comment by mmoayyed** [comment]
I am just using the  default. No other changes. The fact that you are not hitting that breakpoint tells me that something is very wrong. start by weeding out your custom changes such as  your registry and your authentication and then keep repeating the same process until you can generate the ticket granting ticket cookie.once you're there then start adding changes back to see which one actually causes this behaviour although it's very difficult to conjecture one of them causing this issue for you because they really have nothing to do with with cookie generation.

 if that break point is not hit and something else in your overlay is completely wrong. check out your login flow that maybe also a cause. The flow should be sending you to a state where TGTs are generated.

**Comment by mmoayyed** [comment]
Well, this `create.sso.missing.service` will definitely stop the TGC. What this setting when to set to false indicates is that CAS always should expect a service parameter upon or it will fail the request, which is something you do see in the logs. So set this one back to true. 

In your log4j file, what is org.jasig.cas.web set to? Make sure that is also set to DEBUG. Report the logs again.

**Comment by tduehr** [comment]
`<Logger name="org.jasig.cas" level="debug" additivity="true">`

I'll specifically set `org.jasig.cas.web` to `debug` shortly.

I set `create.sso.missing.service` as a diagnostic test. There are a few requests without a service at the start of the log. The last entry is part of an actual authentication attempt. I haven't' dug far enough into the code to see where the service parameter is being stripped but it seems `InitialFlowSetupAction` is being loaded twice somehow.

**Comment by mmoayyed** [comment]
Double log calls are generally a result of additivity=true. You may want to set that to false and define appenders explicitly. 

by the way the docs should be updated for long-term authN.

**Comment by tduehr** [comment]
Got it!

I had set default mappings for `/js/*` and `/css/*` which were lost when I removed that web.xml for the upgrade to 4.2.0. I also have a change to load all of the javascript locally but did not have the *.map files on my host. 

This worked fine with my default servlet mappings since they just returned a 404 and everything went on. However, using the global default servlet, they get referred to the application which 302s to `/login`. When that happens, `InitialFlowSetupAction` is called again and the previous `service` parameter wiped for this "new" phantom login.

Removing that customized cas.js (or adding the *.map files) fixes the immediate symptom.

However, as it sits, this is a race condition: if multiple authentications are attempted fast enough, only one will get the correct redirect. I see this often in other SSO implementations. Most applications can just see if the session already has this information and just not reset it instead of blindly writing it. CAS, and generally SSO implementations, is in an odd place since this will need to be reset or overwritten at times. The easiest thing to do is tell users to log into one application at a time.

**Comment by mmoayyed** [comment]
> However, as it sits, this is a race condition: if multiple authentications are attempted fast enough, only one will get the correct redirect.

I guess I don't understand this statement accurately. Is this something you can reproduce with a vanilla CAS instance via something like JMeter scripts? Trying to wrap my head around the problem, but so far it seems like custom changes created this behavior. Is this something that has the potential to be "fixed" in core?

**Comment by tduehr** [comment]
It's the customization that allowed the bug to show. The only customization I did to those files was to make them use local resources not remote (ie. a local copy of jquery rather than grabbing it from google). The symptom can be prevented by adding default servlet mappings for `/js/*` and `/css/*`.

I tried replicating this manually without that customized js, but couldn't.

Restated: I think the service sending the authentication request is stored in the session somehow and gets rewritten if the original request is still being processed when the second comes in.

I think this thread at this point covers it should someone else run into this. Feel free to close.

**Comment by mmoayyed** [comment]
Very good. Thank you for keeping up with this. 

There is an issue that asks for localizing such resources, JS specially. While that does have benefits, long term it makes the maintenance aspect very difficult. I realize it's not the best security practice, but I am torn :) 

Would it hurt if we simply added default servlet mappings for /js/* and /css/* resources? Just to cover all bases? 

I'd be curious to see if the race condition can actually be duplicated. I know several very large deployments where extensive loads were put on the server, and never a problem as such was reported. Not saying it doesnt exist, just that it'd be good to duplicate it before looking for a black cat in a dark room.

**Comment by tduehr** [comment]
I may still be able to replicate it. I just realized i'd reverted all my changes to make sure the services manager can load...

The default servlet mappings may also not be necessary. I'm going to do ore testing as I get this update installed.

Either way, it's safe to close this for now.
