### ISSUE TITLE
person-directory-impl-1.7.0  find not  ParameterizedRowMapper  class 

### ISSUE THREAD

**Issue by yahuvi** [Jasig/cas#1395]
cas-server-core dependency  person-directory-impl-1.7.0

The  person-directory-impl-1.7.0 dependency spring jar is too old, find not this class

Caused by: java.lang.ClassNotFoundException: org.springframework.jdbc.core.simple.ParameterizedRowMapper

**Comment by mmoayyed** [comment]
That class has been available in Spring since Spring 2. It cannot be too old. What is the Spring version? Do you not have a version conflict?

**Comment by mmoayyed** [comment]
Also this sounds like a bug you should report to person directory instead?

**Comment by yahuvi** [comment]
Prior to Spring 3.0 ,it contains  ParameterizedRowMapper class ,but Spring version 4.2.3 not, cas 4.2.0 dependency spring version 4.2.3

**Comment by mmoayyed** [comment]
OK Cool. You should then ask person directory to update its Spring and release a new version.

**Comment by mmoayyed** [comment]
https://github.com/Jasig/person-directory

**Comment by mmoayyed** [comment]
Relevant section: https://github.com/Jasig/person-directory/blob/master/pom.xml#L59

**Comment by mmoayyed** [comment]
https://issues.jasig.org/browse/PERSONDIR-96

**Comment by yahuvi** [comment]
@mmoayyed,thank you very much your help.

**Comment by mmoayyed** [comment]
I have just released 1.7.1 which updates the PD project to use the latest of Spring. Give that a try.
