### ISSUE TITLE
Service Management web app issue with JSON files

### ISSUE THREAD

**Issue by karlgrose** [Jasig/cas#1405]
When (at least Unix-style) text files are used for the JSON service definitions, the Service Management web app will truncate the final newline character in the file while saving any changes. This is a minor annoyance, but probably unintended behavior.

**Comment by mmoayyed** [comment]
Interesting. Definitely unintended. Does that cause any issues later on with CAS or other tools you might use to read and parse the JSON files? How is the problem manifested?

**Comment by karlgrose** [comment]
No issues noticed yet; it happens when editing by hand with a standard editor such as vim and saving the file. The vim editor inserts the closing newline which persists until the Service Management editor is used. After that, using cat on the file displays the final character "}" on the shell prompt line.

**Comment by mmoayyed** [comment]
OK. We can definitely accommodate this.

**Comment by mmoayyed** [comment]
Turns out, this isn't easily possible. Since CAS pretty prints the JSON response, it auto-removes the line ending as the pretty printer considers that unnecessary. I'll close this for now, since it's not actually causing any particular issues.
