### ISSUE TITLE
Wildcard/Regex support in access control

### ISSUE THREAD

**Issue by jonathanlabin** [Jasig/cas#1414]
For example, the documentation shows an example access control situation that lists valid values of the required attribute:

    "cn" : [ "java.util.HashSet", [ "admin, Admin, TheAdmin" ] ]

Could include support for a wildcard feature or full-blown regex such as:

    "cn" : [ "java.util.HashSet", [ ".*[Aa]dmin.*" ] ]

Not that you'd trust your admin access control to such a filter but as an example of possible capability.

**Comment by mmoayyed** [comment]
What we probably could do best is to consider every entry in that set to be a regex pattern. If the pattern is valid, use it to match against what's needed. otherwise, fall back onto the current behavior. That work for you?

**Comment by mmoayyed** [comment]
Related to https://github.com/Jasig/cas/issues/1417

**Comment by mmoayyed** [comment]
See https://github.com/Jasig/cas/issues/1421
