### ISSUE TITLE
CAS Ticket Validated but then gets deleted before the next getTicket call

### ISSUE THREAD

**Issue by dl2sail** [Jasig/cas#1415]
After upgrading to CAS Maven Overlay 4.1.3 we encounter and issue where the user looked like they were authenticated properly but then a call to getTicket failed.  Here is what we found:

1. User is authenticated
2. CentralAuthenticationServiceImpl.java in method validateServiceTicket(..) in the final clause the ticket gets deleted (line 472-476)
} finally {
    if (serviceTicket.isExpired()) {
        this.serviceTicketRegistry.deleteTicket(serviceTicketId);
    }
}

3. The Audit annotation calls the method "public <T extends Ticket> T getTicket(final String ticketId, final Class<? extends Ticket> clazz)" starting at line 514, which calls final Ticket ticket = this.ticketRegistry.getTicket(ticketId, clazz);
BUT at that point the ticket was deleted so the error INVALID TICKET is returned.  In the 4.0.X this was not an issue because the method would just return null.  

We noted that in 4.1.x it returns an error:
        if (ticket == null) {
            logger.debug("Ticket [{}] by type [{}] cannot be found in the ticket registry.", ticketId, clazz.getSimpleName());
            throw new InvalidTicketException(ticketId);
        }

While 4.0.x returns null
if (ticket == null) {
    return null;
}

**Comment by mmoayyed** [comment]
So what you are saying is, the audit log does now show the validated ticket? I am not sure what the actual issue here is. Could you explain?

**Comment by dl2sail** [comment]
CAS fails to the user authentication every time now.   
1. "validateServiceTicket" is called and the user is authenticated properly (for the moment...)
2. finally block is reached and the ticket is deleted
3. The "Audit" annotation runs which calls getTicket method
 @Audit(
        action="SERVICE_TICKET_VALIDATE",
        actionResolverName="VALIDATE_SERVICE_TICKET_RESOLVER",
        resourceResolverName="VALIDATE_SERVICE_TICKET_RESOURCE_RESOLVER")
4. The getTicket method finds that the ticket is now null and throws an error (previously this would return null and continue processing) and the user is now invalidated and cannot log in

**Comment by mmoayyed** [comment]
OK. Thanks. I"ll run some tests to see if this can be duplicated in a vanilla deployment. If the issue is confirmed, will you be able to provide a fix?

**Comment by dl2sail** [comment]
Yes I'd be happy to

**Comment by mmoayyed** [comment]
I see no exceptions in the logs whatsoever.

**Comment by mmoayyed** [comment]
There is however this log line:

```
[STDOUT] 2016-01-07 01:39:12,444 DEBUG [org.jasig.cas.audit.spi.TicketOrCredentialPrincipalResolver] - <Could not locate ticket [ST-1-x1ereCwizL30iZbZPKNk-cas01.example.org] in the registry>
[STDOUT] 2016-01-07 01:39:12,444 DEBUG [org.jasig.cas.audit.spi.TicketOrCredentialPrincipalResolver] - <Unable to determine the audit argument. Returning [audit:unknown]>
```

But then, I see
```
[STDOUT] =============================================================
[STDOUT] WHO: audit:unknown
[STDOUT] WHAT: ST-1-x1ereCwizL30iZbZPKNk-cas01.example.org
[STDOUT] ACTION: SERVICE_TICKET_VALIDATED
[STDOUT] APPLICATION: CAS
[STDOUT] WHEN: Thu Jan 07 01:39:12 MST 2016
[STDOUT] CLIENT IP ADDRESS: 192.168.1.139
[STDOUT] SERVER IP ADDRESS: 192.168.1.139
[STDOUT] =============================================================
```

So you are saying you want to see the WHO field?

**Comment by dl2sail** [comment]
In our scenario we could not SSO into our application because after we received “SERVICE_TICKET_VALIDATED” our ticket was deleted then “Audit” annotation was fired and the Audit process threw an error (when it tried to getTicket) which made the SSO connection to fail.

**Comment by mmoayyed** [comment]
Well I can not duplicate this with a vanilla overlay project so whatever is causing the issue must be specific to your environment unless you can provide more details

**Comment by mmoayyed** [comment]
Well I can not duplicate this with a vanilla overlay project so whatever is causing the issue must be specific to your environment unless you can provide more details
