### ISSUE TITLE
Fix failing tests on CAS 4.1.x branch

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1418]
The 4.1.x is configured to disable checkstyle, tests and findbugs. Enable them and fix any failing tests.

This might be more difficult to do as there may be a number of dependencies out there, specially for radius whose repos have gone dead. We'll need to account for those too.

**Comment by leleuj** [comment]
For tests, I say yes, but for Checkstyle and Findbugs, is it worth it (as the 4.1.x branch is the oldest maintenance branch)?

**Comment by mmoayyed** [comment]
You may have a point there. I'd say findbugs is more important than checkstyle, but I shall experiment and see how long each phase takes.

**Comment by mmoayyed** [comment]
This is done. 4.1 and 4.2 fully building as well as master/4.3
