### ISSUE TITLE
RuntimeException with CAS 4.1.3 Shibboleth IdP integration configuration

### ISSUE THREAD

**Issue by wanggang1** [Jasig/cas#1423]
I try to follow the instruction, http://jasig.github.io/cas/4.1.x/integration/Shibboleth.html, and use the external (2nd) option.  But when the cas.war is deployed and the login page is accessed, there is a runtime exception.  Looks like it's caused by the static metadata source configuration.  Before this changes, I have already enabled SAML 2.0 Google Account.  Don't know if that is related.  

The stacktrace is provided below, and the configuration files changed for this integration also included.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metadataAdapter': Invocation of init method failed; nested exception is java.lang.RuntimeException: org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'DEFAULT.StaticMetadataResolverAdapter', because one already exists with this identification.
	org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1564)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
	org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1137)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1040)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:759)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:664)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:630)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:678)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:549)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:490)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

```
[cas-servlet.zip](https://github.com/Jasig/cas/files/80390/cas-servlet.zip)

**Comment by mmoayyed** [comment]
Note that your `<bean id="metadataFilters">` does absolutely nothing, as it's not connected to your resources.

**Comment by mmoayyed** [comment]
Also you need to pick the parser action you have configured in your webflow.

**Comment by mmoayyed** [comment]
Do you have your configuration for SAML 2.0 Google Account? Because I can't duplicate this at all based on what you have provided, so I am thinking it may be related to your changes there.

**Comment by mmoayyed** [comment]
I did also enable Google Apps AND your changes. Could not duplicate.

**Comment by mmoayyed** [comment]
The only way this could be reproduced is if your configuration is somehow initializing the `metadataAdapter` twice, which causes the job scheduler that reads the metadata to be created twice. Check your configuration and see what extra elements you have added.

**Comment by wanggang1** [comment]
I have searched my overly project, but didn't find any other metadataAdapter being initialized.  I'm seeing this exception in browser when I try to access /cas/login page, but the logs in cas.log states "Metadata aggregate initialized successfully" every time I access /cas/login from broswer (see attached screen shots).  Any clue what could be wrong on my end?  Also could you provide me a sample on how to properly config <bean id="metadataFilters">?  I was just copying that from the instruction.  Thanks!
![cas-log](https://cloud.githubusercontent.com/assets/176723/12171200/ae8c0bc6-b515-11e5-8a3c-9e4e651a5952.png)
<img width="723" alt="exception-in-browser" src="https://cloud.githubusercontent.com/assets/176723/12171203/b87f3c0c-b515-11e5-884a-59b7b831dfa7.png">

**Comment by mmoayyed** [comment]
I believe you're experiencing that exception because your configuration is scanning your XML configuration twice so look for elements that do component scans in your configuration. Also your configuration shows that your filters list is actually empty. You will need to connect your metadata filters to the list of resources and don't have that list the actually empty as it is right now

**Comment by wanggang1** [comment]
My CAS project is maven overlay following https://github.com/Jasig/cas-overlay-template.  In it, the only scan is in cas-servlet.xml which is copied into overlay for shibboleth customization.  Could this be the issue, both cas-servlet.xml in overlay and in cas-server-webapp being loaded?  Were your tests also in maven overlay project?  Do you say a way I could get around this?  thanks!

**Comment by mmoayyed** [comment]
Yes. I used the same exact overlay and followed instructions on the docs. Attach your overlay here.

**Comment by wanggang1** [comment]
here is my overlay project, thanks!
[cas-overlay.zip](https://github.com/Jasig/cas/files/81267/cas-overlay.zip)

**Comment by mmoayyed** [comment]
I found a small issue, but not relevant to your error message. as far as I can tell, this issue is non-existent.

**Comment by wanggang1** [comment]
Could you provide me some tips as how should I fix my issue?  From what I could tell, when I remove the cas-servlet.xml from my overlay project, CAS works fine.  When I drop cas-servlet.xml into the overlay project, I get this runtime exception complaining initiation of metadataAdapter bean which is required by the shibboleth plugin configuration.  thanks!

**Comment by mmoayyed** [comment]
I don't know how to fix the issue, because as far as I can tell, I don't see an issue. What you are seeing is either the result of cas application context loading twice, or there is a different issue hidden somewhere. Take out your specific extensions and start with a vanilla config. Gradually add your extensions and see what causes the issue. It's something specific to your environment. That's all I can say.

**Comment by mmoayyed** [comment]
> which is required by the shibboleth plugin configuratio

Also, not required. Optional.

**Comment by wanggang1** [comment]
thanks!
