### ISSUE TITLE
Use pac4j to protect the /authorize OAuth endpoint

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1425]

**Comment by mmoayyed** [comment]
:+1: 

Do also consider attribute consent as well.

**Comment by mmoayyed** [comment]
By that I mean, don't let the user choose attributes that are to be consented. Simply rely on the attribute release policy to just let the user know said attributes are going to be released. Consent is more like a billboard, not a menu.

**Comment by leleuj** [comment]
I will keep the same behaviour for the consent part: it's a rebuild with the same feature. The idea is to clean code and prepare other grant types and OpenId Connect.

**Comment by leleuj** [comment]
I think I've done much of the work to use pac4j to secure the `/authorize` endpoint. I finally get rid of JWT (which will be only used for OpenId connect) to use opaque identifiers as it's the spirit of OAuth. So I have created an `AccessToken` and `OAuthCode`, which are empty interfaces inherited from `ServiceTicket` to leverage the OAuth tokens solution on the powerful ticket registries support we have.

@mmoayyed : the problem I have is that Checkstyle refuses empty interfaces: I don't understand this rule. Can we relax on that?

**Comment by mmoayyed** [comment]
Empty? as in completely empty marker interfaces? 

I don't mind relaxing the rule, but let me understand the purpose of these interfaces better. You want tokens and codes to have their own distinct personality, but still be treated as an ST. Correct? 

It's a bit to difficult and premature to talk design, but I'd be okay with relaxing that rule. Marker interfaces serve a purpose.

**Comment by frett** [comment]
for `AccessToken` would there be benefit from extending `TicketGrantingTicket` or `ProxyGrantingTicket` for that instead? access tokens generally have a longer life than authorization codes and service/proxy tickets. Plus is they are also normally multi-use.

**Comment by frett** [comment]
I bring this up because some of the work I've done on my local deployment (in my own custom OAuth implementation) is to support a resource endpoint that could issue a `ServiceTicket` using an active `AccessToken`. This allows apps to bridge from the OAuth protocol to other CAS protected resources using the proxy protocol.

Depending on interest I could see this as a potential new resource endpoint that would require continued use of an `AccessToken` beyond the initial auth.

**Comment by leleuj** [comment]
I want to fit in our current tickets machinery to benefit from all the ticket registries we already have.

To sum up:
ST: linked to a service, short life, used once
TGT: an identity, long life, used multiple times
OAuth code: linked to a service, short life, used once
Access token: linked to a service, long life, used multiple times

So the OAuth code is obviously a ST. For the access token, there is a question indeed: it is linked to a service like a ST, but has a long lifetime like a TGT. I hesitated but finally choose to have the access token inheriting from the OAuth code which inherits from the service ticket, more a simplification in the source code, than a design choice.

I'll propose to revisit this question in the light of the pull request I'll submit. It will be easy for dicussion.

**Comment by frett** [comment]
@leleuj sounds good

**Comment by leleuj** [comment]
Here we go: https://github.com/Jasig/cas/pull/1463

I'm fairly happy with the result: JWT is not used any more (it will be for OpenID Connect), we now have opaque identifiers for codes and access tokens fully integrated with the CAS tickets ecosystem.
Using pac4j, the code is now straightforward. It's a good re-foundation to easily add new authorisation grant types later on.
