### ISSUE TITLE
CAS 4.2.0-RC1 Maven build failure - Unable to add Cas Server Support Saml feature (missing idp-profile-spring maven dependency)

### ISSUE THREAD

**Issue by peyobr** [Jasig/cas#1444]
Hi,

i'm unable to add maven dependency:

<dependency>
  <groupId>org.jasig.cas</groupId>
  <artifactId>cas-server-support-saml</artifactId>
  <version>${cas.version}</version>
</dependency>

Broken dependency found at:
http://mvnrepository.com/artifact/org.jasig.cas/cas-server-support-saml/4.2.0-RC1

Missing maven artifact:
http://mvnrepository.com/artifact/net.shibboleth.idp/idp-profile-spring

Thank you.

**Comment by mmoayyed** [comment]
As far as I can tell in the list of dependencies here:
http://mvnrepository.com/artifact/org.jasig.cas/cas-server-support-saml/4.2.0-RC1

There exists a idp-profile-spring. So?

**Comment by mmoayyed** [comment]
The shibboleth project publishes artifacts to its own repo here build.shibboleth.net/nexus/content/repositories/releases/

**Comment by mmoayyed** [comment]
We should fix the docs on this; adding that repo may be required for maven overlays.

**Comment by peyobr** [comment]
OK!!

**Comment by frett** [comment]
@mmoayyed any clue if there is a way to include repository configuration in the pom files gradle generates for the artifacts. it's one difference from switching from maven to gradle

**Comment by frett** [comment]
I just realized I already manually added the shibboleth repo to my own maven config. I thought it was automatically pulling the repo from dependencies, but this appears to not be the case.

**Comment by mmoayyed** [comment]
I'd imagine it's possible. We generate the poms with everything in it as you see, so it must a few extra lines to include repos as well. I'll review tomorrow.

**Comment by frett** [comment]
@mmoayyed the fact that I needed to manually include the repository in my maven overlay for the Shibboleth dependency on 4.1.x means it doesn't pull repository config from dependencies anyways, so this suggestion wouldn't address the needed repository config for deployers adding SAML support.

**Comment by mmoayyed** [comment]
Sad panda. Guess we can still document it.

**Comment by mmoayyed** [comment]
Had a second look. @frett I am not sure I am with you there. Nothing is pulled from dependencies right now, because nothing is published in the POMs of dependencies. Having compared 4.1 and 4.2, I see the repository info is published in the pom while it's not for 4.2. I do think that per your initial suggestion, if we do publish the repository info in the poms, that should be pulled by maven. Because otherwise, maven would be very very broken if folks were asked to include 10x repositories in their projects! That makes no sense to me.

**Comment by mmoayyed** [comment]
I started out with #1446 to experiment.

**Comment by mmoayyed** [comment]
@peyobr try with 4.2.0-RC2-SNAPSHOT and let us know if the problem persists.

**Comment by peyobr** [comment]
Ok, but now i had to manually add the follwing dependency:

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.1</version>
        </dependency>

in order to use cas-server-support-jdbc and cas-server-support-jpa-ticket-registry

**Comment by mmoayyed** [comment]
Just making sure, that is with  4.2.0-RC2-SNAPSHOT right?

**Comment by peyobr** [comment]
Yes

**Comment by mmoayyed** [comment]
That sounds like a different issue. Why would you need the httpclient for JDBC/JPA support?

**Comment by mmoayyed** [comment]
also, the httpclient should be automatically bundled with the webapp. Is it not?

**Comment by peyobr** [comment]
Sure you are right it's a different issue.

However i need to include that in order to avoid the following:

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaTicketRegistry': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.jasig.cas.logout.LogoutManager org.jasig.cas.ticket.registry.JpaTicketRegistry.logoutManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logoutManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.jasig.cas.util.http.HttpClient org.jasig.cas.logout.LogoutManagerImpl.httpClient; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'noRedirectHttpClient': FactoryBean threw exception on object creation; nested exception is java.lang.NoSuchMethodError: org.apache.http.impl.conn.PoolingHttpClientConnectionManager.setValidateAfterInactivity(I)V

**Comment by mmoayyed** [comment]
Sure, like I said you have a dependency conflict. That is not a CAS issue, per se. You are using a pac4j-oauth module that is pulling in for you a very old version of the httpclient, and the classloader happens to pick that one up instead of what is shipped from CAS. It is an issue in the sense that we should be excluding it from the build, but it's also an issue for pac4j to upgrade their dependency. 

I'll see what I can do for the first one.

**Comment by mmoayyed** [comment]
PS Thanks for the report. Appreciate you trying out the RC.

**Comment by peyobr** [comment]
Thank you (y)

**Comment by mmoayyed** [comment]
I included the pac4j-support module in the webapp overlay, which pulls in pac4j-oauth 1.8.2. I do see http-client 4.5.1 included in the final lib directory. No dependency conflict. Yours must come from another dependency, and must be excluded explicitly.
