### ISSUE TITLE
Wrong dependency on JS file

### ISSUE THREAD

**Issue by nicolasmoreira** [Jasig/cas#1455]
CAS is using this script: /cas/js/cas.js
 
```javascript
var scripts = [ "https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js",
    "https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js",
    "https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js",
    "https://rawgithub.com/cowboy/javascript-debug/master/ba-debug.min.js"];
```

Rawgit recomends use: https://cdn.rawgit.com/cowboy/javascript-debug/master/ba-debug.min.js instead of https://rawgithub.com/cowboy/javascript-debug/master/ba-debug.min.js

Extract from https://rawgit.com/faq FAQ:
 
"Can I use a rawgit.com URL on a production website?
No. Please use cdn.rawgit.com for anything that might result in heavy traffic. Only use rawgit.com URLs for low-traffic testing and sharing temporary examples or demos during development. When people misuse rawgit.com, it costs me money. Please don't be a jerk."

**Comment by mmoayyed** [comment]
Via https://github.com/Jasig/cas/pull/1454

**Comment by mmoayyed** [comment]
Thanks!

**Comment by nicolasmoreira** [comment]
Thanks!
