### ISSUE TITLE
Upgrade CAS overlays to 4.2

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1456]
Upgrade both the cas overlay and the management overlay to 4.2 RC1, in prep for the release so that adopters have a chance to try out and test the new functionality. 

Discussed with Dima. Handing over.

**Comment by dima767** [comment]
Brainstorming... perhaps `master` should be 4.2, with the `4.1` on the branch

**Comment by mmoayyed** [comment]
I agree.

**Comment by dima767** [comment]
OK, upgraded both cas and management web app to `4.2.0-RC1` and pushed both to `4.2` branch. CAS server is just fine while management web app blows up with all sorts of nasty oauth and pacj4 things. Not usable locally at the moment. I'm giving up on the management web app for now... This is the branch: https://github.com/Jasig/cas-services-management-overlay/tree/4.2 .. if someone could make it work, that'd be great.

Cheers,
D.

**Comment by leleuj** [comment]
Very disappointing as I thoroughfully tested the management webapp while replacing Spring Security by pac4j. I will check with the RC1.

**Comment by dima767** [comment]
I think it has something to do with Jackson and classloading when it tries to de-serialize the Oauth reg service back from JSON file which it created during bootstrap by this -> https://github.com/Jasig/cas/blob/v4.2.0-RC1/cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/OAuthServletContextListener.java#L42

**Comment by dima767** [comment]
OK, we identified the problem. Happens when both CAS and managment app is deployed into the same servlet container. The web app is tightly coupled to the oauth module and creates the oauth registered service, but since they both share the same JSON service registry CAS server throws up when it tries to de-serialize that oauth service magically (by servlet listener) created by management web app.

Long story shor - we need to de-couple oauth module from management web app module. @mmoayyed will try to take care of that for `4.3` and if not drastic enough we could backport it to the upcoming `4.2` GA

**Comment by mmoayyed** [comment]
Linked issue #1466

**Comment by tsschmi** [comment]
I am having a problem getting this to deploy to an external jetty setup.  The error in the logs is this

2016-01-21 18:16:20,975 WARN [org.springframework.web.context.support.XmlWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.springframework.web.accept.ContentNegotiationManager.getStrategies()Ljava/util/List;

This problem does not pop up until I add the LDAP authentication dependency.  Looking at the core pom and the ldap poms, I see that core is built with the latest Spring 4.2.3.  LDAP includes a dependency of spring-webflow with the latest tag of 2.4.2.  The issue is that weblfow-2.4.2 resolves to Spring verison 4.2.0.  This results in the cas.war being built with jars form both versions, and when it deploys we get the error above.  

Does this mean core can not be moved past 4.2.0 until spring-webflow is updated? 

Sorry if this is not the correct place to ask this
Travis

**Comment by mmoayyed** [comment]
No it's the right place. We'll likely need to exclude the older spring dependency from webflow. Can you provide a dependency tree for us and paste it here?

**Comment by tsschmi** [comment]
Here are the dependencies in the pom I am using:

    <dependencies>
        <dependency>
            <groupId>org.jasig.cas</groupId>
            <artifactId>cas-server-webapp</artifactId>
            <version>${cas.version}</version>
            <type>war</type>
            <scope>runtime</scope>
        </dependency>
        <dependency>
          <groupId>org.jasig.cas</groupId>
          <artifactId>cas-server-support-ldap</artifactId>
          <version>${cas.version}</version>
          </dependency>
    </dependencies>

Is this what you needed?

**Comment by mmoayyed** [comment]
So, then do a `mvn dependency:tree` and paste the output please.

**Comment by tsschmi** [comment]
[INFO] [dependency:tree {execution: default-cli}]
[INFO] org.jasig.cas:cas-overlay:war:1.0
[INFO] +- org.jasig.cas:cas-server-webapp:war:4.2.0-RC1:runtime
[INFO] \- org.jasig.cas:cas-server-support-ldap:jar:4.2.0-RC1:compile
[INFO]    +- org.springframework.webflow:spring-webflow:jar:2.4.2.RELEASE:compile
[INFO]    |  +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO]    |  +- opensymphony:ognl:jar:2.6.11:compile
[INFO]    |  +- org.springframework.webflow:spring-binding:jar:2.4.2.RELEASE:compile
[INFO]    |  +- org.springframework.webflow:spring-js:jar:2.4.2.RELEASE:compile
[INFO]    |  |  \- org.springframework.webflow:spring-js-resources:jar:2.4.2.RELEASE:compile
[INFO]    |  +- org.springframework:spring-context:jar:4.2.0.RELEASE:compile
[INFO]    |  |  \- org.springframework:spring-aop:jar:4.2.0.RELEASE:compile
[INFO]    |  +- org.springframework:spring-core:jar:4.2.0.RELEASE:compile
[INFO]    |  +- org.springframework:spring-web:jar:4.2.0.RELEASE:compile
[INFO]    |  \- org.springframework:spring-webmvc:jar:4.2.0.RELEASE:compile
[INFO]    +- org.apache.logging.log4j:log4j-jcl:jar:2.5:runtime
[INFO]    +- org.jasig.inspektr:inspektr-aspects:jar:1.3.GA:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.1:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO]    |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.1:compile
[INFO]    +- org.aspectj:aspectjweaver:jar:1.8.6:compile
[INFO]    +- org.apache.logging.log4j:log4j-core:jar:2.5:runtime
[INFO]    +- org.apache.logging.log4j:log4j-api:jar:2.5:runtime
[INFO]    +- org.jasig.cas:cas-server-core-authentication:jar:4.2.0-RC1:compile
[INFO]    |  +- org.jasig.cas:cas-server-core-api-ticket:jar:4.2.0-RC1:compile
[INFO]    |  +- org.jasig.inspektr:inspektr-audit:jar:1.3.GA:compile
[INFO]    |  |  \- org.jasig.inspektr:inspektr-common:jar:1.3.GA:compile
[INFO]    |  +- org.jasig.service.persondir:person-directory-impl:jar:1.7.0:compile
[INFO]    |  |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO]    |  |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.7:compile
[INFO]    |  |  |  +- com.sun.xml.bind:jaxb-core:jar:2.2.7:compile
[INFO]    |  |  |  |  +- javax.xml.bind:jaxb-api:jar:2.2.7:compile
[INFO]    |  |  |  |  \- com.sun.istack:istack-commons-runtime:jar:2.16:compile
[INFO]    |  |  |  \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.12:compile
[INFO]    |  |  |     \- javax.xml.bind:jsr173_api:jar:1.0:compile
[INFO]    |  |  +- org.apache.commons:commons-collections4:jar:4.0:compile
[INFO]    |  |  +- org.jasig.service.persondir:person-directory-api:jar:1.7.0:compile
[INFO]    |  |  \- org.springframework:spring-tx:jar:4.1.6.RELEASE:compile
[INFO]    |  +- org.jasig.cas:cas-server-core-api-services:jar:4.2.0-RC1:compile
[INFO]    |  \- io.dropwizard.metrics:metrics-annotation:jar:3.1.2:compile
[INFO]    +- org.ldaptive:ldaptive:jar:1.1.0:compile
[INFO]    |  \- commons-cli:commons-cli:jar:1.3.1:compile
[INFO]    +- org.ldaptive:ldaptive-beans:jar:1.1.0:compile
[INFO]    +- org.springframework:spring-expression:jar:4.2.3.RELEASE:compile
[INFO]    +- org.pac4j:pac4j-core:jar:1.8.2:compile
[INFO]    +- org.glassfish.web:javax.el:jar:2.2.6:runtime
[INFO]    |  \- javax.el:javax.el-api:jar:2.2.5:runtime
[INFO]    +- org.reflections:reflections:jar:0.9.10:compile
[INFO]    |  +- com.google.guava:guava:jar:15.0:compile
[INFO]    |  +- org.javassist:javassist:jar:3.19.0-GA:compile
[INFO]    |  \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO]    +- org.hibernate:hibernate-validator:jar:5.2.2.Final:runtime
[INFO]    |  +- org.jboss.logging:jboss-logging:jar:3.2.1.Final:runtime
[INFO]    |  \- com.fasterxml:classmate:jar:1.1.0:runtime
[INFO]    +- joda-time:joda-time:jar:2.9:compile
[INFO]    +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.5:runtime
[INFO]    +- org.jasig.cas:cas-server-core-util:jar:4.2.0-RC1:compile
[INFO]    |  +- org.springframework:spring-context-support:jar:4.2.3.RELEASE:compile
[INFO]    |  +- org.bitbucket.b_c:jose4j:jar:0.4.4:compile
[INFO]    |  +- commons-io:commons-io:jar:2.4:compile
[INFO]    |  +- org.jasig.cas:cas-server-core-api-util:jar:4.2.0-RC1:compile
[INFO]    |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO]    |  +- org.jasig.cas:cas-server-core-api-authentication:jar:4.2.0-RC1:compile
[INFO]    |  |  \- org.jasig.cas:cas-server-core-api-protocol:jar:4.2.0-RC1:compile
[INFO]    |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO]    |  +- org.apache.shiro:shiro-core:jar:1.2.4:compile
[INFO]    |  |  \- commons-beanutils:commons-beanutils:jar:1.8.3:compile
[INFO]    |  +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[INFO]    |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.3:compile
[INFO]    |  \- org.quartz-scheduler:quartz:jar:2.2.1:compile
[INFO]    |     \- c3p0:c3p0:jar:0.9.1.1:compile
[INFO]    +- org.springframework:spring-beans:jar:4.2.3.RELEASE:compile
[INFO]    +- org.aspectj:aspectjrt:jar:1.8.6:compile
[INFO]    +- org.slf4j:jul-to-slf4j:jar:1.7.12:runtime
[INFO]    +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO]    \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------

**Comment by mmoayyed** [comment]
@dima767 You should be able to resume the upgrade by the way.

**Comment by dima767** [comment]
Well, it's done... Only on the branch, until GA comes out ;-)

**Comment by dima767** [comment]
And with the new mgmt app property placeholder config location externalized, we don't even need an overlay for it ;-)

**Comment by mmoayyed** [comment]
So found a problem with the cas webapp of the 4.2. You are excluding log4j2 from the overlay, yet you don't configure it in cas.properties. Is that true on your end, or have I missed something?

**Comment by mmoayyed** [comment]
We do need an overlay to show it can be built. We may not need any fancy config for it. That's what you meant right?

**Comment by dima767** [comment]
Well, both overlays are ready on the `4.2` branch. On the cas side wrt log4j config location I do have it in my local, externalized `cas.properties`

**Comment by mmoayyed** [comment]
They both checkout per my testing. The only thing you likely need is 

```
log4j.config.location=file:///etc/cas/log4j2.xml
```

in your etc/cas.properties file.

**Comment by dima767** [comment]
Sure, will add that momentarily

**Comment by mmoayyed** [comment]
Excellent. I'll look into this dependency issue here, but we are good to go for the most part.

**Comment by dima767** [comment]
Done with log4j config location prop

**Comment by mmoayyed** [comment]
Copy that.

**Comment by mmoayyed** [comment]
@tsschmi I am not seeing this. You issue must stem from something else in the config.

**Comment by mmoayyed** [comment]
For clarity, I did try with Jetty 9.3.6.v20151106 and Tomcat 8. no errors.

**Comment by mmoayyed** [comment]
But I do see spring 4.2.0 creeping its way into the config. Just saying Jetty seems to have no issues with it, but that is an issue we should fix.

**Comment by tsschmi** [comment]
I am able to reproduce the error this way:
 
  1. git clone https://github.com/Jasig/cas-overlay-template.git
  2. cd cas-overlay-template
  3. git checkout remotes/origin/4.2
  3. edit pom.xml -
      add dependency -
        <dependency>
          <groupId>org.jasig.cas</groupId>
          <artifactId>cas-server-support-ldap</artifactId>
          <version>${cas.version}</version>
        </dependency>
 4. mvn clean package
 5. mvn jetty:run-war

This will cause the error I reported earlier for me.  I had a colleague try this on his machine and it ran without the issue.  The only difference we can find is I am running Ubuntu 15.10 and he has Red Hat.  If I do mvn jetty:run or mvn jetty:run-forked, the server comes up without the error.

**Comment by tsschmi** [comment]
Confirmed this morning that adding exclusions in the pom.xml for the spring 4.2.0 artifacts from the ldap dependency allows the war to be deployed now.  It is a complete mystery to me as to why not everyone has this class loading issue.

**Comment by mmoayyed** [comment]
Classloaders work in mysterious ways. I am working on making sure all dangling transitive dependencies are excluded correctly. This will be fixed before the final GA.

**Comment by mmoayyed** [comment]
Closing this as the work is done really for this issue. Thanks @dima767
