### ISSUE TITLE
Unable to set TGT cookie path by configuration

### ISSUE THREAD

**Issue by dasibre** [Jasig/cas#1457]
Is there another way to change the cookie path from "/cas" to "/". Changing it in the ticketGrantingTicketCookieGenerator.xml file doesn't seem to have the expected effect. It basically stays the same. 
I'm using Cas server 4.1, any assistance to do this programmatically if config will not do it, would be appreciated. 
<bean id="ticketGrantingTicketCookieGenerator" class="org.jasig.cas.web.support.CookieRetrievingCookieGenerator"
          c:casCookieValueManager-ref="cookieValueManager"
          p:cookieSecure="true"
          p:cookieMaxAge="-1"
          p:cookieName="TGC"
          p:cookieDomain=".example.com"
          p:cookiePath="/cas"/>

**Comment by mmoayyed** [comment]
See InitialFlowSetupAction. Looks like the cookie path is always scoped to the context path. So your /cas setting there seems like it has no effect! I am not sure I totally know why; this is the same behavior carried over from 3.x.

**Comment by mmoayyed** [comment]
I believe this needs to change. We should likely say: if the cookie path is not set, default it to the context path. Otherwise leave it alone. 

Pinging @leleuj  and @frett to confirm.

**Comment by frett** [comment]
There are some security implications with widening the scope of the cookie. Widening the scope will allow other deployed servlets in tomcat direct access to the SSO session cookie, which could have a cascade effect of the other servlets potentially becoming the weakest link in CAS session security.

With that said I feel we should establish security best practices with the default config, but still allow deployers to override those settings if something about their deployment requires the change.

@dasibre out of curiosity, what use case are you trying to address with changing the path of the cookie?

**Comment by dasibre** [comment]
@frett our applications are using sticky sessions which seems to nullify Single Logout callbacks. We figured creating request filters which could check the cas cookie for each request, if it didn't match value in the current session, user session will be reset and user will be sent back to CAS login thus, achieving SLO for all the applications.
