### ISSUE TITLE
Dangling threads on Tomcat shutdown

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1458]
Tomcat is unable to shut down correctly via shutdown.sh|bat with CAS 4.2 RC1 deployed. This seems to be an issue with dangling threads not properly shut down. The issue seems to have to do with the quartz background jobs that run, as well as the log4j log manager that is unable to gracefully close all running threads.

**Comment by frett** [comment]
I've done a little bit of work on improving shutdown for 4.0.x, it got real annoying developing locally when you had to restart tomcat every 2-3 deploys.

I'll package up the quartz changes and submit a PR. This will address some of the warnings, but not all.

**Comment by mmoayyed** [comment]
Yes indeed. I found out about this a couple of days ago. I am presently looking into log4j changes with the help of a colleague, so if you could investigate the quartz issue as well, that'd be superb. 

There seem to be a number of threads on SO suggesting workarounds for log4j2:
http://stackoverflow.com/questions/23359668/log4j2-asyncappender-thread-does-not-die-on-tomcat-undeploy-causing-memory-leak
http://stackoverflow.com/questions/19116984/log4j2-asynchronous-logger-thread-is-not-killed

I wonder if a dependency upgrade could solve this.

**Comment by frett** [comment]
I had something in a custom context loader that manually killed a log4j FileWatchdog thread, but that was log4j and not log4j2.

**Comment by mmoayyed** [comment]
Log4j2 automatically adds a servlet context listener that shuts down the logging context. Specially when deployed in a servlet 3 environment like Tomcat. However, I found out about this:

>Important Note! For performance reasons, containers often ignore certain JARs known not to contain TLDs or ServletContainerInitializers and do not scan them for web-fragments and initializers. Importantly, Tomcat 7 <7.0.43 ignores all JAR files named log4j*.jar, which prevents this feature from working. This has been fixed in Tomcat 7.0.43, Tomcat 8, and later. In Tomcat 7 <7.0.43 you will need to change catalina.properties and remove "log4j*.jar" from the jarsToSkip property. You may need to do something similar on other containers if they skip scanning Log4j JAR files.

From http://logging.apache.org/log4j/2.x/manual/webapp.html

Which is interesting, since I am running  Apache Tomcat/8.0.28. 

So I looked into my catalina.properties, and behold, I did find log4j*.jar element. Once I removed it, the only dangling threads that remained where the quartz threads.

**Comment by mmoayyed** [comment]
This sort of explains why I never encountered the same problem, because jetty does not do the same thing and that's what I mostly use. 

Just for internal dev, if you like, you could use the gretty plugin built into the webapp for 4.1 and beyond I think. Might be 4.2. It does have its own issues though, so be forewarned :)

Guess we can document this issue somewhere. If you could confirm this fix for me, that'd be great....and then the only thing to fix would be the quartz leaks.

**Comment by mmoayyed** [comment]
Just for completeness:

```java
public class Log4jServletContextListener implements ServletContextListener {

    private static final Logger LOGGER = StatusLogger.getLogger();

    private ServletContext servletContext;
    private Log4jWebLifeCycle initializer;

    @Override
    public void contextInitialized(final ServletContextEvent event) {
        this.servletContext = event.getServletContext();
        LOGGER.debug("Log4jServletContextListener ensuring that Log4j starts up properly.");

        this.initializer = WebLoggerContextUtils.getWebLifeCycle(this.servletContext);
        try {
            this.initializer.start();
            this.initializer.setLoggerContext(); // the application is just now starting to start up
        } catch (final IllegalStateException e) {
            throw new IllegalStateException("Failed to initialize Log4j properly.", e);
        }
    }

    @Override
    public void contextDestroyed(final ServletContextEvent event) {
        if (this.servletContext == null || this.initializer == null) {
            throw new IllegalStateException("Context destroyed before it was initialized.");
        }
        LOGGER.debug("Log4jServletContextListener ensuring that Log4j shuts down properly.");

        this.initializer.clearLoggerContext(); // the application is finished shutting down now
        this.initializer.stop();
    }
}

```

**Comment by frett** [comment]
so, what I did to deal with quartz leaks on 4.0.x (and 4.1.x) was to enable both `waitForJobsToCompleteOnShutdown` and `interruptJobsOnShutdownWithWait` on the scheduler. This meant I wait on the scheduler to finish shutting down before proceeding, and jobs that are interruptible are interrupted.

**Comment by mmoayyed** [comment]
Sounds like a plan.

**Comment by mmoayyed** [comment]
Please be sure to target the PRs for both 4.1 and 4.2. I'll then cherry pick the 4.2 one into master.

**Comment by frett** [comment]
I'll have a patch for 4.1 shortly, 4.2 looks a little more complex since each job appears to create it's own scheduler.

**Comment by mmoayyed** [comment]
Very good. If you need me to test the 4.2 changes, let me know please. 

I haven't tried this yet, but just thinking out loud, I wonder if we could:

- Set the same sort of settings on the scheduler for each job.
- Maybe consolidate on schedulers to just one and have it be a singleton?
- Or keep scheduler->job but somehow shut down the scheduler when the context dies?

**Comment by frett** [comment]
yeah, looking through how spring configures the schedulers right now, it appears that it does attempt to use a common instance, but I'm not sure how easy it would be to config that. I'm also not sure if the `destroy` method is called since I'm not sure if this is being configured in the Spring context.

What I might do is move the scheduler itself to common XML config, but leave individual jobs configuring  and registering themselves with the common scheduler.

**Comment by mmoayyed** [comment]
>What I might do is move the scheduler itself to common XML config, but leave individual jobs configuring and registering themselves with the common scheduler.

You read my mind.

**Comment by mmoayyed** [comment]
Oh by the way, if the scheduler does have any settings that you think could be externalized to control its behavior, let's create those settings, and have sensible defaults for them. That will be one less reason to poke around the xml config in overlays if/when needed.

**Comment by frett** [comment]
alright, let me externalize the quartz settings in case someone doesn't want their jobs interrupted

**Comment by frett** [comment]
so, it looks like using the spring quartz scheduler factory bean makes it tricky to manually manipulate the scheduler and register your own jobs dynamically. I'm going to keep poking at it a bit this weekend and hopefully have something by Monday.

**Comment by mmoayyed** [comment]
@frett how goes the work on 4.2?

**Comment by frett** [comment]
I think I have a solution, testing it out now

**Comment by frett** [comment]
so, the log4j2 native behavior is disabled because we manually disable it here: https://github.com/Jasig/cas/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/web.xml#L9

Any clue why we are currently doing that?

**Comment by mmoayyed** [comment]
Because we want to initialize it ourselves with the our own static binder and log4j wrapper factory. See the CasLoggerFactory. In my initial tests, I did see that even though the initializer is disabled its context listener is correctly added to the context and shuts down all logger threads.

**Comment by frett** [comment]
k, I'll keep debugging after I fix the SAML test for the quartz PR

**Comment by frett** [comment]
I'm still seeing the following errors on stopping the web app:
```
Jan 18, 2016 4:08:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/cas-server-webapp-4.2.0-RC2-SNAPSHOT] appears to have started a thread named [Thread-4] but has failed to stop it. This is very likely to create a memory leak.
Jan 18, 2016 4:08:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/cas-server-webapp-4.2.0-RC2-SNAPSHOT] appears to have started a thread named [Thread-5] but has failed to stop it. This is very likely to create a memory leak.
Jan 18, 2016 4:08:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/cas-server-webapp-4.2.0-RC2-SNAPSHOT] appears to have started a thread named [Log4j2-Log4j2Scheduled-5] but has failed to stop it. This is very likely to create a memory leak.
Jan 18, 2016 4:08:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/cas-server-webapp-4.2.0-RC2-SNAPSHOT] appears to have started a thread named [Log4j2-AsyncLoggerConfig-6] but has failed to stop it. This is very likely to create a memory leak.
```
I haven't had much luck figuring out the cause. I see the `Log4jServletContextListener` correctly loaded and shutting things down, but there still appears to be threads left over from Log4j2.

My current working theory is that Log4j is being initialized once (which starts the threads) and then getting re-initialized when we load up `Log4jServletContextListener` orphaning the previous state and threads.

**Comment by mmoayyed** [comment]
hmmm. 

Let's try this: what happens if you rename all AsyncLogger elements in your log4j2.xml file to just Logger elements? I wonder if we have an issue with AsyncLoggers and disruptor. If that turns out to not recreate the issue, try with AsyncLoggers again but upgrade the version of disruptor to the max available and see what happens.

**Comment by scalding** [comment]
Just a note, thanks for looking into this. I see those sorts of messages, but Tomcat does successfully without resorting to extreme measures (SIGKILL, etc). I think you're heading in the right direction.

**Comment by mmoayyed** [comment]
Also, make sure you don't have the Log4jServletContextListener directly in your web.xml file. I suspect you don't, but let's rule out all other variables. You could also set breakpoints in Log4jServletContextListener and see where the double calls come from if any. I only get to intercept requests once, which tells me it's getting loaded once. Could be log4j2 bug too; let's not rule that out :)

**Comment by mmoayyed** [comment]
OK, so the issue I think is not so much with log4j. Apparently, there are a few background threads that happen to stay alive and don't get shut down correctly somehow, which then in turn keep the log4j threads alive likely because those threads are trying to output logs, or have a reference to loggers, etc. I am trying to determine what those threads are. What might be easiest way to trace that?

**Comment by frett** [comment]
I'm not sure a best course for debugging where those threads are coming from, I've dug around a bit in a heap dump of tomcat after stopping the webapp, but with very limited results.

**Comment by mmoayyed** [comment]
I am going to try and get a thread dump and see what gives. I am suspicious of the JSON service registry watch dog and the ticket registry cleaner threads though I know we changed the latter. A dump would tell me where those threads are; worst case scenario we intercept the context shut down to interrupt all threads.

**Comment by mmoayyed** [comment]
I was able to clean up the remaining threads. The only ones I am seeing that don't shut down now are log4j's for some reason, but I don't think it's that big of a deal at the moment. Might have to report this to log4j and see what might be the problem. 

Pending pull https://github.com/Jasig/cas/issues/1465

**Comment by mmoayyed** [comment]
Log4j issue: https://issues.apache.org/jira/browse/LOG4J2-1259

**Comment by mmoayyed** [comment]
Move to 4.3 for now.

**Comment by frett** [comment]
so, the strategy of interrupting all threads on context shutdown is what I had to do to handle shutdown with the original log4j. the `FileWatchdog` thread it started when monitoring config for changes had no controls to trigger a shutdown.

here's the code I used in case it comes to that to deal with the remaining Log4j2 threads:

```
        // cleanup any remaining threads that don't cleanup after themselves
        for (final Thread thread : Thread.getAllStackTraces().keySet()) {
            // only process threads in the current ClassLoader
            if (TheKeyContextLoaderListener.class.getClassLoader().equals(thread.getContextClassLoader())) {
                // kill Log4j FileWatchdog threads because they won't clean themselves up
                if (thread instanceof FileWatchdog) {
                    thread.stop();
                }
            }
        }
```

**Comment by mmoayyed** [comment]
What is TheKeyContextLoaderListener? is that from Log4j?

**Comment by frett** [comment]
it's my own `ContextLoaderListener`, I just copied some of my own older code for reference :)

I basically used the class loader from the CLL to compare to the class loader for each thread so I would only target threads that belonged to the correct servlet.

**Comment by mmoayyed** [comment]
Interesting, we might be able to do the same. Just need to distinguish other threads from one that belong to CAS. There used to be a safe context loader listener that is now removed.

**Comment by mmoayyed** [comment]
Daniel, would you be able to cook up the same patch for 4.2 and master? You could put the new context listener in webapp-support that extends from the common listener, and on context shutdowns clear all threads. Since you have got the patch already, that might be the easiest route though the key would be to ensure we grab onto the right threads.

**Comment by frett** [comment]
I think we should pursue the proper shutdown for log4j2 threads before we utilize the code I posted to forcibly stop threads. It's a very brute force method of handling those threads and I'm not fully sure if the code would work on other servlet hosting platforms (it really depends on how/if they utilize ClassLoaders for deploying servlets). If we are unable to get any traction on fixing log4j2 shutdown then I'll gladly re-evaluate and put together a patch with the brute force strategy.

**Comment by mmoayyed** [comment]
That's fine. I'd like to resolve this issue before the final GA release, so if log4j2 is unable to provide an adequate response/fix by then, I'd say we go ahead and write our own patch for the time being. You may want to have a pull hanging, just in case.

**Comment by frett** [comment]
alright, I'll try and put the patch together this weekend

**Comment by frett** [comment]
hmm, so the dangling threads are being created after the previous threads are shutdown.

```
2016-01-23 15:10:00,680 INFO [org.jasig.cas.web.util.ShutdownLeakPreventionContextListener] - <Destroying ShutdownLeakPreventionContextListener context...>
2016-01-23 15:10:00,683 ERROR [org.jasig.cas.web.util.ShutdownLeakPreventionContextListener] - <found thread Log4j2-AsyncLoggerConfig-4>
2016-01-23 15:10:00,683 ERROR [org.jasig.cas.web.util.ShutdownLeakPreventionContextListener] - <found thread Log4j2-Log4j2Scheduled-3>
2016-01-23 15:10:00,683 INFO [org.jasig.cas.web.util.ShutdownLeakPreventionContextListener] - <Destroyed ShutdownLeakPreventionContextListener context...>
Jan 23, 2016 3:10:01 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/cas-server-webapp-4.2.0-RC2-SNAPSHOT] appears to have started a thread named [Log4j2-Log4j2Scheduled-5] but has failed to stop it. This is very likely to create a memory leak.
Jan 23, 2016 3:10:01 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/cas-server-webapp-4.2.0-RC2-SNAPSHOT] appears to have started a thread named [Log4j2-AsyncLoggerConfig-6] but has failed to stop it. This is very likely to create a memory leak.
```

the names of the threads are different between when my code runs and when they are reported as leaking. I'm going to try manually setting the listener in web.xml instead of extending `AbstractServletContextInitializer` and see if it changes anything. Maybe something is re-initializing Log4j2 after we shut it down?

**Comment by mmoayyed** [comment]
>Maybe something is re-initializing Log4j2 after we shut it down?

Perhaps there are shutdown hooks in the code that attempts to log data when a component is destroyed/finalized? That might explain the behavior. It would be difficult to trace where those are though.

**Comment by frett** [comment]
That's what I'm thinking is happening, I have an idea of how to address it, just need to find time to poke at it some more.

**Comment by frett** [comment]
Also, I tried defining the shutdown listener directly in the web.XML and threads restart themselves when you kill them, so the bruteforce killing won't solve it this time

**Comment by mmoayyed** [comment]
Perfect. I am thinking we should cut cas 4.2 RC2 by this Friday so if you can figure out what the issue is before then that would be fantastic and then we can include it in the upcoming release candidate.
