### ISSUE TITLE
createRegisteredService Long Javascript interpretation problem - Management webapp

### ISSUE THREAD

**Issue by auvence** [Jasig/cas#1471]
When creating services using the management webapp, the assignedId uses long integers which can be approximated my the browser's Javascript breaking the webapp.

Eg : service created using assignedId 12124814344429407, when calling getServices.html the raw Json has the correct value but the Javascript value is 12124814344429408.

We need to be able to modify the max number that can be generated base on JS capabilities, or parse the Int as a string of characters in the Json so that JS doesn't have to parseInt.

**Comment by frett** [comment]
based on this: http://stackoverflow.com/a/25822886 the limit is +-9007199254740992. Maybe we should treat the assignedId as a string instead of a number in the management UI, I can't think of anything there that would require it to be a number.

**Comment by mmoayyed** [comment]
:+1: on string conversion. @frett you want to take this one?
