### ISSUE TITLE
oAuth does not recognize secret sent from clients using HTTP Basic authentication

### ISSUE THREAD

**Issue by sselaya** [Jasig/cas#1478]
rfc6749 states that the oAuth client "MAY use the HTTP Basic authentication scheme as defined in [RFC2617] to authenticate with the authorization server" yet CAS only recognizes an alternate method requiring the secret to be sent as a GET / POST request parameter.

**Comment by mmoayyed** [comment]
@leleuj What is the impact of this fix? Is this to be handled inside pac4j, or CAS and what would be your estimate to fix this, and timeline of course?

**Comment by leleuj** [comment]
It's a small fix, not related to pac4j, it happens on the access token url where parameters are read "manually". I will do that just after: https://github.com/Jasig/cas/issues/1425

**Comment by mmoayyed** [comment]
Ah gotcha. Sounds simple enough. thanks.

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1515
