### ISSUE TITLE
OAuth2 Refresh Token Support?

### ISSUE THREAD

**Issue by smitchelus** [Jasig/cas#1498]
Hi, I've been looking into the OAuth server support in CAS (http://jasig.github.io/cas/4.1.x/installation/OAuth-OpenId-Authentication.html), and I now have the basic flow working. For our implementation we need to return refresh tokens in addition to the access token. I've been looking through the docs and code, and I don't see how to enable that. 

Is this currently supported? If not, any pointers on how I could extend things to add this support?

**Comment by mmoayyed** [comment]
Refresh tokens are not supported. I'd have @leleuj answer this for you since he's working on adding that kind of support.

**Comment by leleuj** [comment]
This is currently not supported, but I'll be able to add it more easily after: https://github.com/Jasig/cas/pull/1463

**Comment by smitchelus** [comment]
Thanks @leleuj, that's good to know. Hopefully part of this work will be to refactor OAuth20WrapperController and it's collaborators to allow for more granular customization should that be required? Right now I'd have to create a custom version of OAuth20WrapperController and OAuth20AccessTokenController and override handleRequestInternal to make any modifications to the data handed back to the caller.

**Comment by leleuj** [comment]
Exactly, I'm in the process of improving the previous design from 4.2 (`OAuth20WrapperController `), trying to find the right balance between security ensured by pac4j and custom handling of OAuth flows and parameters.

**Comment by smitchelus** [comment]
Great, looking forward to seeing the outcome. Thanks!

**Comment by smitchelus** [comment]
@leleuj, would you refactoring make it easier to provide the access token respose in JSON format? Currently the process is very much hard coded to return content type "text/plain" and the access token/expires values returned in what looks like form encoding. Seems strange to me.

**Comment by leleuj** [comment]
I've seen several ways to return the access tokens: the two main ones are plain/text or JSON. Refactoring will help indeed and this is on my TODO list to allow returning JSON as it will be required for the OpenID Connect protocol. It will be some kind of property to setup.

**Comment by leleuj** [comment]
Here is the PR for review: https://github.com/Jasig/cas/pull/1628

**Comment by leleuj** [comment]
Next step will be the support of JSON in addition of plain text as a response format.

**Comment by smitchelus** [comment]
Looking good! So, the customization hook(s) would be via the AccessTokenFactory /RefreshTokenFactory? I'd also like to be able to hook in my own oauth client (service in CAS terms) database which I imagine means I'll just need to wire in my own services manager?

**Comment by leleuj** [comment]
I din't develop the refresh token support with specific customizations in mind. Components that are meant to be overriden are generally in the `deployerConfigContext.xml` file, which is not really possible here as the OAuth server support is optional.
Though, you can certainly override CAS components by your owns.

**Comment by kunnu** [comment]
Is the same supported for OIDC authentication? Since for OIDC, I am getting refresh_token as null.
