### ISSUE TITLE
SAML NPE for service metadata without NameIDFormat

### ISSUE THREAD

**Issue by frett** [Jasig/cas#1499]
Seeing an NPE when parsing service metadata that doesn't include a `NameIDFormat` tag. from the spec [1]:

```
In the absence of a <saml2p:NameIDPolicy> Format attribute in the Service Provider's
<saml2p:AuthnRequest> message, or a <md:NameIDFormat> element in the Service Provider's
metadata, the Format of the <saml2:NameID> SHOULD be set to
urn:oasis:names:tc:SAML:2.0:nameid-format:transient.
```

NPE occurs here: https://github.com/Jasig/cas/blob/master/cas-server-support-saml-idp/src/main/java/org/jasig/cas/support/saml/web/idp/profile/builders/SamlProfileSamlSubjectBuilder.java#L47

[1] http://saml2int.org/profile/current/#section92

**Comment by hlbraddock** [comment]
+1

**Comment by mmoayyed** [comment]
Ah I see you already pointed to the spec here. Dumb of me to ask again :) Good catch.
