### ISSUE TITLE
Credentials are authenticated twice

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1506]
It appears that credentials during a normal login flow are authenticated twice. Once as part of the submission process and once during the ST generation process. This is seen in 4.2.

**Comment by mmoayyed** [comment]
The fix should also be applied to 4.1

**Comment by frett** [comment]
+1 for 4.1.x, I had noticed this behavior a few weeks ago but wasn't completely sure what need it was addressing there and hadn't taken the time to try and figure out.
