### ISSUE TITLE
externalizing log4j2.xml appears to be broken

### ISSUE THREAD

**Issue by frett** [Jasig/cas#1508]
it appears that CAS is no longer honoring an externalized logging config in 4.3.x. I still need to verify this, but wanted to log it now so it didn't get forgotten.

**Comment by mmoayyed** [comment]
Just making sure, you're seeing this in master correct? 4.2 appears to be functional?

**Comment by frett** [comment]
Yeah, it was noticed on master from our saml work. I was out of the office yesterday and didn't get a chance to directly look into the issue yet

**Comment by frett** [comment]
just confirmed that this isn't firing correctly on a stock build from the current master.

Right now I see a couple issues,
1. `initializeApplicationContext` isn't being called, but `initializeRootApplicationContext` is
2. the `logConfigurationFile` doesn't appear to be correctly configured by spring properties

**Comment by frett** [comment]
I take back issue 2, that is working correctly. but I did discover a different issue in our logging filtering layer with using the new java 8 stream api

**Comment by mmoayyed** [comment]
The two can be consolidated I think. They used to exist when we have multiple app contexts for the webapp and each module, and now that it's just down to 2, I think they can be merged. 

What is the other issue?

**Comment by frett** [comment]
dropping of null bind parameters in log messages, I'm going to fix it along with changing which hook triggers the logging reconfig. I was finally able to poke and prod it a bit so I'll have a PR shortly covering both issues.

**Comment by mmoayyed** [comment]
Perfect. Thanks.
