### ISSUE TITLE
Is possible to make login with a nodejs app in cas server

### ISSUE THREAD

**Issue by augcampos** [Jasig/cas#1517]
I there,
I have a cas server 4.1 and a cas-manager on a Ubuntu machine.
I have a nodejs app that as a login page, can I use the app login page and do login by code, using REST API ou other method?

**Comment by mmoayyed** [comment]
yes you can use the rest api.

**Comment by augcampos** [comment]
I see the info in https://jasig.github.io/cas/4.1.x/protocol/REST-Protocol.html#components

This is an example for CAS-SERVICES is this correct?
1º Request: POST  https://S3:8443/cas/v1/tickets 
                postdata: sername=casuser&password=Mellon&service=https%3A%2F%2FS3%3A8443%2Fcas-services%2Flogin%2Fcas

1º Response: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"><html><head><title>201 Created</title></head><body><h1>TGT Created</h1><form action="https://c3:8443/cas/v1/tickets/TGT-25-ohuGxLKGMWTitkxtufNQ94odOPfvCtUOwbJQV9j7eHq5jctPYb-casc3.example.org" method="POST">Service:<input type="text" name="service" value=""><br><input type="submit" value="Submit"></form></body></html>

2º request: GET  https://S3:8443/cas-services/login/cas?ticket=TGT-25-ohuGxLKGMWTitkxtufNQ94odOPfvCtUOwbJQV9j7eHq5jctPYb-casc3.example.org

2 response
...
<div class="col-sm-12">
    <div id="msg" class="errors">
        <h2>Access Denied</h2>
        <p>You are not authorized to access this resource. Contact your CAS administrator for more info.</p>
    </div>
</div>
...

What I'm doing wrong?
Thanks

**Comment by dima767** [comment]
Please use CAS users mailing list for questions like these.
