### ISSUE TITLE
Resource owner grant type for OAuth support

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1527]

**Comment by leleuj** [comment]
My idea is to secure the /accessToken endpoint with pac4j and accept client credentials authentication (parameters and basic auth): authorization code grant type and user credentials authentication (parameters): resource owner grant type. For that, I first need to create a `DirectFormClient`: https://github.com/pac4j/pac4j/issues/468

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1541

**Comment by mmoayyed** [comment]
Running tests against https://github.com/leleuj/cas-pac4j-oauth-demo and its client, 
I see codes correctly generated with the correct expiration policy. However, I do not see the client making any requests to obtain access tokens. Does your client handle that?

**Comment by mmoayyed** [comment]
My redirect-uri was badly formatted. Resuming tests :)
