### ISSUE TITLE
InitialFlowSetupAction sets wrong cookie path

### ISSUE THREAD

**Issue by philippberger** [Jasig/cas#1531]
The InitialFlowSetupAction sets wrong cookie path for CASTGC. The path ends with "/" but the ticketGrantingTicketCookieGenerator expects no tailing "/". 

The tailing "/" was added due to CAS-972 (https://issues.jasig.org/browse/CAS-972) but the ticketGrantingTicketCookieGenerator.xml left unchanged. This does not make sense to me.

In some cases the CASTG-Cookie can not be found due to the different paths.

CAS Version 4.0.7

**Comment by mmoayyed** [comment]
Trying to understand the issue better: What might those cases be?

**Comment by philippberger** [comment]
We have a custom check for the CASTGC where we use same cookie path as defined in the ticketGrantingTicketCookieGenerator.xml.
Now, as a workaround we use the Spring Bean "ticketGrantingTicketCookieGenerator" and its information to get the correct path as this information is updated by the InitialFlowSetupAction.

**Comment by mmoayyed** [comment]
Good. Could u send a PR to correct the cookie path plz?

**Comment by philippberger** [comment]
Sure. But which is the incorrect path? (I do not want to "reopen" CAS-972)

**Comment by mmoayyed** [comment]
One without the trailing backslash I presume.

**Comment by mmoayyed** [comment]
Let me review this in a little bit.  And get back to u. Not currently at my workstation.

**Comment by mmoayyed** [comment]
in 4.0.7 there is a bug where the cookiepath that is configured in XML config is ignored. We have fixed this in 4.1. I suggest you:

1. Backport the patch from 4.1
2. Submit a PR if you want to.
3. Better yet, upgrade to 4.1.

**Comment by philippberger** [comment]
We are not able to upgrade yet, so I decided to submit a PR (#1536).

**Comment by mmoayyed** [comment]
Very good.
