### ISSUE TITLE
DefaultTicketRegistryCleaner tries to release lock even if it couldn't be acquired

### ISSUE THREAD

**Issue by tjanderss** [Jasig/cas#1538]
I don't think it was meant to work this way? Anyway, the problem is that in the try..catch block of clean() an empty collection of tickets is returned if the lock could not be acquired. That's fine, but eventually the finally -block is always executed and an attempt is made to release the lock even if it wasn't acquired in the first place. CAS version 4.1.4.

    public Collection<Ticket> clean() {
        try {
        	...
            if (!this.lock.acquire()) {
                logger.info("Could not obtain lock.  Aborting cleanup.");
                return Collections.emptyList();
            }
            ...
        } finally {
            logger.debug("Releasing ticket cleanup lock.");
            this.lock.release();
        }
    }

**Comment by mmoayyed** [comment]
This is handled by the Lock implementation directly, if it could not be acquired.
