### ISSUE TITLE
Does Version 4.1.4 work as the CAS Protocol is described?

### ISSUE THREAD

**Issue by augcampos** [Jasig/cas#1539]
Hi there
I try in Advanced Rest Client Application (chrome)
SERVER: https://s3:8443

1º - 
**POST** to https://s3:8443/cas/v1/tickets     
 **Params**: username=casuser&password=Mellon
**RESPONSE**:
`<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"><html><head><title>201 Created</title></head><body><h1>TGT Created</h1><form action="https://s3:8443/cas/v1/tickets/TGT-19-hpJwZhdRRv3xNQPN9cY1TVFLa0Cdoxht4TWgCNaVq2LUuJw6wX-cas.example.org" method="POST">Service:<input type="text" name="service" value=""><br><input type="submit" value="Submit"></form></body></html>`

2º
**POST** to https://s3:8443/cas/v1/tickets/TGT-19-hpJwZhdRRv3xNQPN9cY1TVFLa0Cdoxht4TWgCNaVq2LUuJw6wX-cas.example.org
  **Params**: service=http%3A%2F%2Fs3%2Fapp%2F%23%2Fapp%2Flogin
**RESPONSE**:
ST-36-goRfuh15q1My21KCWcIB-cas.example.org

3º
**POST** to https://s3:8443/cas/serviceValidate
 **Params**: service=http%3A%2F%2Fs3%2Fapp%2F%23%2Fapp%2Flogin&ticket=goRfuh15q1My21KCWcIB-cas.example.org
**RESPONSE**:
`<cas:serviceResponse>
<cas:authenticationFailure code="INVALID_TICKET">Ticket 'ST-36-goRfuh15q1My21KCWcIB-cas.example.org' not recognized</cas:authenticationFailure>
</cas:serviceResponse>`

I already try several types and I do not work. Can some one please tell me what I'm doing wrong?

Thanks

**Comment by mmoayyed** [comment]
Your ticket is expiring. Look into your server logs and you will see why.
