### ISSUE TITLE
Default OAuth 2.0 Callback service does not define a AttributeReleasePolicy leading to an error when trying to get user profile attributes

### ISSUE THREAD

**Issue by ardias** [Jasig/cas#1546]
Version used: 4.2.0 RC2

When adding support for oauth by adding the cas-server-support-oauth dependency to the cas-overlay project, there is a default callback service registered in WEB-INF/classes/services. This service does not define a 'attributeReleasePolicy' so whe using the 'profile' endpoint to retrieve user attributes the reponse is always the
 error:

{"id":"casuser","attributes":[{"error":"invalid_request. null"}]}

Example default file generated:
[OAuthCallbackurl-10785150082049.json.txt](https://github.com/Jasig/cas/files/130579/OAuthCallbackurl-10785150082049.json.txt)

**Comment by leleuj** [comment]
Indeed, there is a problem but not the expected one. The callback service should never be used to get user attributes, the provided service is the one that needs to attached to the access token.

It's a lot easier in the master, due to the refactoring.

**Comment by leleuj** [comment]
PR for 4.2.x: https://github.com/Jasig/cas/pull/1547

**Comment by ardias** [comment]
Makes sense. Thanks
