### ISSUE TITLE
OpenId impl in non-association mode must verify the request

### ISSUE THREAD

**Issue by ardias** [Jasig/cas#1550]
The client does a verify when it's in association mode. When it's not is association mode, the client has to send a verification request to the server. 
http://openid.net/specs/openid-authentication-2 0.html#verification (section 11.4.2)

**Comment by mmoayyed** [comment]
Does your change also work correctly when doing the opposite? Stateless associations work correctly? If so, sure. Please submit a pull request.

**Comment by ardias** [comment]
Haven't tried, sorry. I'll try to test it and if i can i'll do the PR.

**Comment by ardias** [comment]
Ok, so from a bit of debugging, at least in this branch, the Stateless mode is not supported.
I could taht see in OpenIdCredentialsAuthenticationHandler the authenticate method returns success, as well as the PolicyBasedAuthenticationManager. The problem is that the OpenIdServiceResponseBuilder always looks for an association (an association handle to be more precise) and since there's no association (the assoc_handle is not present) then it responds with an authentication failure.

Per the OpenId 2.0 spec, the assoc_handle is optional. 
Maybe when building the response we should skip the association validation if it's not present and just validate the Ticket?

**Comment by mmoayyed** [comment]
The branch you are looking at and reviewing is the same as what's in master and 4.1. At least the core functionality is the same. 

So as you note, the bug is that the response builder should really consider that association as an optional. As you say, if not present, we could skip and let it proceed.

**Comment by ardias** [comment]
I think so. I tried a quick "hack" and skipped the association check if not present and it works. Now i just need to try the server verification of the response as the local verification fails in this mode.

**Comment by mmoayyed** [comment]
Any updates on this?

**Comment by ardias** [comment]
Haven't had the time to test the server verification. But i would say skipping the association check when there's no association is working. I do not know the security implications of removing this check. Someone that developed the OpenId support might have important input in this case

**Comment by mmoayyed** [comment]
Could I ask you to post your patch here so we can review? or better yet publish a pull? 

One possibility might be to keep the default behavior, but allow the skipping of association only if an option is set to do so in cas.properties.

**Comment by ardias** [comment]
Ok, let me see if i can do a PR during today.

**Comment by ardias** [comment]
I have another update on the issue. The server verification of the authentication response also fails with the default configuration parameters, ie., the successful  authentication response returns the CAS service ticket. this ticket is then used to verify the authentication response, but by default the ticket is configured to one-time use only, so the verification fails.
Changing the configuration to allow the service ticket to be used more than once (i changed to 2 times) fixes this issue and the verification succeeds.
Once again i'm not fully aware of the security implications of making this change. At first glance it seems to be a low-risk change but leaving this to a configuration change in cas.properties seems a bit obscure.

**Comment by mmoayyed** [comment]
Service tickets should always be used once; adjusting the config to allow anything more than is a big security risk. 

The only way the verification would fail is if the ticket is used somehow prior to the validation call. Where and when is that?

**Comment by ardias** [comment]
It's used in the authentication step. The service ticket then it's returned to the RP that sends it again to the OP (cas server) for verification of the authentication response and it fails because the ticket was already used.
I believe it's because the Service Ticket is used in the redirect to the 'login page' in the authentication phase, and then it's reused for the verification phase. 
Maybe after the successful authentication step CAS could generate another service ticket and return that one to the RP (client) so that the verification step used the new service ticket instead of the expired one.
But this is a bit over my head. I'm not familiar enough with the code base to fix this.

**Comment by mmoayyed** [comment]
That doesnt make sense. You should only get a service ticket AFTER you have authenticated. There should be no service ticket sent to the login page. I'd have to see your configuration, but likely, there is something missing.

**Comment by ardias** [comment]
Yes, and you do only have a service ticket after authentication. But when building the open id response in OpenIdServiceResponseBuilder, the service ticktet is validated  to get the assertion. This makes the service ticket expire (based on usage count).
On the verification step, after the authentication, the OpenIdValidateController  delegates to the AbstractServiceValidateController and the service ticket is validated again. Since the ticket is expired an exception is thrown and the verification fails.
Now, the 'double' verification of the service ticket happens because i explicitly changed the code to allow for stateless mode, ie, allow the service ticket validation even if there's no association.
If i remove that change, then stateless mode doesn't work. If i keep the change stateless mode 'works'  until the verification step when the service ticket is validated again and fails due to expiration.

**Comment by mmoayyed** [comment]
Understood. Thanks. Post your patch somewhere and we'll continue working on a solution.

**Comment by mmoayyed** [comment]
Updated issue description.

**Comment by mmoayyed** [comment]
Quick ping. @ardias

**Comment by ardias** [comment]
Hey, sorry, i haven't been able to progress much. I'm in the process of changing jobs so it's been complicated. I'll try to take a stab at it in the weekend

**Comment by mmoayyed** [comment]
No problem. Thanks, and good luck to you. Hope you don't mind the occasional ping. :)

**Comment by ardias** [comment]
Hey @mmoayyed , so i was looking to try and implement something this weekend but I'm having trouble getting things to work as before. I saw there were some changes to the configuration and now OpenId responses are failing (with a missing parameter error). I tracked it down a problem with the class OpenIdConfiguration. The class for some reason is not picking up the value for the property 'endpoint' so it builds a ServerManager with the property set to null. This causes the 'missing parameter error' alter on.
Can you check what might be causing it to not pick up the value. I compared it to the OAuthConfiguration class which also has a similar property, and it works in OAuth module but not in the OpenId module. Couldn't figure out why.

**Comment by mmoayyed** [comment]
Sure. I'll let you know shortly. Thanks for getting back to me.

**Comment by mmoayyed** [comment]
@ardias Reorganize that configuration class to be more like:

```java
@Configuration("openidConfiguration")
public class OpenIdConfiguration {
    private static final Logger LOGGER = LoggerFactory.getLogger(OpenIdConfiguration.class);
    
    /**
     * The Endpoint.
     */
    @Value("${server.prefix:http://localhost:8080/cas}/login")
    private String endpoint;
        
    /**
     * The Enforce rp id.
     */
    @Value("${cas.openid.enforce.rpid:false}")
    private boolean enforceRpId;
    
    /**
     * The Smart open id association controller.
     */
    @Autowired
    @Qualifier("smartOpenIdAssociationController")
    private AbstractDelegateController smartOpenIdAssociationController;

    /**
     * The Open id validate controller.
     */
    @Autowired
    @Qualifier("openIdValidateController")
    private AbstractDelegateController openIdValidateController;

    /**
     * Cas open id service failure view jstl view.
     *
     * @return the jstl view
     */
    @Bean(name="casOpenIdServiceFailureView")
    public JstlView casOpenIdServiceFailureView() {
        return new JstlView("/WEB-INF/view/jsp/protocol/openid/casOpenIdServiceFailureView.jsp");
    }

    /**
     * Cas open id service success view jstl view.
     *
     * @return the jstl view
     */
    @Bean(name="casOpenIdServiceSuccessView")
    public JstlView casOpenIdServiceSuccessView() {
        return new JstlView("/WEB-INF/view/jsp/protocol/openid/casOpenIdServiceSuccessView.jsp");
    }

    /**
     * Cas open id association failure view jstl view.
     *
     * @return the jstl view
     */
    @Bean(name="casOpenIdAssociationFailureView")
    public JstlView casOpenIdAssociationFailureView() {
        return new JstlView("/WEB-INF/view/jsp/protocol/openid/casOpenIdAssociationFailureView.jsp");
    }

    /**
     * Cas open id association success view jstl view.
     *
     * @return the jstl view
     */
    @Bean(name="casOpenIdAssociationSuccessView")
    public JstlView casOpenIdAssociationSuccessView() {
        return new JstlView("/WEB-INF/view/jsp/protocol/openid/casOpenIdAssociationSuccessView.jsp");
    }

    /**
     * Open id provider view jstl view.
     *
     * @return the jstl view
     */
    @Bean(name="openIdProviderView")
    public JstlView openIdProviderView() {
        return new JstlView("/WEB-INF/view/jsp/protocol/openid/user.jsp");
    }

    /**
     * Openid delegating controller delegating controller.
     *
     * @return the delegating controller
     */
    @Bean(name="openidDelegatingController")
    public DelegatingController openidDelegatingController() {
        final DelegatingController controller = new DelegatingController();
        controller.setDelegates(Arrays.asList(this.smartOpenIdAssociationController, 
                this.openIdValidateController));
        return controller;
    }

    /**
     * Server manager server manager.
     *
     * @return the server manager
     */
    @Bean(name="serverManager")
    public ServerManager serverManager() {
        final ServerManager manager = new ServerManager();
        manager.setOPEndpointUrl(this.endpoint);
        manager.setEnforceRpId(this.enforceRpId);
        LOGGER.info("Creating openid server manager with OP endpoint {}", this.endpoint);
        return manager;
    }
}
```

**Comment by ardias** [comment]
I had already tried to put a 'default value' and it still doesn't work. I added the logging statement and what i get is:
2016-03-07 11:29:04,292 INFO [org.jasig.cas.config.OpenIdConfiguration] - <Creating openid server manager with OP endpoint null>
The strange thing is that in the OAuthConfiguration class the proeprty value injection works (casLoginUrl for example has a correct value) but no in the OpenIdConfiguration.
It seems like the SpringPropertyPlaceholder is not processing the OpenIdConfiguration class. I have a suspicion that it might be related to the time when the class is being instantiated. Maybe it's before spring has had time to instantiate the property sources or something.
I'm going to do some more debugging to try and find the reason for this

**Comment by ardias** [comment]
Ok, so status update.
It seems that in OpenIdConfiguration having the smartOpenidAssocationController as a 'lazy' dependency (with the autowired annotation) and the ServerManager also as a Autowired dependency is making Spring instantiate the ServerManager before processing the Value annotations, or is instantiating it outside of the context, or in some other context (not completely sure about this).
If i make the smartOpenIdAssocationController non-lazy, using an instantiation method, then the ServerManager is instantiated correctly , either inside the context, or after spring processes the Value annotations. Either way, it fixes the issue.
Check the [commit](https://github.com/ardias/cas/commit/47de56a020fbd59a1d903d16392ab66aa9dd28da) and if you're ok with it i'll send a PR later.

Just a suggestion also: Maybe changing dependencies injection to Constructor injection with help with some of these issues. I used to be a fan of the Autowired properties but it hides a lot of information about dependencies and also makes simple testing a bit harder imho.

**Comment by dima767** [comment]
Good point on the constructor injection points. +1 on that - wherever
practical

**Comment by mmoayyed** [comment]
Reviewed. Your patch is perfectly fine. I am all for ctor injections, as long as that's not the only option for injecting dependencies.

**Comment by ardias** [comment]
@mmoayyed  So i took a stab at implementing the signature verification on the server. I re-used the OpenIdValidateController for that.
Can you take a look at the [commit](https://github.com/ardias/cas/tree/20dbf94d2e9097a1f868a3af0bcf9362a0c7b697) before i make the PR?

**Comment by mmoayyed** [comment]
Reviewed. Looks good.
