### ISSUE TITLE
TokenAuthenticationHandler.getRegisteredServiceJwtSigningSecret method does not retrieve the correct property

### ISSUE THREAD

**Issue by rafamarquezv** [Jasig/cas#1555]
- CAS server version: cas-4.2.0-RC2
- Container type/version: apache-tomee-jaxrs-1.7.3
- Project: cas-server-support-token
- Class: TokenAuthenticationHandler
- Method: getRegisteredServiceJwtSigningSecret
- Line: 82

**Description**: 
_This method is supposed to return 'signing secret' value but it is returning 'encryption secret' because when using TokenConstants object it uses TokenConstants.PROPERTY_NAME_TOKEN_SECRET_ENCRYPTION instead of TokenConstants.PROPERTY_NAME_TOKEN_SECRET_SIGNING._

**Comment by mmoayyed** [comment]
Thanks for the report. Would you be able to submit a patch? I imagine it's a trivial fix.

**Comment by mmoayyed** [comment]
You're perfectly right. This line needs to be changed:
https://github.com/Jasig/cas/blob/master/cas-server-support-token/src/main/java/org/jasig/cas/authentication/handler/support/TokenAuthenticationHandler.java#L81

**Comment by rafamarquezv** [comment]
You are welcome! Sure I'll submit a patch.

**Comment by mmoayyed** [comment]
Fantastic.

**Comment by rafamarquezv** [comment]
Hi, I have seen that in the same class 'TokenAuthenticationHandler' (Line 42) on 'getAuthenticator' method, to set 'encryptionSecret' it is also calling 'getRegisteredServiceJwtSigningSecret' when it should call 'getRegisteredServiceJwtEncryptionSecret'. I am fixing that too.

**Comment by rafamarquezv** [comment]
Hi, it's done on waiting PR: https://github.com/Jasig/cas/pull/1558
