### ISSUE TITLE
Leverage @Configuration to construct CAS application context

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1566]
Allow the cas application context to use @Configuration and @Bean annotations. This has a number of advantages:

1. Less XML noise and easier overlay configuration
2. Allows beans to dynamically and conditionally be configured based on properties
3. Properties can later be used to dynamically reload the application context via @RefreshScope
4. Allows more aspects of CAS components to be customizable via making more properties available.

The primary driver is #3, make sure the context can become fully reloadable via something like spring-cloud-config. We should prep the codebase to allow that to happen in future versions.

**Comment by mmoayyed** [comment]
Note that most if not all @Component annotations need to turn into valid @Bean definitions as well, so properties can be injected later on for the bean to reload itself.

**Comment by dima767** [comment]
Good call on @Configuration style. Here's a small example of the power the
Javaconfig could bring:
https://github.com/Jasig/cas/blob/master/cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/config/HazelcastInstanceConfiguration.java
