### ISSUE TITLE
Ticket data in 10 w when using mysql management level, there will be a cas necrosis

### ISSUE THREAD

**Issue by arleylee0702** [Jasig/cas#1569]
cas version ： 3.5.2  
container    ：tomcat 7
problem      ： 
By cas ticket using mysql management, in the ticket data reaches more than 10 w level, every day timer when cleaning out the ticket.Code ticketRegistryCleaner contact is a direct ticket all data in the table (the.findall) do expired, lead to memory leaks, program is not available.I have to clean the overdue ticket to improve page composition form.That solved the problem

**Comment by mmoayyed** [comment]
Yes. Known issue. Note that CAS3 is EOL. Your first solution is to upgrade.
