### ISSUE TITLE
Support Spring Security's PasswordEncoder component

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1578]
CAS clients provided by frameworks that rely on Spring Security usually leverage the built-in Spring Security PasswordEncoder. It will be useful to wrap that component into a CAS password encoder so SpringSec can be used in authN handlers for passing encoding.

**Comment by joemccall86** [comment]
Currently there's no hard dependency on Spring Security in `cas-server-core-authentication`. The way I see it there are two options:

1.) Introduce the dependency.
2.) Rely on reflection to call .encode() and .matches() from an arbitrary object provided by the user. The reflection will happen in afterPropertiesSet() at runtime to fail fast.

Thoughts/preferences?

**Comment by mmoayyed** [comment]
Introduce the dependency, mark it as provided. Exclude all transitive dependencies and conflicts.
