### ISSUE TITLE
TicketRegistry timeouts are hardwired to assume ST and TGT expiration policy timeouts

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1580]
CAS ticket registries are used to store more than just TGTs and STs. They also store PTs and PGTs as well as OAuth Codes and Access Tokens, and potentially more in the future. 

Most ticket registries are wired to setup backend storage (i.e. cache) services for TGTs and STs. Since all other ticket types are an extension of these two types, storage services accept and process them. 

However, the cache that is set up itself is wired to use the timeout policies of STs and TGTs for idle timeouts or hard timeouts. These timeout values will not work when dealing with PGTs and OAuth codes, etc. The cache need not be directly constructed via ST and TGT timeouts. The cache must be independent of those values, allowing perhaps for a wider range of timeouts so that CAS expiration policies for tickets can operate with that range, and be allowed to determine which ticket needs expiring.

**Comment by mmoayyed** [comment]
So I think one possible solution to this problem would be divorce the timeout properties for each cache from ST/TGT timesout via pure config. For instance, ehcache would have "ehcache.all.things.service" and "ehcache.all.things.sso" props which could have each cache live longer than the normal ST and TGT policies, slightly longer. Then CAS would be able to calculate expiration off the ticket expiration policy rather than relying on the cache itself, and the cleaner would start auto cleaning based on the same logic.

**Comment by dima767** [comment]
Perhaps somewhat related, but a more general architectural idea: create a "registry" abstraction for each type of tokens managed by CAS server? i.e. TgtRegistry, StRegistry, PgtRegistry, OauthTokenRegistry, etc. That might sound like an overkill, but would give clear separation of responsibilities of these storage abstractions dealing with specific types of items. I could imagine a general parameterized type like TokenRegistry<T> and each concrete extension of that with new concrete type param, etc.

**Comment by dima767** [comment]
`TokenRegistry<T>` that is

**Comment by mmoayyed** [comment]
That sounds like a very attractive option; one that we might even be able to attack for 4.4 or even 5 perhaps. It sounds like we might also need a façade of some sort, to hold various instances of ticket registry types, and then plug in the façade to all components that today expect just a TicketRegistry. Similar thing we do today with the authN support system. 

I can think of a few side effects here, but we'll likely need to prototype this out to see what and how it looks like.

**Comment by mmoayyed** [comment]
An easy solution for the time being would be to construct the cache without any sort of timeout value for hard/idle timeouts. Let the cache keep items as long CAS needs to be available. And, let the CAS ticket cleaner process  the cache to clean up entries. (The cleaner runs for all cache instances rather than just the default or the JPA one) This achieves a number of things:

1. Less confusion for the deployer to understand the difference between CAS timeout vs Cache timeout.
2. Less configuration for us. In fact, nothing changes!
3. Prohibits misconfiguration for the deployer: If you configure your cache timeout to be quicker than the CAS timeout, weird stuff happens. Objects end up removed, while CAS still expects them to be there. 

Potentially though, there are side effects to this approach. Performance and memory alloc for one. A none ephemeral cache, hanging around JVM for long periods of time for all token types could lead to very very bad performance. Not sure. Must test this too.

**Comment by dima767** [comment]
I'm not sure I'm personally a big fan of a separate "one size fits all"
cleaner approach. I'd rather us not spend time implementing low level
infrastructure code, but rather solve the domain problems of SSO, authn,
authz, etc. and let the software that does it best deal with these low
level problems. For instance, in Hazelcast case, you define the lifetime of
the item in its cache "jit" style, right at the time of when you put
objects in cache, utilizing native CAS tickets timeout settings. No
problems not confusions there.

Again, cleaner might be needed, but only for "not capable" implementations.

D.

**Comment by dima767** [comment]
So, if anything, I'd introduce `ExternallyCleanable` abstraction and let
registries that wish to let Cleaner take care of the cleaning job implement
it, or something like that

**Comment by mmoayyed** [comment]
>For instance, in Hazelcast case, you define the lifetime of
the item in its cache "jit" style, right at the time of when you put
objects in cache, utilizing native CAS tickets timeout settings. No
problems not confusions there.

But there is. That is the exact problem we are trying to solve. The objects you put into the registry cache only apply today to the statically configured policy for STs and TGTs. The registry today does not just apply to STs and TGTs. So if you decided to, for instance, keep your OAuth codes longer than 10 seconds, or if you decided to keep your PGTs longer than than the default policy, the implementation today is completely broken. The oauth code will be gone at 10 seconds, regardless what you decided for oauth code's expiration policy. The solution would be to modify the ST timeout for the cache and keep growing it to match various CAS policy config, which is effectively the same solution as I proposed. You need to keep the cache large enough to account for all kinds of policies. 

So unless you dig deeper, there is no way you can get around the problem by simply trusting the framework. Now, we could break the registry into multiple smaller registry types, dedicated for each object. A one-to-one mapping of registry->objectType. That's way more complicated, plus you have to account for replication issues.

The cleaner is also required for a number of reasons:

1. The cleaner handles backchannel SLO. If a cache does automatic cleanup, SLO is completely broken. So not a desirable behavior.
2. There have been many reports where the automatic cleanup configuration of the technology does not do what it should. Objects tend to stick around longer than needed cache.

**Comment by mmoayyed** [comment]
Also note that each registry of today is able to override the cleaner policy. That is already handled, but not something you would want a registry instance to do, I don't think. You want the cleaner to run and behave the same for all registry types, so you can control how and when each object is removed based on the object's dedicated expiration policy, and not the cache's.

**Comment by mmoayyed** [comment]
Thought about this some more; another possible option would be that we expose the expiration policy object for every ticket type in the API. So we'd have something like `ticket.getExpirationPolicy()`. This is only now exposed in impl classes of the ticket API. 

Once we have access to the expiration policy, each registry would then use the policy of the ticket to store that object into cache, rather than what's statically injected into the registry at runtime. 

However, that still does not solve the problem of the cache policy itself. Still, the cache timeout policy needs to be large enough to last longer than the CAS ticket expiration policy. (Similar to the default ticket registry where items tend to last forever until a restart). Once it's able to handle all kinds of timeouts, we could then dynamically start storing objects into various caches based on the item policy of the ticket itself, and not the cache's.

**Comment by mmoayyed** [comment]
Initial scan shows that out of all registry types we support, only ehcache and ignite keep separate caches for STs and TGTs, while every other cache/registry option uses a single cache instance to store various ticket types. So as a first step, it would possible be practical to change those 2 impls to use a single cache instance for everything, similar to Hazelcast and others. There is not much difference between the two cache instances; Ehcache for instance only differs in terms of its replicator, and everything else can be consolidated.

**Comment by dima767** [comment]
+1 on enhancing the Ticket API with an expiration policy, besides, the
expiration policy IS a part of Ticket abstraction naturally.

But as I mentioned previously, down the road it will make much sense to
create a higher level of `Token` abstraction, with generified
`TokenRegistry<T>` parameterized with concrete token types e.g.
`TokenRegistry<TicketGrantingTicket>, TokenRegistry<OauthToken>` etc. Down
the road...

**Comment by mmoayyed** [comment]
Agreed. Sure. I'll create a separate issue to track the refactoring effort.
