### ISSUE TITLE
Handle TGC generation at runtime or via the maven overlay build?

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1584]
There are certain TGC keys in cas.properties that are used for cookie encryption. Adopters are expected to generate new keys, but may forget to do so, or not care wrongly, as they are there by default defined to some static keys. Possible options around this issue:

1. Expect adopters to generate keys, and leave the keys blank. Build an approach into the overlay or something else that allows adopters to build keys at build-time. 
2. Leave the keys blank by default. If blank, generate them automatically at runtime. Otherwise, use what's there and validate. This approach is problematic when dealing with multi-node CAS deployments, because every node could potentially end up creating different keys. 
3. Same as #2, but generate a WARN entry in the logs noting the caveat.

**Comment by frett** [comment]
We may want to also apply this to the webflow session encryption secret key as well.

**Comment by mmoayyed** [comment]
Good point. Sure. I'll cook up something. 

I am more inclined to auto-gen it, but issue a warning. We should also have instructions on how to generate it. It's simple, but may be hard to find it for non-devs.

**Comment by mmoayyed** [comment]
Guess this might work: generate the key, WARN, and also output the generated keys saying: you should really copy this to all nodes if you are in HA. 

I noticed boot does similar things when it wants to secure endpoints via basic authn. It generates a password and outputs that into logs for u to use. Same sort of idea.
