### ISSUE TITLE
Expiration policy timeouts specified using @Value annotations overflow in some cases

### ISSUE THREAD

**Issue by aukevanleeuwen** [Jasig/cas#1599]
If you are specifying values of over (roughly) 24 days in seconds (in cas.properties) the expressions

    /** Maximum time this ticket is valid.  */
    @Value("#{${tgt.maxTimeToLiveInSeconds:28800}*1000}")
    private long maxTimeToLiveInMilliSeconds;

will result in negative integer values being assigned to the long fields. So in `cas.properties`:

    # (1) does not work, overflows to negative integer
    tgt.maxTimeToLiveInSeconds=7776000

    # (2) works
    tgt.maxTimeToLiveInSeconds=7776000L

This is unexpected for the end user, since it immediately invalidates his just created tickets most of the time.

**Comment by dima767** [comment]
This needs to be very clearly documented (the long 'L') postfix semantics,
since we are dealing with longs and Java's implicit integer conversions,
etc. 'L' postfix in these config values must always be required!

**Comment by aukevanleeuwen** [comment]
@dima767 well that should not be necessary anymore (if you merge the PR) since I'm forcing the expression to be calculated using longs by postfixing the 1000 with an L instead. If one of the two operands is a long the result will also be a long.

**Comment by aukevanleeuwen** [comment]
The PR is merged, should I close the issue?

**Comment by mmoayyed** [comment]
Yes please.
