### ISSUE TITLE
Warnings in log due to @Metered / @Timed / @Counted annotations

### ISSUE THREAD

**Issue by aukevanleeuwen** [Jasig/cas#1605]
Ticket created based on comment from Misagh Moayyed [here](https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/hdyecxeA9LE):

On 4.2.0-RC3 I have the following warnings in my log:

```
08.03.2016 08:37:42 WARN  [com.ryantenney.metrics.spring.AnnotationFilter] Ignoring @Metered on method org.jasig.cas.AbstractCentralAuthenticationService.getTicket due to illegal modifiers: final
08.03.2016 08:37:42 WARN  [com.ryantenney.metrics.spring.AnnotationFilter] Ignoring @Metered on method org.jasig.cas.AbstractCentralAuthenticationService.getTickets due to illegal modifiers: final
08.03.2016 08:37:42 WARN  [com.ryantenney.metrics.spring.AnnotationFilter] Ignoring @Timed on method org.jasig.cas.AbstractCentralAuthenticationService.getTicket due to illegal modifiers: final
08.03.2016 08:37:42 WARN  [com.ryantenney.metrics.spring.AnnotationFilter] Ignoring @Timed on method org.jasig.cas.AbstractCentralAuthenticationService.getTickets due to illegal modifiers: final
08.03.2016 08:37:42 WARN  [com.ryantenney.metrics.spring.AnnotationFilter] Ignoring @Counted on method org.jasig.cas.AbstractCentralAuthenticationService.getTicket due to illegal modifiers: final
08.03.2016 08:37:42 WARN  [com.ryantenney.metrics.spring.AnnotationFilter] Ignoring @Counted on method org.jasig.cas.AbstractCentralAuthenticationService.getTickets due to illegal modifiers: final
```

Looks like a bug (although it's being ignored).

**Comment by mmoayyed** [comment]
Thanks for the report. It's not a bug per se as you note, but it's certainly annoying. We'll need them moved around. (I am not seeing this on master by the way. Looks like we somehow at some point took care of this)

**Comment by mmoayyed** [comment]
Going to classify this as a bug nonetheless.

**Comment by mmoayyed** [comment]
by the way might I interest you to pick this up and issue a PR? Should finals be removed or could we move them somewhere else that might make better sense?

**Comment by aukevanleeuwen** [comment]
I'm sorry but I wont be able to do that in the near future. It's not that important (to me) anyway for the 4.2.0 release either. That's why I initially posted it o the user list, just so it could be fixed at some point in time.

**Comment by mmoayyed** [comment]
No worries. I might be able to take a pass at this today.
