### ISSUE TITLE
Grant ST always fails when ssoEnabled flag is unset

### ISSUE THREAD

**Issue by dima767** [Jasig/cas#1610]
1. CAS server version: 4.1.5
2. Container type/version (Tomcat, Jetty, etc): Any
3. Steps to duplicate the problem: In the service registry set `ssoEnabled` flag to `false`

This is a regression bug introduced by fixing an unnecessary second authentication transaction during an issuance of a service ticket. The exact place where ST creation would ALWAYS fail for a perfectly valid authenticated principal when the `ssoEnabled` flag is unset is here: https://github.com/Jasig/cas/blob/v4.1.5/cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java#L259

Obviously the entire authentication logic in this method is a leftover from the previous design and needs to be re-thought or removed entirely here.

**Comment by mmoayyed** [comment]
Reviewing this tomorrow. Likely, needs to be ported fwd to all branches.
