### ISSUE TITLE
Interval (or the log message) of job in JpaTicketRegistry is not correct

### ISSUE THREAD

**Issue by aukevanleeuwen** [Jasig/cas#1613]
1. CAS 4.2.0-RC3
2. Tomcat

In the 4.2.x branch there is something similar in the setup of the job going on  as in this issue  #1608.

https://github.com/Jasig/cas/blob/0758488a037bf9e9574d192bd9a46bded83dd03b/cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java#L252 

    /**
     * Schedule reloader job.
     */
    @PostConstruct
    public void scheduleCleanerJob() {
        try {
            if (shouldScheduleCleanerJob()) {
                logger.info("Preparing to schedule cleaner job");

                final JobDetail job = JobBuilder.newJob(this.getClass())
                    .withIdentity(this.getClass().getSimpleName().concat(UUID.randomUUID().toString()))
                    .build();

                final Trigger trigger = TriggerBuilder.newTrigger()
                    .withIdentity(this.getClass().getSimpleName().concat(UUID.randomUUID().toString()))
                    .startAt(DateTime.now().plusSeconds(this.startDelay).toDate())
                    .withSchedule(SimpleScheduleBuilder.simpleSchedule()
                        .withIntervalInSeconds(this.refreshInterval)
                        .repeatForever()).build();

                logger.debug("Scheduling {} job", this.getClass().getName());
                scheduler.scheduleJob(job, trigger);
                logger.info("{} will clean tickets every {} seconds",
                    this.getClass().getSimpleName(),
                    TimeUnit.MILLISECONDS.toSeconds(this.refreshInterval));
            }
        } catch (final Exception e){
            logger.warn(e.getMessage(), e);
        }
    }

One line says: `.withIntervalInSeconds(this.refreshInterval)`, the logging line says: `TimeUnit.MILLISECONDS.toSeconds(this.refreshInterval))`. This case I'm not such which of the two is meant though, because running it every 5 seconds by default might be a bit steep? So no PR this time

**Comment by mmoayyed** [comment]
We probably want the value to be consistent across all. I think it is assumed to be in seconds, so let's make sure it is properly logged as seconds. If you need a better interval, you can always change the prop key.

**Comment by aukevanleeuwen** [comment]
Seconds is probably logical for a job like this (you don't want to run it multiple times per second I suppose), however the default is a bit weird for second: it will run every 1 hour 23 minutes and 20 second. Since that seemed a bit weird to me I didn't issue a PR.

**Comment by mmoayyed** [comment]
Yes. That needs changing. So here is a suggestion: start up delay, 20 seconds. Refresh interval: 5 minutes.

**Comment by aukevanleeuwen** [comment]
Fixed as suggested.
