### ISSUE TITLE
Consider renaming 4.3 release to 5.0

### ISSUE THREAD

**Issue by dima767** [Jasig/cas#1616]
With a pretty dramatic configuration style change, big decoupling of authentication and sso subsystems and introduction of authentication transaction API, building on top of Spring Boot, etc. several core API changes e.g. changing ticket counter API from `int` to `long`, inclusion of the multifactor authentication subsystem, IMHO it would be appropriate to designate `4.3` release as a `5.0`.

This issue could be the channel to track and discuss...

**Comment by leleuj** [comment]
That's fair: 4.3 consists of many huge changes, but so was 4.2 (with full automatic configuration).

**Comment by dima767** [comment]
wrt full automatic config - the current master goes even further with Spring Boot style config, many API changes, inclusion of mfa subsystem (which is huge), API changes, inclusion of OIDC, SAML Web SSO profile impls, etc. etc. It'd be nice to enumerate most of the big changes here, so it's apparent that it's time for 5.0 ;-) I'll see what I could do to list them here...

**Comment by dima767** [comment]
Well, to be fair - Spring Boot is not in the master yet, but looks like it's going pretty well and will be at some point ;-)

**Comment by dima767** [comment]
OK big items justifying major 5.0 release designation:

* Java 8 (language features and APIs) - requiring min. version of Java 8 to run CAS server
* Overhaul of configuration with Spring JavaConfig model
* Redesign of Authentication API and de-coupling it from web SSO subsystem
* Native MFA subsystem
* Addition of risk-based authn. components
* Various core API changes (due to Java 8 - like ticket counter return type and usage of new java.time.* API)
* Build on Spring Boot (coming up)
* Replacement of a view layer (from JSP to Thymeleaf) (coming up)

... to name a few

**Comment by frett** [comment]
I'm in favor of the 5.0 tag because it is quite a large set of changes that will affect deployer overlays and it should be reflected in in our versioning.

**Comment by mmoayyed** [comment]
:+1:

**Comment by mmoayyed** [comment]
I think we are all in agreement on this. Any nays before we change milestone dates and schedules? 

Also @dima767 would you want to scan the code to change @since tags from 4.3 to 5? I should likely do this on the MFA branch and the boot stuff as well. Then we should be able to close this issue.

**Comment by dima767** [comment]
I could try. Any advice on how to better (more efficiently) accomplish this?
Some IntelliJ IDEA trickery perhaps?

On Tue, Mar 15, 2016 at 04:38, Misagh Moayyed <notifications@github.com> wrote:
I think we are all in agreement on this. Any nays before we change milestone
dates and schedules?

Also @dima767 [https://github.com/dima767] would you want to scan the code to change @since [https://github.com/since] tags from 4.3 to 5? I should likely do this on the MFA branch and the boot
stuff as well. Then we should be able to close this issue.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/Jasig/cas/issues/1616#issuecomment-196720292
[https://github.com/Jasig/cas/issues/1616#issuecomment-196720292][https://github.com/notifications/beacon/AAAxVTnrej5AACuwcxLpFokZm8X3WMNPks5ptnASgaJpZM4Htvp6.gif]

**Comment by mmoayyed** [comment]
Fairly easily. I'd do: Ctrl+Shift+R to bring up the replace dialog. Punch in the pattern "@since 4.3.0" and change it to "@Since 5.0.0". Also account for "@since 4.3". Case insensitive mode. Replace all.

**Comment by dima767** [comment]
OK will give it a try. And what are the logistics for getting this into master?
Usual PR route off of feature branch based off of master's HEAD, etc.?

On Tue, Mar 15, 2016 at 07:08, Misagh Moayyed <notifications@github.com> wrote:
Fairly easily. I'd do: Ctrl+Shift+R to bring up the replace dialog. Punch in the
pattern " @since [https://github.com/since] 4.3.0" and change it to " @Since [https://github.com/Since] 5.0.0". Also account for " @since [https://github.com/since] 4.3". Case insensitive mode. Replace all.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/Jasig/cas/issues/1616#issuecomment-196767603
[https://github.com/Jasig/cas/issues/1616#issuecomment-196767603][https://github.com/notifications/beacon/AAAxVaQKYhayAxObIezRnG6Iksb9zVSCks5ptpMugaJpZM4Htvp6.gif]

**Comment by mmoayyed** [comment]
I'd say so yes. Helps to track changes and tag them under milestones, the PR route.

**Comment by mmoayyed** [comment]
Oh, and by the way, please also change the gradle config to point to 5.0.0.
