### ISSUE TITLE
TICKETGRANTINGTICKET table is getting "Locked" CAS 4.1.2

### ISSUE THREAD

**Issue by suvaraj** [Jasig/cas#1624]
Hi ,
The TICKETGRANTINGTICKET table is getting "Locked" when user tries to login. It does not happen all the time but the frequency is high .We are using the CAS of version 4.1.2 which runs on Tomcat server and we use JPA to connect to the database which is in mysql.The issue happens only on Production environment and we are not able to reproduce it in any other environment.

Caused by: org.springframework.dao.CannotAcquireLockException: could not execute batch; SQL [update TICKETGRANTINGTICKET set NUMBER_OF_TIMES_USED=?, CREATION_TIME=?, EXPIRATION_POLICY=?, LAST_TIME_USED=?, PREVIOUS_LAST_TIME_USED=?, ticketGrantingTicket_ID=?, AUTHENTICATION=?, EXPIRED=?, PROXIED_BY=?, SERVICES_GRANTED_ACCESS_TO=?, SUPPLEMENTAL_AUTHENTICATIONS=? where ID=?]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute batch

Please treat this as Urgent as we are facing this issue in Production Environment and we do not have any other job running which is using the table. In fact we configured it as clustered environment ,but to debug the issue we disabled the cluster with only one node running and still we have the same issue.

I have attached the application log and mysql lock for more details

Please help us out.
[mysql_lock.txt](https://github.com/Jasig/cas/files/169591/mysql_lock.txt)

[error.txt](https://github.com/Jasig/cas/files/169580/error.txt)

**Comment by mmoayyed** [comment]
@frett has applied a number of fixes to the 4.1.x release line. Please upgrade and see if the fixes apply to you. You should be able to adjust the locking level on the registry to avoid this sort of problem. 

The CAS project does not provide any sort of SLA when dealing with issues. Please contact the mailing lists or a commercial support provider if you need that type of support.
