### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1627]
Update the project README to better advertise the full feature-set of the CAS software. Include graphics where possible, and make explicit the use of overlays for building CAS.

**Comment by dima767** [comment]
It's currently attached to `5.1.0` milestone. Is this correct?

**Comment by mmoayyed** [comment]
Switched back to 5.0.0

**Comment by mmoayyed** [comment]
Handled via #1577

**Comment by mmoayyed** [comment]
Via https://github.com/Jasig/cas/pull/1649
