### ISSUE TITLE
Remove deprecated ClearPass functionality

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1640]

**Comment by ikogan** [comment]
Is there going to be something that'll replace the ability to get a user's unencrypted password that ClearPass provides?

**Comment by mmoayyed** [comment]
Yes. we are just removing the "deprecated" clearpass functionality. not its replacement. consult the docs plz: http://jasig.github.io/cas/4.2.x/integration/ClearPass.html

**Comment by mmoayyed** [comment]
Handled via #1577

**Comment by mmoayyed** [comment]
Via https://github.com/Jasig/cas/pull/1649
