### ISSUE TITLE
Missing LdapAuthenticationHandler attributeRepository documentation

### ISSUE THREAD

**Issue by jerrykan** [Jasig/cas#1643]
CAS server version: development

The [`LdapAuthenticationHandler`](http://jasig.github.io/cas/development/installation/LDAP-Authentication.html) page in the documentation states:
> The LdapAuthenticationHandler is capable of resolving and retrieving principal attributes independently without the need for extra principal resolver machinery.

but there doesn't appear to be any documentation about how to use the attributes returned by `LdapAuthenticationHandler` to popluate the `attributeRepository`.

While it is possible to use a `LdapPersonAttributeDao` to look up these attributes from LDAP and populate the `attributeRepository`, the documentation would indicate that this is not required. Is this really the case?

**Comment by mmoayyed** [comment]
http://jasig.github.io/cas/development/installation/Configuring-Principal-Resolution.html#principalresolver-vs-authenticationhandler

**Comment by mmoayyed** [comment]
The reason it's not documented for LDAP authn specifically, I suspect, is because it can be applied to all kinds of authn. Perhaps it would be good to cross link.

**Comment by jerrykan** [comment]
Thanks for the link, but as far as I can tell that page contains no information about attribute resolution, it only refers to principle resolution, which is not the lack of documentation I am talking about.

**Comment by mmoayyed** [comment]
You're right. Principal resolution is closely tied to attribute resolution. Since, when you resolve a principal, attributes are also retrieved and stuffed into that principal. Perhaps the docs should make that explicit. Feel free to issue a PR.

**Comment by jerrykan** [comment]
@mmoayyed the problem I'm am hitting is that I can't figure out how to populate the `attributeRepository` from the attributes resolved from the `LdapAuthenticationHandler`.

I have the following `LdapAuthenticationHandler`, which I can see from the debug log is retrieving the correct attributes values:
```
    <bean id="ldapAuthenticationHandler" class="org.jasig.cas.authentication.LdapAuthenticationHandler"
          init-method="initialize"
          p:principalIdAttribute="uid"
          c:authenticator-ref="ldapAuthenticator">
        <property name="principalAttributeMap">
            <map>
                <entry key="givenName" value="Firstname" />
                <entry key="sn" value="Surname" />
                <entry key="mail" value="Email" />
                <entry key="entryDn" value="DN" />
            </map>
        </property>
    </bean>
```
but then how do I populate the following `attributeRepository` with the attributes resolved from the above `LdapAuthenticationHandler`?
```
    <bean id="attributeRepository" class="org.jasig.services.persondir.support.MergingPersonAttributeDaoImpl">
        <property name="personAttributeDaos">
            <list>
                (??????)
            </list>
        </property>
    </bean>
```
If you can provide an example, I would be more than happy to write it up in the documentation and submit a pull request.

**Comment by mmoayyed** [comment]
You do not and cannot do that. 

Either attributes are retrieved by the handler, in which case you do not need the repository, OR, attribute are retrieved from the repository in which case the handler is entirely ignored. If you want to merge attributes from multiple sources, you need to configure everything as an attribute repository.

**Comment by jerrykan** [comment]
OK, that clarifies things. My reading of the documentation was that I could resolve the principle and attributes using the `LdapAuthenticationHandler` and then augment that with other attribute resolvers... which would make it nice not have to configure a separate `LdapPersonAttributeDao`.

I appreciate you taking to time to answer my queries.

**Comment by mmoayyed** [comment]
I would say that it would be confusing to do what you propose. If you are going to have other attribute resolvers, that means you're going to have other DAO type components that retrieve attributes from X and Y sources. So, to pull some attributes from source A that is tied to your handler, and then some other attributes from source B that is tied to an attribute DAO somewhere would be confusing configuration-wise. (It's perfectly fine to have multiple sources) It would be much easier, I'd argue, if you know how your attribute configuration is constructed in a single spot only. So, you need to decide whether the same source that handles authentication is sufficient for attributes as well, or whether you need separate extra sources to do a merge and combine. DAOs are usually used for advanced cases, such as caching, merging and cascading. 

I should clarify that I am not opposed to the behavior you had in mind, if you wish to issue a pull request to make that possible. By all means, do so if you find it easier that way :)  I am just saying I personally find that more confusing than the alternative, but that's just me.

**Comment by anigeorge** [comment]
Can you please tell me how to do this? I have authentication handler and principalAttributeMap with all the required attributes. How to populate this to an attributeRepository?
