### ISSUE TITLE
CasVersion#getDateTime doesn't work with Wildfly vfs: resource path

### ISSUE THREAD

**Issue by kalmykov-sergey** [Jasig/cas#1651]
1. CAS server version 4.2.0
2. Container type/version Wildfly 9

During server start:
org.jasig.cas.CasVersion#getDateTime falls with IllegalArgumentException on vfs:/... resource path

**Comment by mmoayyed** [comment]
post the entire stack trace plz.

**Comment by mmoayyed** [comment]
Looks like the class does not handle vfs resources. We likely could use Spring here to detect that protocol and construct the appropriate VFS resource.

**Comment by mmoayyed** [comment]
In particular, this component seems to do the trick:
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/io/VfsResource.html

You may want to post a patch, since you already have wildfly available and deployed.

**Comment by devpreview** [comment]
Similar problem when deploying on Wildfly 10:

> 2016-03-28 18:08:05,184 ERROR [org.springframework.web.context.ContextLoader] (ServerService Thread Pool -- 81) Context initialization failed: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'casEnvironmentContextListener': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.IllegalArgumentException: Unhandled url protocol: vfs for class: org.jasig.cas.CasVersion resource: vfs:/content/cas-management-webapp-4.2.0.war/WEB-INF/lib/cas-server-core-4.2.0.jar/org/jasig/cas/CasVersion.class

**Comment by mmoayyed** [comment]
You're welcome to apply this patch and see if it solves the issue for you:
https://github.com/Jasig/cas/pull/1657

**Comment by devpreview** [comment]
It's not work for cas-4.2.0.
Too many conflicts :)

**Comment by devpreview** [comment]
Patch for cas-4.2.0
http://pastebin.com/tzkfu2yW

**Comment by benborba** [comment]
i'm using jboss eap 6.4 and get the same problem when deploy.  at last i resolved it by :
1. add jboss vfs dependency
                <dependency>
			<groupId>org.jboss</groupId>
			<artifactId>jboss-vfs</artifactId>
			<version>3.2.9.Final</version>
			<scope>provided</scope>
		</dependency>
2. copy CasVersion to my class path and change it, add "else if" to protocol part like this:
 else if ("vfs".equals(resource.getProtocol())) {
            	VirtualFile vf = (VirtualFile)resource.getContent();
            	return new DateTime(vf.getLastModified());
            }

**Comment by frett** [comment]
@benborba the latest patch on #1659 should resolve it without needing to introduce the jboss-vfs dependency

**Comment by benborba** [comment]
yes @frett , no more dependencies, that's look better! thanks :-P

**Comment by kalmykov-sergey** [comment]
i can propose to consider usage of org.springframework.util.ResourceUtils in addition. It offers wide range of specific protocols, i.e. for IBM WAS. 
http://pastebin.com/RwXQDkff
