### ISSUE TITLE
CAS attributes are not released to SAML SPs

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1655]
This is wrt to the new SAML2 WebSSO functionality. 

When a SAML request comes in, CAS builds a callback url and appends the entityID as a query parameter to the callback. The callback becomes the service parameter and is sent to /login.
Upon login, CAS redirects back to the callback endpoint. The endpoint attempts to validate the ticket. It supplies the callback url again as the service and calls on CAS to validate the ticket.
Validation succeeds, but because the service used for validation is the callback service and not the real one (entityID), the SP client ends up getting no attributes because the callback has no attribute release policy and it’s a catchall for all.
 
We likely need to come up with a mechanism to let CAS know to use the “entityID” of the service used when it starts to process attributes for validation. Some sort of interceptor component in the validation logic that says: if the service is a callback url, look into the entityID parameter and look up the registered service associated with that. Use rules defined by that definition to process attributes only.
 
In all places, the callback service must remain the official entry point. Difficulty here is that we are really supplying 2 services to CAS where one is fake (callback) and the other is real (entityID). The service parameter must always be a URL because that is what CAS uses to issue redirects. The entityID cannot become the service parameter because it’s not always a URL. So we need the callback url to stay around and act as a façade that it does, but we need some internal mods to instruct CAS to pick the real service based on the entityID.

**Comment by mmoayyed** [comment]
Likely, SAML registered services should also be changed to include the entityId in the serviceId field, rather than the actual requester URL.

**Comment by mmoayyed** [comment]
This might also be useful for how we support OAuth @leleuj since the same callback url approach is used there too.

**Comment by frett** [comment]
The other thing I don't believe our current model accounts for is custom themes & logos on SAML Registered Services. It currently would rely on the configuration for the callback service and not that actual SAML service.

**Comment by mmoayyed** [comment]
Yes, that is very likely. (I do suppose however that you could use the mdui module for that sort of thing)

**Comment by leleuj** [comment]
Indeed, for OAuth, we also use an internal callback url: I must check it works properly with the attributes.

**Comment by leleuj** [comment]
There is a problem, I opened: https://github.com/Jasig/cas/issues/1697

**Comment by mmoayyed** [comment]
Via https://github.com/Jasig/cas/pull/1649
