### ISSUE TITLE
Allow an option for SWF state to be managed by container session

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1656]
Provide an option to manage SWF state via the container session, rather than the client. This might be useful in cases where a deployment wishes to extend SWF machinery to great extents and likely is more comfortable with a session-backed state, that is replicated across nodes.

**Comment by dima767** [comment]
Might make sense to explore Hazelcast-based implementation or look into Spring Session project.

**Comment by mmoayyed** [comment]
Spring Session is a great idea! Will investigate.

**Comment by mmoayyed** [comment]
Handled via #1577

**Comment by mmoayyed** [comment]
Via https://github.com/Jasig/cas/pull/1649
