### ISSUE TITLE
ClassNotFoundException: org.slf4j.impl.Slf4jLogger from Service Module Loader

### ISSUE THREAD

**Issue by devpreview** [Jasig/cas#1662]
After login attempts from /cas-management to /cas
I have exception:

> Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.Slf4jLogger from [Module "deployment.cas.war:main" from Service Module Loader]
>         at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)

[Full stacktrace](http://pastebin.com/AstTxi7i)

1. CAS server version: 4.2.0
2. Container type/version: Wildfly 10

**Comment by mmoayyed** [comment]
Thanks for the report. I'll try to look into this tomorrow.

**Comment by mmoayyed** [comment]
Cant duplicate.

Downloaded WF 10 and ran the standalone server.
Deployed the CAS over under 4.2.1-SNAPSHOT to master.
No errors. Can get to 8080/cas just fine.

**Comment by mmoayyed** [comment]
Used this to deploy: https://docs.jboss.org/wildfly/plugins/maven/latest/examples/deployment-example.html

**Comment by mmoayyed** [comment]
Actually, I take that back. I do see an error in the browser that is almost the same as yours, but I can't trace this in the logs. Which file did you use to look up the stack trace?

**Comment by devpreview** [comment]
This error has DEBUG level.
My config for Wildfly:

```
<subsystem xmlns="urn:jboss:domain:logging:3.0">
    ...
    <logger category="org.jboss.as.config">
        <level name="DEBUG"/>
    </logger>
    <root-logger>
        <level name="DEBUG"/>
        <handlers>
            <handler name="CONSOLE"/>
            <handler name="FILE"/>
        </handlers>
    </root-logger>
    ...
</subsystem>
```

**Comment by mmoayyed** [comment]
Thanks. Which file in WF do the above changes go into?

**Comment by devpreview** [comment]
/__wildfly_path__/__mode__/configuration/__mode__.xml

__wildfly_path__ - path to Wildfly
__mode__ - standalone or domain

See jboss.server.config.dir to find the path.
Wildfly output or server log has this variable:

```
2016-03-31 00:21:42,772 DEBUG [org.jboss.as.config] (MSC service thread 1-1) Configured system properties:
    [Standalone] = 
    ...
    jboss.server.config.dir = /srv/wildfly/standalone/configuration
```

For example:
/opt/wildfly/standalone/configuration/standalone.xml
/opt/wildfly/domain/configuration/domain.xml

**Comment by mmoayyed** [comment]
Found and fixed the issue. Tested with Jetty and WF 10. 

The fix is to ensure logger fields are marked as transient, so they are ignored during serialization.

**Comment by devpreview** [comment]
Thanks! Worked with my WildFly 10 too.

P.S. To use CAS 4.2.0 with WildFly 10 your must apply this patch's:

1. [1658.patch](https://patch-diff.githubusercontent.com/raw/Jasig/cas/pull/1658.patch)
2. [1659.patch](https://patch-diff.githubusercontent.com/raw/Jasig/cas/pull/1659.patch)
3. [1666-4.2.0.patch](https://gist.github.com/devpreview/862d4260b1cd411fd51df3db937a886d) (based on [1666.patch](https://patch-diff.githubusercontent.com/raw/Jasig/cas/pull/1666.patch))

**Comment by mmoayyed** [comment]
Point your overlay to 4.2.1-SNAPSHOT and you should have all those patches available. The actual release will be in a few weeks.
