### ISSUE TITLE
Meta tag in top.jsp missing proper closing tag

### ISSUE THREAD

**Issue by gougej88** [Jasig/cas#1667]
1. Confirmed missing in 4.1.x and 4.2.x as of 3/31/16. Found on 4.1.4
2. Tomcat 8
3.  Vendor provided that error messages were thrown from CAS client for inproper meta tag closing.

Meta tag current: <meta name="viewport" content="width=device-width, initial-scale=1">
Meta tag correct: <meta name="viewport" content="width=device-width, initial-scale=1" />

Exception Details:
- Error Description: The 'meta' start tag on line 15 position 4 does not match the end tag of 'head'. Line 26, position 3.
- Error Type: System.Xml.XmlException
- Source: System.Xml
- Stack Trace: 
-    at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
-    at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
-    at System.Xml.XmlTextReaderImpl.ParseEndElement()

Please apply to 4.1.x and 4.2.x for future compatibility.

**Comment by mmoayyed** [comment]
Happy to. Do you want to submit a pull request?

**Comment by gougej88** [comment]
Been a long time since I have worked with Git. Think I created a pull request with the change.  Not sure if you or I merge it into the next builds of 4.1.7 and 4.2.x.
Thanks for the quick response! 
-Jeff

**Comment by mmoayyed** [comment]
I will merge. You want to:

1. Fork the repo here and clone your fork
2. Create a branch off of 4.1.x or 4.2.x
3. Apply the change
4. Commit and push the change to a remote branch of your fork
5. Submit a PR, targeting 4.1.x OR 4.2.x

**Comment by mmoayyed** [comment]
See http://jasig.github.io/cas/developer/Contributor-Guidelines.html

**Comment by mmoayyed** [comment]
Thanks for the patch! I merged the change back to all 4.1 and 4.2 releases. Releases should be out in a few weeks. Great work!
