### ISSUE TITLE
When using OAuth support, the pac4j logout hides the CAS logout

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1670]
The pac4j security definition should exclude its own logout or use another url.

**Comment by mmoayyed** [comment]
You mean, contacting /cas/logout will have pac4j log out, rather than CAS?

**Comment by leleuj** [comment]
Exactly, as /callback and /logout are the default endpoints brought by pac4j via this definition: https://github.com/Jasig/cas/blob/master/cas-server-support-oauth/src/main/resources/META-INF/spring/cas-servlet-oauth.xml#L11

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1684
