### ISSUE TITLE
Custom OAuth Protected Web Services

### ISSUE THREAD

**Issue by uwolfinger** [Jasig/cas#1671]
So far the only protected Service by OAuth is /oauth2.0/profile. Having a Custom Service in a Custom webapp, e.g. /myapp/rest/data and protect it by OAuth is not possibe at the moment.

The goal would be to provide a servlet filter which protects services and checks an access token towards the jasig OAuth server.

See also https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/S_feEPvn5Yk

CAS server version: 4.2
Container type: Tomcat

**Comment by mmoayyed** [comment]
You have got the flow incorrectly here. This is not something CAS would want to do. Custom service's concerns are custom service's concern. If you want to protect `/myapp/rest/data`, then you need to ensure it's configured to talk to CAS via whatever mechanism you deem fit (such as a filter), *inside your own app*, not CAS.

**Comment by mmoayyed** [comment]
Or at best, this might be something you could contribute to the CAS client, not the server.
