### ISSUE TITLE
Missing commons-collections4 dependency for persondir

### ISSUE THREAD

**Issue by jerrykan** [Jasig/cas#1673]
CAS server version: 4.2.1 (also had the same issue with 4.2.0-RC3)

I have been hitting a silent failure when trying to use `org.jasig.services.persondir.support.ldap.LdaptivePersonAttributeDao` within my `deployerConfigContext.xml` file.

It seems as though `LdaptivePersonAttributeDao.getPeopleForQuery()` eventually calls `CaseInsensitiveNamedPersonImpl.createImmutableAttributeMap()` (see stack output from debugger below) which attempts to create a new `CaseInsensitiveMap` object from commons-collections4, but this library is not included when I do a `mvn package`.

As a work around I can include the following in my `pom.xml` file and things start working:
```
...
<dependencies>
    ...
    <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.0</version>
    </dependency>
</depencencies>
...
```

I barely know anything about java development (apparently enough to get the eclipse debugger running with tomcat and read some code), but I assume the following line needs to be removed from the `build.gradle` file?:
```
diff --git a/build.gradle b/build.gradle
index e69d7d65e1..46150b2d3a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -728,7 +728,6 @@ persondirectory  : dependencies.create("org.jasig.service.persondir:person-directory-impl:$personDirectoryVersion") {
             exclude(group: 'commons-logging', module: 'commons-logging')
             exclude(group: 'org.slf4j', module: 'slf4j-api')
             exclude(group: 'org.apache.commons', module: 'commons-lang3')
-            exclude(group: 'org.apache.commons', module: 'commons-collections4')
             exclude(group: 'org.springframework', module: 'spring-beans')
             exclude(group: 'org.ldaptive', module: 'ldaptive')
             exclude(group: 'org.springframework', module: 'spring-context')
```
----
Stack output from eclipse debugger:
```
CaseInsensitiveNamedPersonImpl.createImmutableAttributeMap(int) line: 42	
CaseInsensitiveNamedPersonImpl(BasePersonImpl).buildImmutableAttributeMap(Map<String,List<Object>>) line: 51	
CaseInsensitiveNamedPersonImpl(BasePersonImpl).<init>(Map<String,List<Object>>) line: 42	
CaseInsensitiveNamedPersonImpl(NamedPersonImpl).<init>(String, Map<String,List<Object>>) line: 34	
CaseInsensitiveNamedPersonImpl.<init>(String, Map<String,List<Object>>) line: 33	
LdaptivePersonAttributeDao.getPeopleForQuery(SearchFilter, String) line: 158	
...
```

**Comment by mmoayyed** [comment]
Thanks for the report. This is really an issue with the person directory project of which CAS is a user. Please move the issue over. https://github.com/Jasig/person-directory

You should absolutely not include this:

```
<dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.0</version>
    </dependency>
```

You want:

```
<dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.1</version>
    </dependency>
```

The CAS project does not on purpose include any version of collections. I imagine person directory would also eventually end up removing that dependency.

**Comment by jerrykan** [comment]
Hello @mmoayyed the person-directory project does not have an issue tracker (that I can find) so there is no place to move the issue to.

As I understand it the person-directory is a dependency pulled in by core CAS components, and currently affects the ability for CAS to perform attribute resolution from LDAP (or even indicate that an error is occurring without having to pull out a debugger), so I would assume that the CAS project would still want to track this as being a open issue until it is resolved.

**Comment by mmoayyed** [comment]
Thanks for the note. I opened up the issues section. PD usually uses a separate JIRA to mark and track issues of which I have never been a fan. So please move the issue over. 

You're partly correct, but this is not really an issue we can do anything about it other than to wait. Leaving it open would likely have better publicity on the issue, so I can have it be open if you prefer.

**Comment by mmoayyed** [comment]
I realized that PD ends up fixing that bug, we may want to upgrade CAS as well and issue a follow up release. So opening this issue up to track that. Thanks again.

**Comment by mmoayyed** [comment]
reviewed person directory. removing collections4 is a nontrivial task at the moment. will create an issue to track that at a later time. For the time being, this would have to be a doc enhancement.
