### ISSUE TITLE
Upgrade PersonDirectory to 1.7.1: allow ldapPersonAttributeDao's resultAttributeMapping entry keys to be case-insensitive

### ISSUE THREAD

**Issue by jerrykan** [Jasig/cas#1674]
CAS server version: 4.2.1

The [LDAP Attribute Resolution](http://jasig.github.io/cas/development/integration/Attribute-Resolution.html#ldap) documentation gives the impression that the `resultAttributeMapping` map entry keys are not case-sensitive, but it appears that only keys with lower case values will work (ie. `<entry key="displayName" value="displayName" />` will not work).

As best as I can tell in `org.jasig.services.persondir.support.AbstractQueryPersonAttributeDao.mapPersonAttributes()` the `person` object passed in contains attribute keys that are all lower-case, so the `if (personAttributes.containsKey(dataKey)) {}` condition will only be met if the `dataKey` is also forced to be lower case.

Though based on the name of the class of the `person` object being passed in (`CaseInsensitiveNamedPersonImpl`) it would seem pointless to create a case insensitive version of the `NamedPersonImpl` if it isn't being used in that way (though I have tried to dig into that part of the code).

**Comment by mmoayyed** [comment]
Thanks for the report. This is really an issue with the person directory project of which CAS is a user. Please move the issue over. https://github.com/Jasig/person-directory

**Comment by mmoayyed** [comment]
Could you upgrade your person directory depenency to force it to use 1.7.2? Seems like this issue is resolved there.

**Comment by mmoayyed** [comment]
Or rather, 1.7.1.

Reference: https://github.com/Jasig/cas/blob/4.2.x/gradle.properties#L54

**Comment by jerrykan** [comment]
I'm assuming that to do this properly you are supposed to recompile CAS and somehow use the compiled version in the `pom.xml`, which is well beyond my skill/knowledge level of using java/maven.

As a shortcut I just added the following to my `pom.xml`:
```
    <dependency>
        <groupId>org.jasig.service.persondir</groupId>
        <artifactId>person-directory-impl</artifactId>
        <version>1.7.1</version>
    </dependency>
```
Then a `mvn package`, deployed the `war` to my Tomcat's `webapp` directory and deleted the `cas/WEB-INF/lib/person-directory-*-1.7.0.jar` files and started up Tomcat. There no longer seem to be issues with case-sensitivity.

So I assume if the dependency on the person-directory in CAS can be bumped up to 1.7.1 that should solve the problem.

**Comment by mmoayyed** [comment]
No, all you should have to do for now is to declare that dependency in your overlay pom and exclude what is shipped by CAS. We will bump the dependency for the next patch release, which would mean less work for everyone all around. Thanks for the confirmation.

**Comment by jerrykan** [comment]
CAS Version: 4.2.1

Just adding to this issue that:

* `org.jasig.services.persondir.support.jdbc.SingleRowJdbcPersonAttributeDao`
* `org.jasig.services.persondir.support.jdbc.MultiRowJdbcPersonAttributeDao`

are broken in `person-directory` v1.7.0

```
2016-04-12 15:03:03,710 ERROR [org.springframework.web.context.ContextLoader] - <Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultAuthenticationSystemSupport': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.jasig.cas.authentication.AuthenticationTransactionManager org.jasig.cas.authentication.DefaultAuthenticationSystemSupport.authenticationTransactionManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultAuthenticationTransactionManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.jasig.cas.authentication.AuthenticationManager org.jasig.cas.authentication.DefaultAuthenticationTransactionManager.authenticationManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticationManager': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticationHandlersResolvers': Cannot resolve reference to bean 'primaryPrincipalResolver' while setting bean property 'sourceMap' with key [<primaryAuthenticationHandler>]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'personDirectoryPrincipalResolver': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public final void org.jasig.cas.authentication.principal.PersonDirectoryPrincipalResolver.setAttributeRepository(org.jasig.services.persondir.IPersonAttributeDao); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'attributeRepository' defined in ServletContext resource [/WEB-INF/deployerConfigContext.xml]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/jdbc/core/simple/ParameterizedRowMapper
```

It seems as though `person-directory` v1.7.0 is using `spring-jdbc` v4.2.3, but `org.springframework.jdbc.core.simple.ParameterizedRowMapper` was deprecated/removed(?) in v4.1.0/v4.2.0 ([ref](https://docs.spring.io/spring/docs/4.1.0.RELEASE/javadoc-api/deprecated-list.html))

I can confirm that using `person-directory` v1.7.1 fixes the problem with JDBC attribute resolution as well, by adding the following to the `pom.xml`

```
...
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                ...
                <configuration>
                    ...
                    <overlays>
                        <overlay>
                            <groupId>org.jasig.cas</groupId>
                            <artifactId>cas-server-webapp</artifactId>
                            <excludes>
                                <exclude>WEB-INF/lib/person-directory-*-1.7.0.jar</exclude>
                            </excludes>
                        </overlay>
                    ...

    <dependencies>
        <dependency>
            <groupId>org.jasig.service.persondir</groupId>
            <artifactId>person-directory-impl</artifactId>
            <version>1.7.1</version>
        </dependency>
    ...

So bumping the `person-directory` to v1.7.1 will fix a number of problems.

**Comment by mmoayyed** [comment]
Cool. Feel free to submit a patch to 4.2.x.

**Comment by featheredtoast** [comment]
Any way to swap person-directory version using gradle? I can add the dependency, but I don't see a way of excluding the previous dependency.

I was attempting to update my version of CAS to the latest and I hit this issue today.

Alternatively, what is the schedule for 4.2.2 getting released?

**Comment by mmoayyed** [comment]
Schedules are outlined here:
https://github.com/apereo/cas/milestones

You probably need to exclude the dependency from cas-server-webapp. The sample overlay shows you how to certain files can be excluded from the packaging.

**Comment by featheredtoast** [comment]
Ah, appreciated. I've gotten a gradle build up and it appears that the dependencies have been getting through correctly.

Further googling, another exception I'm getting seems unrelated and similar to [this](https://groups.google.com/forum/#!searchin/jasig-cas-user/No$20qualifying$20bean$20of$20type/jasig-cas-user/Yu4Yw_36Qrc/k4ifZt-nDwAJ) issue. I'm going to spelunk there and get out of GH. Seems like a config issue on my end, you guys are golden. Thanks again! :)
