### ISSUE TITLE
SLO on ticket expiration

### ISSUE THREAD

**Issue by raisou** [Jasig/cas#1679]
Hi,

I'm using CAS v4.1.6 and i'm looking for slo POST requests at ticket expiration.

I was unable to make it run following documentation so i tried to search in code and it looks like a bug.

In CentralAuthenticationServiceImpl class, in getTicket method, after the deletion of the ticket in registry i see a exception throw i can't understand. [Here](https://github.com/Jasig/cas/blob/v4.1.6/cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java#L533)

This throw coz the non execution of the performLogout method and the execution of corresponding SLO requests. [See](https://github.com/Jasig/cas/blob/v4.1.6/cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java#L218)

When i comment this line it looks working like a charm.

Am i missing something ?

**Comment by mmoayyed** [comment]
This is likely a question best suited for the CAS mailing list. Please post to the list, and if there is an actual issue, file a bug.
