### ISSUE TITLE
Add ability to easily add custom authentication exceptions for custom error messages

### ISSUE THREAD

**Issue by dima767** [Jasig/cas#1681]
Currently, the `AuthenticationExceptionHandler` is not designed for easily adding custom authentication exceptions and thus making them available for custom UI message mapping in `messages.properties`.

Refactor `AuthenticationExceptionHandler` to add such facility for adding custom authentication exceptions to the list of the default ones and make it work via `cas.properties`, so the deployer would only need to do 2 simple things (well, besides introducing custom `GeneralSecurityException` or `PreventedException` and throwing them from their custom authn handlers):

1) Add a list of such exceptions to `cas.properties`:

`cas.custom.authentication.exceptions=org.example.MyCustomEx1,org.example.MyCustomEx2`

2) Map the messages for those in `messages.properties`:

```properties
authenticationFailure.MyCustomEx1=Custom msg1
authenticationFailure.MyCustomEx2=Custom msg2
...
```

**Comment by jasp255** [comment]
Hi,
I try this solution on cas 5.1.0 but is not working for me.

I debug application and in "handle" method  of "AuthenticationExceptionHandlerAction" class obtains null in de exception parameter:

public class AuthenticationExceptionHandlerAction extends AbstractAction {
public String handle(final Exception e, final MessageContext messageContext) {
  //e is null !!!

What is the problem?
