### ISSUE TITLE
4.1.7 Audit error 'principal' cannot be null.

### ISSUE THREAD

**Issue by peyobr** [Jasig/cas#1692]
Ensure that you have reported the following:

1. CAS version: 4.1.7
2. Container: Tomcat 7
3. Steps to duplicate the problem: simply upgrade an enterprise production fully working CAS v4.1.6 installation to v4.1.7
4. Stacktraces and CAS logs follows...

2016-04-18 12:53:16,031 DEBUG [org.jasig.cas.web.flow.AuthenticationViaFormAction] - 'principal' cannot be null.
Check the correctness of @Audit annotation at the following audit point: execution(public abstract transient org.jasig.cas.authentication.Authentication org.jasig.cas.authentication.AuthenticationManager.authenticate(org.jasig.cas.authentication.Credential[]))
java.lang.IllegalArgumentException: 'principal' cannot be null.
Check the correctness of @Audit annotation at the following audit point: execution(public abstract transient org.jasig.cas.authentication.Authentication org.jasig.cas.authentication.AuthenticationManager.authenticate(org.jasig.cas.authentication.Credential[]))

**Comment by dima767** [comment]
Please create a sample overlay demonstrating the exception so the dev team could re-create and debug locally as described here: https://github.com/cas-projects/cas-issues

**Comment by mmoayyed** [comment]
There was a recent post on the mailing list. You likely are just missing the commons-collections dependency from person directory.
