### ISSUE TITLE
Throttling support on REST Interface

### ISSUE THREAD

**Issue by mdottavi** [Jasig/cas#1694]
Hi,
I'm using CAS 4.1.0 with REST interface with tomcat.
I enabled Throuttling and such config was working fine for cas-web-app login.
The problem is that I was not able to enable Throttling for REST access.

After a lot of experiments and web searching I landed to this [CAS-Community message](https://groups.google.com/a/apereo.org/forum/#!searchin/cas-user/throttling$20rest/cas-user/bbDxUFXRgMQ/QvGQL5UGLAAJ) where someone else asked for the same feature...

Is there any chance to get this supported?

**Comment by mmoayyed** [comment]
Yes, there is always the possibility. Feel free to submit a patch.

**Comment by mmoayyed** [comment]
I am somewhat casually working on this :) So stayed tuned. I am not targeting this for v4, so you may want to backport when/if it becomes available.

**Comment by mmoayyed** [comment]
Via https://github.com/Jasig/cas/pull/1649

**Comment by qfrank** [comment]
@mmoayyed 
Hi there! I'm using cas-overlay-template 5.1.2, throttling for rest access is still not working..Am i missing something?

**Comment by qfrank** [comment]
throttling works fine only for cas-web-app login
