### ISSUE TITLE
OAuth support can not get Principal from ldap or any other authentication handler

### ISSUE THREAD

**Issue by yisiqi** [Jasig/cas#1695]
In CAS 5.0.0, the Profile Controller serializing principal from J2EContext which based on pac4j. But the origin principal from ldap is ignored. I wanna the origin version principal which contains much useful infomations, but no way to get them.

**Comment by leleuj** [comment]
In fact, the OAuth endpoint is protected by the pac4j security library which delegates the authentication to the CAS server. So you should be able to setup the CAS server / authentication according to your needs by defining the appropriate `primaryAuthenticationHandler` and `primaryPrincipalResolver`.

**Comment by leleuj** [comment]
Closing. Please ask any questions on the mailing list.

**Comment by yisiqi** [comment]
@leleuj Sorry, I got. Thanks for the help.
