### ISSUE TITLE
OAuth support should take into account CAS services definition

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1697]
Especially the CAS services (OAuth client) attributes release policy

**Comment by leleuj** [comment]
I also noticed that the OAuth support doesn't use the `ensurePrincipalAccessIsAllowedForService` method, I guess it's also necessary.

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1698

**Comment by mmoayyed** [comment]
Thanks!

Just a quick tip that if you put in "Closes #IssueNumber" in the PR body when you submit, GH will link the PR to the issue, and will auto close the issue when the PR is merged. So you wouldnt have to manually link the two together.
