### ISSUE TITLE
In CAS 4.2.0, the ticket registry cleaner does not remove expired tickets

### ISSUE THREAD

**Issue by petracvv** [Jasig/cas#1708]
CAS Version: 4.2.0
Container: Tomcat 8.0.32

We are using CAS 4.2.0 on tomcat as our SSO solution and we have the DefaultTicketRegistry enabled. However, even though we have tickets expiring, the ticket registry cleaner job does not find any tickets to clean up. If I look on our statistics page I see that we have expired tickets:

![cas_stats](https://cloud.githubusercontent.com/assets/3154784/14744784/d89f99b8-086d-11e6-84d7-06fcabe5d1c4.png)

But the ticket cleanup does not find them:
```
2016-04-22 09:09:46,488 INFO [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - Beginning ticket cleanup...
2016-04-22 09:09:46,488 INFO [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - 0 expired tickets found and removed.
```

I have tried turning on debug logging for more information but there is no more output produced related to the cleaning process. 

I have rechecked any configuration that may be related but we are using close to defaults. I have only modified the cleaner repeatinterval to 3600 sec so it runs every hour.

Let me know if you want more logging information.

**Comment by mmoayyed** [comment]
As the issue template suggested at the time of opening the issue:

## To reproduce the issue

When and where appropriate, please submit your CAS configuration/overlay to this project in form of a pull request so we could easily evaluate your deployment configuration to reproduce the issue: 

https://github.com/cas-projects/cas-issues/

**Comment by petracvv** [comment]
I am not sure how to make a pull request to this repository if I only have an overlay. However, my overlay is available here: https://github.com/WIU/cas-overlay.

This overlay is different from our actual deployment but I was able to reproduce my issue with it (using real credentials). In the version on github, all sensitive credentials have been replaced with REDACTED, new tgc.encryption and signing keys were generated, new google apps keys were generated and all of our custom theming has been removed.

I have also changed the ticket cleaner to run every 2 min, put the ticket hard timeout at 5min and the sliding timeout at 100sec. 

With this overlay locally, I would login through it, wait 100sec and see that the statistics page displays 1 expired TGT and that expired TGT never goes away even with the ticket cleaner running.

**Comment by mmoayyed** [comment]
Tracked this down, and duplicated it. Patch pending.

**Comment by petracvv** [comment]
Thanks for the quick fix!

**Comment by mmoayyed** [comment]
Sure.

Try running 4.2.2-SNAPSHOT in your local overlay. That should take care of this issue.
