### ISSUE TITLE
Table name changed with no documentation on  it

### ISSUE THREAD

**Issue by mateofacu** [Jasig/cas#1709]
#### Context
Task: Migration from CAS 4.1.4 to CAS 4.1.7

#### Problem
In AbstractRegisteredService.java there is a change from v4.1.6 to v4.1.7  in which  the table name mapping for property attributeReleasePolicy was modified.

I searched into v4.1.7  release changes. I didn't find a commit, issue or comment making reference to this change.  May be I missed something in here? 

I wonder if it is actually a change but  a mistake. Personally I do not consider a table name change suitable for a fix release with no mention on it.

**v4.1.7**
```java
...
 @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(name="RegisteredServiceImpl_Props")
    private Map<String, DefaultRegisteredServiceProperty> properties = new HashMap<>();
...
```

**v4.1.6**
```java
...
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(name="RegisteredServiceImpl_Properties")
    private Map<String, DefaultRegisteredServiceProperty> properties = new HashMap<>();
...
```

**Comment by mmoayyed** [comment]
It's possible that the changelog generation process missed that fix, because the original PR was targeted to 4.2.x and it was backported to 4.1.We don't mention the table names in the documentation, because we'd want CAS to handle the generation automatically without any manual changes.

**Comment by mateofacu** [comment]
But what about migrations? It becomes error and trial.

**Comment by frett** [comment]
here is the issue that actually precipitated this change:
https://github.com/Jasig/cas/issues/1652

**Comment by mateofacu** [comment]
Perfect. mmoayyed is right then. Just problem with the changelog generation.
