### ISSUE TITLE
Consider renaming top level package to org.apereo

### ISSUE THREAD

**Issue by dima767** [Jasig/cas#1718]
For v5, this is a good opportunity to rename top level package from `org.jasig` to `org.apereo` to reflect the reality of an umbrella organization. I am +1 this one...

**Comment by leleuj** [comment]
+1

**Comment by mmoayyed** [comment]
Discussing the move with sonatype. Hold tight.

**Comment by mmoayyed** [comment]
This is ready: https://issues.sonatype.org/browse/OSSRH-22155

**Comment by mmoayyed** [comment]
It's the kind of thing we should really do before M1.

**Comment by dima767** [comment]
exactly

**Comment by dima767** [comment]
OK, I'll try to tackle this one today, falling back to @mmoayyed if I fail miserably ;-)
