### ISSUE TITLE
how to build cas-4.2.1?

### ISSUE THREAD

**Issue by mmdallal** [Jasig/cas#1727]
Hello,

We used to build cas-4.1.x using the command (mvn clean package). now with the new release cas-4.2.1 how to do that?

Thanks a lot.

**Comment by jiangfangcheung** [comment]
maven overlay Google it


发自网易邮箱大师
在2016年05月01日 19:43，mmdallal 写道:

Hello,

We used to build cas-4.1.x using the command (mvn clean package). now with the new release cas-4.2.1 how to do that?

Thanks a lot.

**Comment by mmdallal** [comment]
I know it is maven overlay, but there is no pom.xml
how to do?

**Comment by jiangfangcheung** [comment]
This is the overlay-template,"mvn clean package"
https://github.com/UniconLabs/simple-cas4-overlay-template




At 2016-05-01 20:20:04, "mmdallal" <notifications@github.com> wrote:


I know it is maven overlay, but there is no pom.xml
how to do?

**Comment by mmdallal** [comment]
I will check it

Thank you a lot,

**Comment by jiangfangcheung** [comment]
: )，you are welcome

**Comment by mmdallal** [comment]
Hi,

I got many troubles, have you a guide with step by step to do CAS-4.2.1 configuration with Active Directory?

Thanks.

**Comment by dima767** [comment]
Please use CAS user mailing list for questions like these.
