### ISSUE TITLE
OAuth implementation does not support custom grant flow

### ISSUE THREAD

**Issue by zawn** [Jasig/cas#1734]
@leleuj Currently OAuth implement coupling is too high, I can not without modifying the code to add a custom grant flow.Do you think needs to be improved.

Thank you.

**Comment by leleuj** [comment]
I'm fairly happy with the new implementation, as the previous one didn't feel very goo. That said, there is always room for improvement. Feel free to submit pull requests for that.

**Comment by zawn** [comment]
ok, as we discussed before pac4j, I wish to add additional grant flow.

I want to add SMS login,email login (forgot password for email), third-party login.

SMS and EMail Flow:
And similar authorization code flow,Send an authorized code (may be url) to the specific phone number or mail already exists in the user profile, user-agent return code to obtain access token.

third-party token Flow(trusted token flow):
Allows direct use of trusted_token to obtain our own access_token, trusted_token is usually a acces_token obtained from third-party sdk. CAS use pac4j verify the validity of trusted_token and obtain use profile.

**Comment by mmoayyed** [comment]
Your 3rd party token is already supported. 

Your other 2 flows, I am not sure there is a place in CAS for those. They seems like they are more relevant in your particular deployment.

**Comment by zawn** [comment]
Sorry I did not find similar 3rd party token(is a OAuth2 accessToken) flow in existing cas , Now cas integrated pac4j-oauth supports only the authorization code flow.

supplement:
1. The client ( our mobile app) by calling the 3rd party OAuth provider's  SDK to obtain valid AccessToken,
2. Obtained in the previous step Access_Token passed to us CAS server.
3. After the CAS to verify the validity of the token issued our own AccessToken ( Pac4j OAuth module can be used directly to complete the third-party verification token )

**Comment by zawn** [comment]
for mobile app, we are currently very popular SMS Login.

**Comment by mmoayyed** [comment]
What you describe as the use case is fine, but again, I'd stress that it's not something we'd want to include at this point. The CAS Oauth functionality is the authority on generating access tokens. That cannot be delegated to anything else. If you wish to delegate, then you better start using the 3rd party API directly and not go through CAS...and the write the integration module for the 3rd party API, based no pac4j or something else.
