### ISSUE TITLE
usernameAttributeProvider requires username attribute to be authorized for release

### ISSUE THREAD

**Issue by idwright** [Jasig/cas#1738]
CAS version 4.1.7

If the usernameAttributeProvider is not listed as an allowedAttribute for release then the default attribute will be used instead of the configured usernameAttributeProvider.

e.g. for the following configuration the mail attribute will be returned not the uid attribute

     <bean id="usernameAttributeProvider"
                class="org.jasig.services.persondir.support.SimpleUsernameAttributeProvider">
                <property name="usernameAttribute" value="mail" />
        </bean>

<bean class="org.jasig.cas.services.RegexRegisteredService" p:id="5"
                        p:name="HTTP and IMAP" p:description="Allows HTTP(S) and IMAP(S) protocols"
                        p:serviceId="^https?://.*(:8443)?" p:evaluationOrder="10000100">
                        <property name="usernameAttributeProvider">
                                <bean                                       class="org.jasig.cas.services.PrincipalAttributeRegisteredServiceUsernameProvider"
                                        c:usernameAttribute="uid" />
                        </property>
</bean>

**Comment by mmoayyed** [comment]
Yes that is all true. Where is the issue? :) 

If you have a provider, CAS uses that to find the username for release. If you don't, the default is used.

**Comment by mmoayyed** [comment]
for the following configuration the mail attribute will be returned not the uid attribute

```
 <bean id="usernameAttributeProvider"
            class="org.jasig.services.persondir.support.SimpleUsernameAttributeProvider">
            <property name="usernameAttribute" value="mail" />
    </bean>
```

Also, you're using the wrong provider. CAS has no SimpleUsernameAttributeProvider.

**Comment by idwright** [comment]
The formatting got a bit messed up - I'll attempt to post again and expand

The problems are as follows:

In previous versions you could just configure the usernameAttribute for a service without having to include that attribute in allowedAttributes whereas now you need it in both

You get unexpected behaviour in that a different attribute than that configured is returned without any indication that something odd is happening.

Old:

```
<bean class="org.jasig.cas.services.RegexRegisteredService" p:id="0"

			p:name="HTTP and IMAP" p:description="Allows HTTP(S) and IMAP(S) protocols"
			p:serviceId="^(https?|imaps?)://alfresco.*" p:evaluationOrder="10000001">
			<property name="usernameAttribute" value="uid"/>
</bean>
```
New broken:

```
<bean class="org.jasig.cas.services.RegexRegisteredService" p:id="5"
                        p:name="HTTP and IMAP" p:description="Allows HTTP(S) and IMAP(S) protocols"
                        p:serviceId="^https?://.*(:8443)?" p:evaluationOrder="10000100">
                        <property name="usernameAttributeProvider">
                                <bean
                                        class="org.jasig.cas.services.PrincipalAttributeRegisteredServiceUsernameProvider"
                                        c:usernameAttribute="uid" />
                        </property>
                </bean>
```
New working:
```
<bean class="org.jasig.cas.services.RegexRegisteredService" p:id="5"
                        p:name="HTTP and IMAP" p:description="Allows HTTP(S) and IMAP(S) protocols"
                        p:serviceId="^https?://.*(:8443)?" p:evaluationOrder="10000100">
                        <property name="usernameAttributeProvider">
                                <bean
                                        class="org.jasig.cas.services.PrincipalAttributeRegisteredServiceUsernameProvider"
                                        c:usernameAttribute="uid" />
                        </property>
                        <property name="attributeReleasePolicy">
                                <bean class="org.jasig.cas.services.ReturnAllowedAttributeReleasePolicy">
                                        <property name="allowedAttributes">
                                                <list>
                                                        <value>uid</value>
                                                </list>
                                        </property>
                                </bean>
                        </property>
                </bean>
```

**Comment by mmoayyed** [comment]
True, yes. While that is  redundant, it's by design. We could backlog this. Thanks for clarifying the issue.
