### ISSUE TITLE
While using JsonServiceRegistryDao its not possible to inject properties from cas.properties

### ISSUE THREAD

**Issue by vladimirilm** [Jasig/cas#1740]
1. CAS server version
4.2.1
2. Container type/version (Tomcat, Jetty, etc)
jetty 9.3
3. Steps to duplicate the problem
such service is not possible to configure via cas.properties, but i can do it with spring.
{
	"@class" : "org.jasig.cas.support.oauth.services.OAuthRegisteredService",
	"serviceId" : "^(https?|imaps?)://([A-Za-z0-9_-]+\.)*whatecer\.com.*",
	"name" : "API",
	"description" : "API",
	"id" : 11,
	"evaluationOrder" : 0,
	"clientId" : "ourapi",
	"clientSecret" : "${oauth.somekindofapi.secret}"
}

4. Stacktraces and CAS logs where appropriate.
nope.

**Comment by mmoayyed** [comment]
Not an issue. By design.
