### ISSUE TITLE
CAS Management Logs went away with v4.2.1

### ISSUE THREAD

**Issue by tsschmi** [Jasig/cas#1741]
After updating to the v4.2.1 and setting -Dlog4j.configurationFile for the CAS server to pick up our logging config, CAS Management App logs stopped being written out.  The app is deployed to same tomcat instance as a CAS Server instance, but management log entries do not show in cas.log either.  I have tried setting -Dlog4j.config.location for the management app since that was the property in cas-management.properties, but that did not work either.

**Comment by tsschmi** [comment]
I found that adding this to cas-management-webapp-support/build.gradle

runtime group: 'com.lmax', name: 'disruptor', version: disruptorVersion

Now is writing logs based on configuration that is set in -Dlog4j.configurationFile.  Is there plans to use separate config file for management app?

**Comment by mmoayyed** [comment]
It should work the same way that CAS itself does. So in that sense, this is a bug but you could if you wanted to point to a different log file which does not use async loggers and that would make the problem go away. This needs to be fixed though.
