### ISSUE TITLE
[CAS-1458] @Transaction annotations generate database calls during authentication

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#476]
Background information on this issue can be found in the following cas-user mailing list thread: https://lists.wisc.edu/read/messages?id=33283543

If a JPA service registry is configured, a database outage should not cause CAS authentication to fail. However, due to @Transaction annotations placed on methods in the class CentralAuthenticationServiceImpl, database transactions are used for non-service-registry methods. Specifically, createTicketGrantingTicket() is called during authentication, which causes the transaction manager to call "SET autocommit=0; commit; SET autocommit=1" against the database. When the service registry database is offline, all authentication attempts cause a "CAS is unavailable" error page to be displayed.

I worked around this by disabling @Transaction annotations and using declarative XML to put transactions on only a few methods. I'll attach the changes I made for this in case other CAS implementers want this workaround.

Perhaps the @Transaction annotations can be removed from the CentralAuthenticationServiceImpl class or the service registry can be reworked somehow.

Environment: JPA ticket registry

Reported by: Andrew Morgan, id: protag

Created: Fri, 30 May 2014 10:57:24 -0700

Updated: Fri, 30 May 2014 11:00:12 -0700

JIRA: https://issues.jasig.org/browse/CAS-1458

Diff of changes to deployerConfigContext.xml to remove the annotation-driven transaction manager and use declarative XML instead.

**Comment by ikogan** [comment]
Thanks for this, I was just looking into this issue myself and will be using this method. I'd love a more "supported" solution as, obviously, if the service manager gets refactored, this'll silently disable transactionality in the service manager.

**Comment by mmoayyed** [comment]
Handled via #1003
