### ISSUE TITLE
Memory Leak in TicketGrantingTicketImpl

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#493]
TicketGrantingTicketImpl contains a hashmap of services (service by id). This references are used to logout from all services which have been used in case the TGT expire(s). Only in case of the expire these pairs (id, service) are released.

Problem is that the id used to store a service in the hashmap is the service ticket id. It is generated in CentralAuthenticationServiceImpl.grantServiceTicket

``````````
...
final ServiceTicket serviceTicket = ticketGrantingTicket
.grantServiceTicket(serviceTicketUniqueTicketIdGenerator
.getNewTicketId(ServiceTicket.PREFIX), service,
this.serviceTicketExpirationPolicy, credentials != null);
this.serviceTicketRegistry.addTicket(serviceTicket);
``````````

That means the TGT services hashmap contains one entry per Service Ticket which was created during the live time of the TGT. With long RememberMe times this causes TGT to consume substantial memory. In our case with web page = service we end up with approx. 1MByte per TGT after 10-20days.

I propose to introduce an explicit logout url per service and use it instead of the ST id to store the service. This would allow to have one logout per service e.g. webapp in our case.

Reported by: Wilko Kempa, id: Cotopax

Created: Mon, 27 Jan 2014 12:54:21 -0700

Updated: Mon, 27 Jan 2014 12:54:21 -0700

JIRA: https://issues.jasig.org/browse/CAS-1420

**Comment by ChrisDeath** [comment]
Hi together,
we observed this issue too in our setup with an clustered ehCache (https://wiki.jasig.org/display/CASUM/EhcacheTicketRegistry and v3.5.2).
I do not understand why this issue should be minor as any user can do an DoS attack with this knowledge by just requesting ST tickets (in our case we had 2.5 Mio Service HashMap entries) and drive the CAS Tomcat into an OutOfMemory. So it is at least security critical!
For me the problem is that the service HashMap is never cleaned-up only by destroying the whole TGT in memory.

**Comment by mmoayyed** [comment]
Minor is the initial evaluation of the effort required to fix the issue; not the severity of the issue.

**Comment by ChrisDeath** [comment]
Hi Misagh,
alright i am not that familiar with GitHub, sorry.
I have forked the project and commited a workaround: https://github.com/ChrisDeath/cas/commit/e6c0f152226dc51cc68ffd493e7f853965a47b03
Unfortunatley this will break the SLO function as the AbstractWebApplicationService will not have an unique remote session identifier available. But my test (https://github.com/ChrisDeath/cas/commit/5738ff2a5363cea357eb55253041a3e9c85bc99e) showed that it actually works fine if you do not use SLO.

**Comment by mmoayyed** [comment]
Cool. Thanks for taking this on. We do need to find a way to make SLO work. I'll take a look at the patch and see if I can recommend something. Can you elaborate a bit more on why SLO in fact breaks? By unique, you mean STs correct?

**Comment by mmoayyed** [comment]
Also, feel free to issue a PR. We'll discuss the issue over there, even if breaks functionality, you might be able to update it and have us review it with you.

**Comment by mmoayyed** [comment]
I had a chance to think about this a bit more, and I cant come up with any scenarios where a service could have multiple "active" sessions. It makes sense to me to say, the current active session is provided via this TGT and no matter how many times that session is renewed, it's always backed by that TGT. Keyword being "renewed". otherwise I cant come up with a hyopthesis where a service may require more than one active session at a time; not even sure how that's possible!

All you'd want to know is, how many services did this TGT authorize; not every ST is going to cause a session renewal on the service side anyway. 

I recommend you bring this on the user/dev list and propose your solution. We can take it from there. 

Another possible option would be that if you are not using SLO, then we could just track that id instead of the ST. I'd also ping @leleuj

**Comment by AndrewRichardScully** [comment]
Is this possibly an issue when running multiple web nodes behind a reverse proxy? In that case, the same web-app (service) URL can be serviced by multiple back-end servlets, so you could have multiple internal sessions for the same user-facing service.

**Comment by leleuj** [comment]
A TGT can grow almost indefinitely because of the saved service tickets, I remember mitigating this problem by checking that the service was not already present in the map (and removing it if necessary) before adding the ST and the service.

**Comment by mmoayyed** [comment]
@leleuj Do you think you could prepare a PR or a prototype with the solution you worked out?

**Comment by leleuj** [comment]
Yes, I'll do that.

**Comment by leleuj** [comment]
Here is the PR: https://github.com/Jasig/cas/pull/1182
It's a really simple fix. 2 tests demonstrate the protection: only the latest service is kept.

**Comment by robertoschwald** [comment]
Thanks Jerome, this was one feature I waited for a long time. We are using long term tickets with JPA Ticket stores and needed to grow the MAX_PACKET_SIZE in MySQL for such very large TGT blob entries in the past. One thing you can't avoid with a fix currently are registered wildcard service urls. We avoid wildcard patterns strictly for all CAS clients since a while, as they can blow your CAS service availability. 

+1

**Comment by leleuj** [comment]
I'm not sure to understand this sentence: `One thing you can't avoid with a fix currently are registered wildcard service urls`: do you mean that the fix does not work with wildcard service definitions?

**Comment by robertoschwald** [comment]
Correct. But thats a scenario no fix I can imagine can fix it.
We had a wildcard service registered e.g.

    https://casclient.app/myapp/*

and the CAS client (a PHP forum) requested service urls with the url encoded title in the service url (very bad idea), which generated thousands of tgt service entries.
With a tgt validity of 3 months, this caused serious problems, even with the ticket cleaner which took ages to deserialize the tickets. 
Therefore, we do not allow wildcard service urls registered since then.

**Comment by leleuj** [comment]
OK. I get it. Indeed, there is no solution if you generate tons of services by changing the url in the dynamic part.

**Comment by leleuj** [comment]
For 4.1.x: #1184

**Comment by leleuj** [comment]
For 4.0.x: https://github.com/Jasig/cas/pull/1185

**Comment by AndrewRichardScully** [comment]
Please can someone reassure / correct me on the following point?

Consider this scenario:
1. HTTP reverse proxy fronting 2 (or more) web nodes, so one externally facing URL being serviced by multiple workers.
2. Stateless (e.g. Restful) web-app, so no "sticky sessions".
3. Each AJAX request can be serviced by either worker -- the reverse proxy balances the requests between the nodes.

Now (in 4.0.X at least) the Service uses only it's id field in determining equals(). In this kind of scenario, the service ID will be the same for more than one actual web servlet.

So, with this proposed change, the service ticket grant for the second worker node will cause the removal of the service ticket for the first worker node.

This will become a problem when the SLO is invoked and some of the STs will be missing, so the matching HTTP sessions cannot be expired.

**Comment by mmoayyed** [comment]
Help me understand this: if there no sessions involved on the application side, why do we need SLO? Your app is stateless, and it just needs an ST to do its job. If it starts creating its own sessions, and there is some sort of load balancer involved, stick-sessions are a must. Right?

**Comment by AndrewRichardScully** [comment]
Purely because of the way the CAS protocol and Spring Security CAS filters interact.

My understanding of a typical flow is as follows:
1. Unauthenticated request comes in to web-app servlet, user agent is redirected to CAS login page.
2. User logs in, CAS redirects back to service URL with ST as URL "token" parameter.
3. Web-app servlet validates ST and records that the request's session (e.g. JSESSIONID) is kosher.
4. For subsequent calls, only the HTTP session ID is validated (CAS itself is not further involved).

The SLO mechanism instructs the servlets to expire the HTTP sessions associated with each ST issues by the TGT, otherwise access to the servlets still succeeds even though the session cookie is invalidated.

So the web-app itself is stateless, but the security filters are not.

Are you saying that the CAS Spring filters should not be used this way in this kind of scenario? (The client records the ST and it is tested by CAS for each access?)

**Comment by mmoayyed** [comment]
Your analysis is correct, but those filters keep track of the authenticated session in the web-app itself. They initiate a session, and use one that is created. Otherwise, every request from the application as you noted would end up going to CAS. The filters generally live within the application itself, right? I am reminded of Java CAS client or even Spring Security where you configure filters to use the session created and managed by the app. The app itself may not carry any state, but there has to be something to keep track of that SSO session, and it generally is always the app session. Based on your summary, your app is not exactly stateless. (i.e. see `useSession` of the Java CAS client). 

The idea is that if you have more than one application that are managed by some sort of load balancer, whether that is software-based or hardware-based, the load balancer must use sticky-sessions to route the request to the app node. Each app node is protected by a filter, that only routes authentication requests to CAS if there is no data found in the session (again, Java CAS Client as an example). So the entire cluster in general would get one ST for one service access that is VIP of the load balancer. When the TGT expires, a request goes out to the VIP and invalidates the session. If in the meanwhile, the app session times out and it needs to authenticate again, a new ST is generated by CAS, and the old ST is removed from the TGT collection, because a new session is created that is represented by that new ST.

Make sense? Off?

**Comment by AndrewRichardScully** [comment]
Thanks, yes that makes sense.

The scenario I describe is not strictly "stateless" as you say, but the application logic still can be (with the only stateful element coming from the Spring Security session map, used purely for performance /  SLO purposes). In such a case, CAS would effectively be requiring the use of sticky sessions, purely to drive the SLO mechanism / give a performance boost by not requiring repeated ticket validations. If the particular app wasn't interested in SLO, then it could be entirely stateless.

I suppose what I'm saying is that there is a danger that this change targets a particular, well-know scenario(s) at the expense of atypical scenarios, or unforeseen scenarios.

Perhaps it would be worthwhile to give the option to opt-out / opt-in to this new behaviour, perhaps even on a Service-by-Service basis? I might make the difference between being able to say "yes CAS can do that" and "sorry, that's not supported" at some point in the future!

**Comment by mmoayyed** [comment]
I think providing that option makes very good sense, specially if it's on a service-by-service basis. It will be a difficult change to implement, because effectively the TGT object would have to be linked with the services manager/registry somehow. But functionality-wise, I am all for making this optional, and perhaps off by default.

**Comment by mmoayyed** [comment]
@leleuj would you be able to implement this behavior as an optional feature? If we are going to make this on a service-by-service basis, we should also consider how the management webapp can also present options to configure this.

**Comment by ChrisDeath** [comment]
Hi together,
that option already exists: slo.callbacks.disabled
But it is not used by the SimpleWebApplicationServices but only by the SamlSerivces (see usage of SamlArgumentExtractor). (Code Base 3.5.2).
To the discussion about stateless or not: As soon as you use SLO you can not be stateless anymore. CAS is part of your architecture and so all applications must be configured to know how the function. If you want to use SLO your client nodes must either be registered as service each own to address them directly or must provide a dispatcher that wraps all nodes behind one access point von CAS view. With the provided solution CAS is open to support all 3 ways (disable SLO, reachout each node, reachout the wrapper). BTW: if one service should really not be informed, don't provide a callback interface ?!

**Comment by mmoayyed** [comment]
I think this is a different option. Regardless of SLO on/off, TGTs keep accumulating service tickets and Service objects, which causes memory issues. Doesn't matter much if you intend to process these STs later on with SLO. If SLO is turned off specially, we are just adding services to TGT memory for no reason. 

If SLO is turned off for a service, a callback will never be informed for that service.

**Comment by ChrisDeath** [comment]
I know that, the wrong usage of STs must be fixed anyway...without options to disable or not.
We came to the SLO cause it was asked why we do that. And the list of STs was used to iterate on an TGT destroy over the list and inform the services. So the important information is not what ST was used but what services are "using" this TGT (here we go with the statefull stuff).
Andrew was asking to have a option to disable this memory leak prevention and here you should say that this shouldn't be possible.
For the rest i already commented in my workaround commit: https://github.com/ChrisDeath/cas/commit/e6c0f152226dc51cc68ffd493e7f853965a47b03

**Comment by mmoayyed** [comment]
>So the important information is not what ST was used but what services are "using" this TGT (here we go with the statefull stuff).

Wouldn't you be able to use the strategy, via the proposed pull here to find out what services are used? I imagine the following scenario:

Various authN attempts:
```
Services: 
ST-1 - ServiceX
ST-2 - ServiceY
```

Another sounds of AuthN attempts:

ServiceX needs a new ST:

```
Services: 
ST-3 - ServiceX
ST-2 - ServiceY
```

ServiceY needs a new ST:

```
Services: 
ST-3 - ServiceX
ST-4 - ServiceY
```

- You can tell which services are accessed by this TGT
- SLO would work because we still have the ST as the session identifier

Right? Which part do you see as a problem that would be make this not possible?

**Comment by leleuj** [comment]
I'm not sure to see what edge cases would break with this fix, but I can admit that maybe it could happen. Though, I don't think we should go for such a complicated solution (configuration by service).

**Comment by ChrisDeath** [comment]
Hi you be right with your edge case argument, but let me explain it:

In CentralAuthenticationServiceImpl you have this call:
final ServiceTicket serviceTicket = ticketGrantingTicket.grantServiceTicket(serviceTicketUniqueTicketIdGenerator.getNewTicketId(ServiceTicket.PREFIX), service, this.serviceTicketExpirationPolicy, credentials != null);

This will end up in your fixed method, but as you can see the variable "id" will be the ST. So now looking on your fix it will do the following:
         this.services.values().remove(service);
         this.services.put(id, service);

So yes you remove ONE value with that matches service and ad a new entry with the ST Ticket as key. But as your default example is to register a HTTP Service (Delegate-Authentication.md using <property name="serviceId" value="http://**" />) it would mean (so far i understand) that the service url may alter trough due to different parameters in url (guess that is meat with wildcard problem) and so on. This will result in a not removal but definitively in an add. So it is still a potential DoS attack point. Yes, it is in CAS Admin hands to use unique service ids to not allow http wildcards but you then have to warn anybody who is looking on your example about that possible security flaw ;)
At least i would call removeAll(service) to catch all possible instances to make it a bit "customizations-saver" if somebody else directly is altering the list (i know it is private).

**Comment by mmoayyed** [comment]
Good point. My understanding is that the situation you describe is the same whether we we track services by ST or URL. If parameters change, we consider that to be a unique service and application. Historically, that has been the case but you make a very good point, that perhaps we should iterate and remove all possible services that match the new service in some way before adding one. (If the host is the same, etc) The `remove` method needs to better consider what constitutes two services to be equal. Right now, it's all ID based but that might need changing a bit better. 

@leleuj what do you think?

**Comment by leleuj** [comment]
My fix is not a universal solution and indeed, it cannot prevent against DoS attacks with wildcard services. Though, it helps for other scenarios like unexpected CAS round-trips from a badly configured application or for long-term TGT used for remember me.

I like the idea to iterate over all services to see if it matches, but I'm not sure if we can really do that. I'll take a look at this option when trying to make this change optional.

**Comment by leleuj** [comment]
Working more on this, I realized we don't have any good solution for wildcard.
Let's take an example: I define the registered service: `https?://.*` and I have two services: `http://host/web1` and `http://host/web2`.
Let's say I have ST1 for service 1 and ST2 for service 2. If I get ST3 for service 1, I know the registered service but how can I know which service ticket I should remove as both services match the registered service?

**Comment by leleuj** [comment]
I just updated PR: https://github.com/Jasig/cas/pull/1182 to be able to defined if the latest ST must be kept for each registered service. I didn't work on the UI, nor on the backports to 4.0 and 4.1 until we reach some agreement on the solution.

**Comment by mmoayyed** [comment]
So lets walk through your scenario:

You have TGT-1 that is linked to the following services:

```
ST1 - http://host-xyz/web1
ST2 - http://host-abc/web2
```

Then, lets say you get ST3 for service `http://host-xyz/web1?hello=world`. You can iterate over the collection of services and remove all STs that match that entry for the same protocol, host and context path. So ST1 I think can be safely removed. You dont need to reach into the registry for this kind of thing. 


Doing it on a per-service basis can be tricky. You can't link a TGT to a registered service object, because that will cause lots of other issues with serialization. You need to stuff a flag, boolean one perhaps, that indicates the activation of this feature, and it needs to be stuffed into the TGT when a TGT is created. Outside the TGT, you will have access to the registered service, and can figure out what the flag should be right there, but not inside the TGT by linking the objects together. 

Makes sense?

**Comment by mmoayyed** [comment]
I did also review the PR, and as you have it, it's a no-go because of the linking of two objects (TGT vs RegSvc) and also because it impacts public APIs. I think the approach I suggested above should help with both of these issues.

**Comment by ChrisDeath** [comment]
Mhh i think it would be possible to configure it service wise, also it would only make sense to an wildcard service. Refine your example:

ST1 - http://host-xyz/web1
ST2 - http://host-abc/web2
ST3 - SERVICE_ID_1
ST4 - http://other-abc/rest1

In this setup you do have actually 3 registered services: http://**, SERVICE_ID_1 and http://other-abc/rest1. Then you could add on each service a boolean for handling remove by pattern. No serializations issues as you are not doing anything other then already now. The service is also already in place at the code place.
But actually this example shows another problem (sorry for finding that :( ): If you have two HTTP based services the more generic one would remove the dedicated to if that flag (doesn't matter which implementation) is active.

But in the end, i could definitily live with your solotion, cause i think you either have an wildcard service or you have special registered services and no "anonymous" services.

**Comment by leleuj** [comment]
@mmoayyed : I had the idea to compare services using the `RegisteredService` of the added ST, but I can do a simple `host/path` comparison.
About the fact I use the `RegisteredService`, I think I followed your recommendation (my proposal was to have a global flag to only keep or not the latest ST): https://github.com/Jasig/cas/issues/493#issuecomment-144328285, you mentioned the update of the management webapp...

Did I misunderstand you? In all cases, public API will be changed if we want to make this "only keep the latest ST" optional: the `grant` method must have at least a `boolean` to define that.

@ChrisDeath : I'm not sure to see the problem: if we keep the url without the query string, we will never remove a most generic service, won't we?

**Comment by ChrisDeath** [comment]
Hi leleuj,
i think you are right, i mixed up the Services Interface with RegisteredServices one. So the equals methode of a Service is using the ID currently, what is the complete URL. But i think you are on the right way. :)

**Comment by mmoayyed** [comment]
@leleuj I think I was concerned that in your pull, the registered service object and the TGT were linked together somehow. Using a flag makes better sense. 

As for the management webapp, I don't see a problem with adding a getter to the registered service class as long as that's the only change really. Core APIs are those that are kept inside the core-api module, and everything else is considered impl. I dont think you need to modify `grant` right? The flag could be passed to the ctor of the TGT, and then used later.

Lets take the conversation down to the PR and continue there.
