### ISSUE TITLE
Redesign the management webapp UI

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#496]
Essentially, the management app should be completely redesigned, and this would require both front-end and back-work. Although, mostly front-end for now. We want to re-envision the process/flow that is used to add/edit/delete CAS services, make it look really good, modern, easy to use and feel less clunky. The app also has not been maintained in a while, and so does not have support for some extra fields that have been added recently to each CAS service definition, and we would want to support those too. There are few other TODO items as well, but these are in a summary our miletones:

1.	Update the look and feel of the app, redesign the entire IU
2.	Add support for extra fields to be managed via the app
3.	Add support for a search functionality so services can be found in the list in the UI

Make this all look really good, functional, modern and mobile friendly. Would be great if the theme were to match the current CAS theme you designed.

**Comment by mmoayyed** [comment]
Have begun work on this issue. Going to get started with mock-ups first.

**Comment by mmoayyed** [comment]
Update:

If you want to check out what's currently done, see https://github.com/uNICON/CAS/tree/mgmt-webapp

We are still in the process of adding CRUD operations to the form. None of that is working at the moment, and should be addressed this week. We are focusing on the new UI at the moment and mapping JSON services to the form. Please watch the repo and I will keep you posted.

**Comment by mmoayyed** [comment]
Screenshots ![](https://s3.amazonaws.com/uploads.hipchat.com/142961/1732914/VIWpxlghW90BAG5/Capture1.PNG)

and
![](https://s3.amazonaws.com/uploads.hipchat.com/142961/1732914/SPhaDLYasbFD2r1/Capture2.PNG)

These are a bit old but they do the screen justice.

**Comment by leleuj** [comment]
Hey, it's nice! I'll give it a try sooner or later.

**Comment by mmoayyed** [comment]
Progress update: we have finalized the main dashboard. Working through edits and form saves. Drag and Drop as well as Deletes all work. Should be done by this week's end. Everything, as far as I have tested, works fine.

**Comment by mmoayyed** [comment]
Status update: all crud operations are nearly functional. We're testing some last UI wrinkles. Should be done by next week.

**Comment by mmoayyed** [comment]
Good news. we are almost done. I expect to publish a PR by the weekend. 

Note that this is going to a very big PR. Best way to test is to pull it down and test. A number of bugs have been fixed that relate to cloning, equality and copies of objects. Plus, more tweaks to the JSON service registry. Pure goodness.
