### ISSUE TITLE
Improve "CAS serialization" of complex objects at service ticket validation ?

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#510]
If a user attribute is a complex object, it will be sent to the CAS client application after being "serialized" through the **toString()** method. This may not be satisfactory.

The question arises with the creation of the **cas-server-support-pac4j** module which returns profiles with complex attributes at authentication : https://github.com/Jasig/cas/pull/234

**Comment by mmoayyed** [comment]
@leleuj how about this one? relevant still?

**Comment by leleuj** [comment]
The "CAS serialization" still exists in pac4j. When calling the `toString()` method (in the service ticket validation), the object is JSONified to be written in the response, passed to the application and rebuilt on the application client side (using the `ProfileHelper.buildProfile` method).
It's a good system as most people (if not all) use the default XML service ticket validation (and not the new JSON format).
For me, the main concern was the way it was implemented in pac4j: it has been completely rebuilt in version 1.9 in a clean and light way.
So I think we can close this one.

**Comment by mmoayyed** [comment]
Thanks.
