### ISSUE TITLE
[CAS-1288] Leverage OAuth server support on Spring Security OAuth library and add missing grant types

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#513]
Add missing grant types :

 *  password credentials
 *  implicit

Reported by: Jérôme Leleu, id: jleleu

Created: Tue, 2 Apr 2013 10:46:24 -0700

Updated: Wed, 19 Jun 2013 10:18:09 -0700

JIRA: https://issues.jasig.org/browse/CAS-1288

As far as the /profile endpoint is concerned, we can define that as a convenience endpoint for the integrator, but it's not strictly required for OAuth 2 compatibility.

**Comment by mmoayyed** [comment]
@leleuj Shall we tackle this for 4.2? Does it seem like something you can fit into that release?

**Comment by leleuj** [comment]
Yes, I should definitely restart working on a full OAuth server support (same for https://github.com/Jasig/cas/issues/514).

**Comment by mmoayyed** [comment]
By the way, here is a summary of our last discussion at ESUP, also available on the roadmap doc:

-----------------

Oauth server support
CAS server can be customized to act as an OAuth server. Presently the OAuth implementation requires that the client receives the TGT to pass to the profile as an access token. Also, the implementation attempts to release all attributes rather than those are allowed due to the limitations in current design. The following alternatives may be used instead:
Rather than passing the TGT directly to the client, we simply encrypt the entire CAS validation response at the time of authorization using a technology such as JWT. The encrypted response is sent to the client, and submitted back again to the profile endpoint at which point it is decrypted again and attributes are released.
Alternatively, rather than encrypting the whole response we could just simply encrypt the TGT and the service and pass it along to the client, which when received again as the access token, would be decrypted to release user attributes.
Or, we could design a new ticket type, that is a true access token made up of random strings that is passed to the client. This would replace the TGT as the token, and does not require any kind of decryption.
 
Spring Security's OAuth support may be a candidate to review.

**Comment by leleuj** [comment]
Linked to: https://github.com/Jasig/cas/issues/514

**Comment by mmoayyed** [comment]
Closing as a duplicate of #514
