### ISSUE TITLE
[CAS-1282] Leverage confirmation screen timeout on web session timeout, not on service ticket timeout

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#516]
**Issue :**

I'm trying to get OAuth to work as a provider with our CAS server. I can hit the /authorize endpoint and get a code, but when I try to hit /accessToken with the code, I'm getting

Code expired : ST-8-xZ7rHxdSWPlhaaTvZ9ST-cas01.example.org

I think I have everything set up correctly, but I can't figure out why it thinks my code is expired.

--------------------

**Explanation :**

It comes from the fact that the OAuth code (which is the service ticket) is computed before the confirmation screen is displayed : thus, if you stay too much time on the screen before clicking on the "Confirm" button, the code will be expired. The only solution is to setup a longer timeout for service ticket (1 minute for example instead of 10 seconds by default).

It's not really a bug, but the truth is that the design could be greatly improved here.

**The confirmation screen timeout should be leverage on the web session timeout, not on the service ticket timeout.**

Reported by: Jérôme Leleu, id: jleleu

Created: Sat, 30 Mar 2013 01:29:40 -0700

Updated: Tue, 10 Jun 2014 03:46:55 -0700

JIRA: https://issues.jasig.org/browse/CAS-1282

**Comment by mmoayyed** [comment]
@leleuj This issue is still relevant?

**Comment by leleuj** [comment]
Since https://github.com/Jasig/cas/issues/1425, it's not relevant any more. The OAuth code is only generated after approval so it's timeout does not matter for approval, approval still being optional.
