### ISSUE TITLE
Can't login after timeout when "Remember Me" feature enabled

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#517]
"Remember Me" feature work fines. If checked, it granted long time tickets. Without it, it is only 3 hours. But once the session time out, no matter normal ticket or long term ticket, it can't login any more. No error at the login page, it just return back to login page. The error shows in catalina.out:

2013-02-17 23:17:38,338 INFO \[com.github.inspektr.audit.support.Slf4jLoggingAudi
tTrailManager\] - <Audit trail record BEGIN=============================================================
WHO: audit:unknown
WHAT: http://www.example.com/private/
ACTION: SERVICE\_TICKET\_NOT\_CREATED
APPLICATION: CAS
WHEN: Sun Feb 17 23:17:38 GMT 2013
CLIENT IP ADDRESS: xxx.xxx.xxx.xxx
SERVER IP ADDRESS: unknown
=============================================================

If you logout (click cas/logout page) and refresh login page, then you may login again.

Could someone help me? Thanks.

Environment: Rethad Enterprise 6, tomcat 6.0.24, Apache httpd 2.2.15, mod\_ssl 2.2.15, java-1.7.0-openjdk, maven 3.0.4, mod\_auth\_cas 1.0.9.1, self-signed SSL certificates

Reported by: Min, id: moviemin

Created: Fri, 15 Mar 2013 13:22:40 -0700

Updated: Fri, 15 Mar 2013 13:22:40 -0700

JIRA: https://issues.jasig.org/browse/CAS-1274

**Comment by mmoayyed** [comment]
This should be fixed in 4.0 already. I tried the above parameters, and can see that when the app session is invalidated, and the remember-me cookie is also gone, CAS returns the flow back to the login screen and asks the user to reauthenticate again.

**Comment by nmoraes** [comment]
Hi mmoayyed , I have the same issue with CAD.

Did you find the solution?

I'm going to very appreciate your response,

Regards

**Comment by mmoayyed** [comment]
There is no solution, because we don't quite know what the problem is. If you can share details of exactly what you run into, then we can diagnose possible issues.

**Comment by nmoraes** [comment]
I'm working in an issue something like your.
I'm going to share with you later . . .

**Comment by mmoayyed** [comment]
great. look fwd to it.

**Comment by nmoraes** [comment]
Hi there, finally, I culd resolve the issue,
The main issue was an invalid java certificate on server machine.

You must to add the certificate for your app to the keystore file of the used JVM located at %JAVA_HOME%\lib\security\cacerts.

First you can check if your certificate is already in the keystore by running the following command: keytool -list -keystore "%JAVA_HOME%/jre/lib/security/cacerts"

In case of your certificate is missing you can get it by downloading it with your browser and add it to the keystore with the following command:

keytool -import -noprompt -trustcacerts -alias <AliasName> -file   <certificate> -keystore <KeystoreFile> -storepass <Password>

Afer import you can run the first command again to check if your certificate was added.

After that, I could authenticate with CAS without errors.

Best regards, Nicolas
