### ISSUE TITLE
[CAS-984] Allow AuthenticationMetaDataPopulators to throw AuthenticationException

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#560]
currently within the default AuthenticationManagerImpl the only extensible code that can throw exceptions are the AuthenticationHandlers. Unfortunately this doesn't allow authentication exceptions to be thrown in code that populates attributes if certain attributes can't be found.

adding the throws exception to the interface shouldn't break any existing Resolvers, but it is still a minor API change.

Reported by: Daniel Frett, id: frett

Created: Fri, 10 Jun 2011 07:39:18 -0700

Updated: Mon, 17 Oct 2011 13:43:46 -0700

JIRA: https://issues.jasig.org/browse/CAS-984

I'm narrowing the scope of this improvement because my actual implemented use case only utilizes exceptions on MetaDataPopulators

I've opened a pull request for this issue up on github.

my use case is that I have an object that is expensive to generate and is required when the user logs in to determine if their account has an administrative hold on it (which blocks the login), and it is also required when validating tickets. I want to be able to store the object with the base Authentication object so I can reference it from any tickets issued under it's authority.

**Comment by frett** [comment]
This can probably be closed, I opened it several years ago, but figured out a better way to meet my requirements since then.

**Comment by mmoayyed** [comment]
Great! thanks for the update.
