### ISSUE TITLE
Support for Multi-Factor Authentication

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#572]
Update APIs for Support for Multi-Factor Authentication

**Comment by urqui** [comment]
What would be required for you to add support for the URQUi mfa solution?

**Comment by mmoayyed** [comment]
1. Community demand
2. An authentication handler

**Comment by urqui** [comment]
Ok, great. We have the handler, and currently implementing at an institution. How do you gauge demand?  Would a school(s) contact you, asking for it?

**Comment by mmoayyed** [comment]
We would need the code to typically be in production, and we would need the institutions to publicly ask for the feature on the mailing lists, so that we can discuss and see whether it makes sense to include the module in the core, and whether there is enough demand for it in the community. It would also have to be advocated by the institution rather than the vendor, unless the community is already comfortable with the vendor like Duo.

**Comment by urqui** [comment]
ok, thanks

jon

**Comment by mmoayyed** [comment]
From @dima767 

>My main point is that currently, each SWF action e.g.: https://github.com/Unicon/cas/blob/a013bb8714f413541499ec8939e391be2243ce41/cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/AuthenticationViaFormAction.java#L174 and for example non-interactive action also blindly assume that they are THE ONLY participants in the authentication transaction and immediately build the context and ask CAS to issue TGT. This assumption/impl would need to be re-thought and refactored to introduce a higher layer *web/SWF for example) to mediate the multi-phased authn transactions, take care of the auth ctx builder persistence in between requests in the thread safe manner for each authn session, etc. Basically a mediator/glue layer between authentication and web sso subsystems.

**Comment by mmoayyed** [comment]
AuthN API pulls are merged. Resuming work.
