### ISSUE TITLE
Language/Message bundle updates 

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#678]
Attempt to update language bundles with the most recent translations based on the default English bundle. This preferably needs to be the last item to resolve before the actual release, so as to make sure there aren't any dangling changes.

@leleuj and @mmoayyed and @robertoschwald  may be able to help with some of the language bundle texts.

**Comment by mmoayyed** [comment]
@leleuj are there any messages that could be translated to french?

**Comment by leleuj** [comment]
Yes, certainly, I'll take a look and see if there is some missing translation.

**Comment by leleuj** [comment]
PR for French language: https://github.com/Jasig/cas/pull/1041

**Comment by mmoayyed** [comment]
Changed milestone to target the next release.

**Comment by mmoayyed** [comment]
Closing this. We'll do this in an ad-hoc fashion on demand.
