### ISSUE TITLE
Extract OAuth AuthZ server; issue true OAuth Access-Tokens

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#685]
The OAuth implementation in CAS does two things; it pretends that CAS is both the authorization server as well as the resource server. This approach is complicated in some ways, because it forces CAS to ignore released attributes for the OAuth client defined in the registry, thereby releasing all, and it issues TGTs that are treated like OAuth access-tokens, which can be problematic security-wise. 

The idea here discussed proposes that oauth authorization server be pulled out, which would be the entity only responsible to create access-tokens. This authz server would still use CAS for authentication and retrieval of user profile, but it is responsible to manage tokens and communicate requests from oauth clients to CAS and back. The clients only interacts with the authz provider who acts as the proxy.

Typical flow is such, summarized:

1. Oauth client submits request to AuthZ provider
2. AuthZ provider sends the request from client to CAS for authentication
3. CAS validates the authentication flow
4. AuthZ receives CAS response, issues access-token to client
5. Client issues request to authZ server via access token to get user profile
6. AuthZ server sends request to CAS, identifying the client
7. CAS validates the request (issues ST, validates ST) and generates user profile with attributes for the client
8. AuthZ server receives profile, sends it back to client.

We discussed that there may authz server implementations out there that we could use, particularly Spring OAuth support.

**Comment by mmoayyed** [comment]
Closing in favor #514

**Comment by junetam11** [comment]
I am new joiner. Had been sourcing around and found the Apereo Cas 5.0 with cas-server-support-oauth-webflow and cas-server-support-oauth. Is Apereo Cas server ready product for OAuth2 compliance Authorization and Single-Signed-On solution?

**Comment by junetam11** [comment]
Is yes, anyone can share the Maven POM file and the documentation? If no, what are the alternative open source SSO solution?
