### ISSUE TITLE
CAS Rest API doesen't work behind a proxy

### ISSUE THREAD

**Issue by drogin** [Jasig/cas#762]
If the CAS-server is behind a proxy with a different host and port name, the Location-header returned after creating a ticket with the CAS rest API returns the server-URL&port, instead of the proxy-url and proxy-port, even when actually doing the call through the proxy.

Usually this can be remedied by setting proxyPort="" and proxyName="" in the tomcat connector hosting the CAS-server webapp. However, when I add these, the REST-API returns 404. If I remove the proxy-configurations in the tomcat-connector, the REST API works again, but as mentioned, with the "wrong" URL and Port in the location-header.

This is a major problem when serving CAS-servers from behind proxies, as the URL and port the REST API returns to the caller, is useless and misleading, as those arent exposed to the public(only the proxy is).

**Comment by mmoayyed** [comment]
Closing this for now.
