### ISSUE TITLE
REST Protocol do not work

### ISSUE THREAD

**Issue by toocruel** [Jasig/cas#839]
i want to login cas in my android app.so i add the Configuration in my cas server web.xml:
<servlet>
    <servlet-name>restlet</servlet-name>
    <servlet-class>org.restlet.ext.spring.RestletFrameworkServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
</servlet>
 
<servlet-mapping>
    <servlet-name>restlet</servlet-name>
    <url-pattern>/v1/*</url-pattern>
</servlet-mapping>

but ii can not to work,and the url 'v1/tickets' will to be filtered.
and the where is the jar which include  org.restlet.ext.spring.RestletFrameworkServlet ?

**Comment by mmoayyed** [comment]
Please post your questions to the cas-user mailing list first.
