### ISSUE TITLE
timeToKillInSeconds did not work

### ISSUE THREAD

**Issue by liu-tao** [Jasig/cas#850]
the document says that when I confired the ticketExpirationPolicies.xml ,like  

<description>
        Assignment of expiration policies for the different tickets generated by CAS including ticket granting ticket
        (TGT), service ticket (ST), proxy granting ticket (PGT), and proxy ticket (PT).
        These expiration policies determine how long the ticket they are assigned to can be used and even how often they
        can be used before becoming expired / invalid.
    </description>

    
    <util:constant id="SECONDS" static-field="java.util.concurrent.TimeUnit.SECONDS"/>
    <bean id="serviceTicketExpirationPolicy" class="org.jasig.cas.ticket.support.MultiTimeUseOrTimeoutExpirationPolicy"
          c:numberOfUses="1" c:timeToKill="${st.timeToKillInSeconds:10}" c:timeUnit-ref="SECONDS"/>

    
    
    <bean id="grantingTicketExpirationPolicy" class="org.jasig.cas.ticket.support.TicketGrantingTicketExpirationPolicy"
          p:maxTimeToLiveInSeconds="${tgt.maxTimeToLiveInSeconds:28800}"
          p:timeToKillInSeconds="${tgt.timeToKillInSeconds:60}"/> 

but when 60 seconds move on ,I vist the login page ,it also tell me that i have login success .that means the ticket is alse useful,and why?

**Comment by mmoayyed** [comment]
please post your questions to https://jasig.github.io/cas/Mailing-Lists.html first
