### ISSUE TITLE
Find a replacement for Perf4j

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#863]
Based on this thread:
https://groups.google.com/forum/#!topic/jasig-cas-dev/iOd6KaGygNk

The perf4j library is outdated and unmaintained. Look for better and more recent alternatives that are frequently maintained and present the same set of features, particularly support for annotations and gathering stats is important.

**Comment by dima767** [comment]
I'd suggest to seriously look into this library: https://dropwizard.github.io/metrics/3.1.0/

**Comment by mmoayyed** [comment]
Great, thanks Dima.

**Comment by mmoayyed** [comment]
Turns out that I cant even use perf4j for the time being with its JMX appenders because all perf4j appenders are tied to log4j v1. I'd have to remove that component entirely. I'll take a look what Dima suggested and see how it can fitted into CAS.
