### ISSUE TITLE
CAS single sign out in load balancing

### ISSUE THREAD

**Issue by sdmohsen** [Jasig/cas#874]
Hi,
Is there anyone using feature of single-sign-out alongside with load balancing?
I need some specific help.

+ load balancing: Apache server + mod_jk
+ single-sign-out: CAS server final version

**Comment by mmoayyed** [comment]
post your questions to the CAS mailing lists please.

**Comment by mmoayyed** [comment]
http://jasig.github.io/cas/Mailing-Lists.html
