### ISSUE TITLE
Empty warning page with every authentication after one user gets a warning message

### ISSUE THREAD

**Issue by mabes** [Jasig/cas#884]
I am running CAS 4.0.1 in Debian 7.8 
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
Tomcat version : 7.0.28-4+deb7u1

I have setup LPPE, and warnings are correctly displayed when a user has a password that is about to expire. However, once the warning page has been displayed once for one user, every single user that logs in will see a warning page without any warnings being actually displayed.

I traced this issue to commit 74ac80408dc6ef4909b7cb6964b52db67ebe81bf which introduces an instance variable to track whether the warning page should be displayed. After the first user gets a warning, this instance variable is set to "true" and since AuthenticationViaFormAction is a singleton, everyuser gets the warning page.
I see that this behaviour no longer happens in 4.1.0-SNAPSHOT due to the changes in e5ffa578d840c3e5243c8efe39ded44e1030ed65 , but is it possible to revert the faulty commit in 4.0.x so we can have a working 4.0.2 version ?

**Comment by mmoayyed** [comment]
> is it possible to revert the faulty commit in 4.0.x so we can have a working 4.0.2 version ?

Maybe. We'll see what the release schedule might be. Your workaround at this point is to include the patch in your maven overlay.

**Comment by mmoayyed** [comment]
This should be ported over to 4.0.3. Apologies for delays on this one; long overdue.

**Comment by mmoayyed** [comment]
Via https://github.com/Jasig/cas/commit/7501389ddbecbb7dab6c613dd75420eb3b6f8551
