### ISSUE TITLE
custom attribute response xml

### ISSUE THREAD

**Issue by jasonchw** [Jasig/cas#887]
Hi there,

In the CAS documentation, 2.5.7 Example response with custom attributes (http://jasig.github.io/cas/development/protocol/CAS-Protocol-Specification.html#head2.5.7), it mentioned about the response xml with custom attributes as following,

```
<?xml version="1.0" encoding="UTF-8"?>
<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
   <cas:authenticationSuccess>
      <cas:user>username</cas:user>
      <cas:attributes>
         <cas:firstname>John</cas:firstname>
         <cas:lastname>Doe</cas:lastname>
         <cas:title>Mr.</cas:title>
         <cas:email>jdoe@example.orgmailto:jdoe@example.org</cas:email>
         <cas:affiliation>staff</cas:affiliation>
         <cas:affiliation>faculty</cas:affiliation>
      </cas:attributes>
      <cas:proxyGrantingTicket>PGTIOU-84678-8a9d...</cas:proxyGrantingTicket>
   </cas:authenticationSuccess>
</cas:serviceResponse>
```

which is different from the recommended format as shown in Appendix A: CAS response XML schema (http://jasig.github.io/cas/development/protocol/CAS-Protocol-Specification.html#head4.2.5.1), based on my understanding, it is something like,

```
<cas:attribute name="affiliation">staff</cas:attribute>
```

So, can you tell me which xml format should I use? In addition, what's the reason of choosing that particular format?

Thanks,
Jason

**Comment by mmoayyed** [comment]
Use where exactly?

You should use the first syntax. I'll update the docs to note that in 4.2.5.1

**Comment by jasonchw** [comment]
Use as response for /serviceValidate .

**Comment by jasonchw** [comment]
Based on the Appendix A: CAS response XML schema (http://jasig.github.io/cas/development/protocol/CAS-Protocol-Specification.html#appendix-a-cas-response-xml-schema), should I put the custom attributes within &lt;cas:userAttributes&gt;? Like the following,

```
<?xml version="1.0" encoding="UTF-8"?>
<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
   <cas:authenticationSuccess>
      <cas:user>username</cas:user>
      <cas:attributes>
         <cas:userAttributes>
            <cas:firstname>John</cas:firstname>
            <cas:lastname>Doe</cas:lastname>
            <cas:title>Mr.</cas:title>
            <cas:email>jdoe@example.orgmailto:jdoe@example.org</cas:email>
            <cas:affiliation>staff</cas:affiliation>
            <cas:affiliation>faculty</cas:affiliation>
         </cas:userAttributes>
      </cas:attributes>
      <cas:proxyGrantingTicket>PGTIOU-84678-8a9d...</cas:proxyGrantingTicket>
   </cas:authenticationSuccess>
</cas:serviceResponse>
```

Please clarify. Thanks a lot.
Jason

**Comment by mmoayyed** [comment]
Please provide an example for a custom attribute. 

Any attribute that you have resolved and allowed for release will automatically show up in this list. Nothing more for you to do.

**Comment by mmoayyed** [comment]
What you see in your xml snippet are example custom attributes. If you are looking to figure out how to add more attributes into the response, I'd recommend you consult the docs and/or post to the mailing lists. I have updated the docs to fix the format of attribute declaration when the protocol is going to be extended.

**Comment by jasonchw** [comment]
I am looking for a correct response XML format with custom attributes. I have no problem in retrieving those attributes. I just want a clarification about where should I put those custom attributes in the response, as the example snippet is putting them as a child of &lt;cas:attributes&gt;, while the XML schema is suggesting to put them as a child of &lt;cas:userAttributes&gt; (where &lt;cas:userAttributes&gt; is a child of &lt;cas:attributes&gt;), that's why I am confuse. As it is a contract between the client and server, changing it after we rolled it out will be problematic.

**Comment by mmoayyed** [comment]
The correct response would be what you have in the xml block.
