### ISSUE TITLE
org.springframework.scheduling.quartz.SimpleTriggerBean used in spring-configuration

### ISSUE THREAD

**Issue by AndrewRichardScully** [Jasig/cas#892]
The class org.springframework.scheduling.quartz.SimpleTriggerBean is being referenced in some of the spring-configuration XML file shipped within cas-server-webapp, such as ticketRegistry.xml.

Unfortunately this class is not compatible with Quartz 2> mandating the use of Quartz 1.

org.springframework.scheduling.quartz.SimpleTriggerFactoryBean is a drop-in replacement and is compataible with both major versions of quartz.

**Comment by mmoayyed** [comment]
Are there any CAS components that require Quartz 2?

**Comment by mmoayyed** [comment]
...and if not, why would you want to use Quartz 2?

**Comment by AndrewRichardScully** [comment]
Why wouldn't you? :-)

Looks like the last release of Quartz 1 was back on 12-Jan-2012. Quartz 2 has lots of shiny new stuff (http://www.quartz-scheduler.org/documentation/quartz-2.x/new-in-quartz-2).

For me in particular, I'm running within an OSGI environment, where it is preferable to have just one copy of a given artifact within the runtime (rather than having the same jar appearing in many WEB-INF/lib directories). The older dependency in CAS makes this difficult, as the other areas of the software started using Quartz 2 ages ago.

**Comment by mmoayyed** [comment]
Sounds good. I was just wondering if there is something specific that you were planning to do with Quartz 2. Would you mind posting a PR?

**Comment by mmoayyed** [comment]
I forgot to ask. what version of CAS are you running?

**Comment by AndrewRichardScully** [comment]
3.5.1 unfortunately, I don't have source for the trunk.

**Comment by mmoayyed** [comment]
Well that's good, because I just checked and looks like master is running Quartz 2.x. Likely that's also the case for CAS 4.

**Comment by AndrewRichardScully** [comment]
I was looking at the artifact cas-server-webapp-4.0.1.war. The spring-configuration files there still reference SimpleTriggerBean, but it looks like they've been changed on master to SimpleTriggerFactoryBean

(by you actually! https://github.com/Jasig/cas/commit/6bb8657a508f8e2f3fcd4520b2999d8466e19540)

So thanks for pre-emptively helping!

Don't suppose you know whether this change make it into the next version of cas-server-webapp?

**Comment by mmoayyed** [comment]
Yes it will. master is marching towards 4.1.

**Comment by AndrewRichardScully** [comment]
Brilliant thanks for your time. Apologies I should have checked the master before raising this ticket.

Shall I close this ticket?

**Comment by mmoayyed** [comment]
Pleasure, and no worries, and I already did :)
