### ISSUE TITLE
Allow the ClientAuthenticationHandler to become extensible. 

### ISSUE THREAD

**Issue by yellowcola** [Jasig/cas#897]
Hi all, 

I'm working on a CAS project where it allows user link their facebook account to their account in our system. 

One of the step is to check if a user exist in our database after it successfully authenticate/authorize with facebook. Originally, I was planning to extend org.jasig.cas.support.pac4j.authentication.handler.support.ClientAuthenticationHandler and have the logic in postAuthenticate(). But since ClientAuthenticationHandler is final, where do you see is the best place to plug this logic into authentication process?

Thanks,
Karl

**Comment by alexkolson** [comment]
+1. Extending cas for federation is also very much of interest to me.

**Comment by leleuj** [comment]
In the CAS server 4.0, you can use a specific resolver to fetch the local user.

During the authentication, the user profile from Facebook is saved into credentials: https://github.com/Jasig/cas/blob/master/cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java#L115 , which could be reused for the resolver: https://github.com/Jasig/cas/blob/master/cas-server-core/src/main/java/org/jasig/cas/authentication/PolicyBasedAuthenticationManager.java#L231.

Just let me know if it works.

And yes, we could "open" the `ClientAuthenticationHandler` (by removing the `final` keyword).

**Comment by serac** [comment]
I guess it's just a problem with wording, but the issue description reads like a question that should be on the user list. If we're considering an API change to increase customization, let's rephrase the issue so that's clear. I would like to see discussion on mailing list followed by issue creation if there's agreement -- it really helps with issue management to have clear, succinct issues and related work log.

**Comment by yellowcola** [comment]
Thanks, @leleuj. I'll try using a resolver.
@serac Thanks for pointing it out. I agree this is more a user list question. I have no preference on opening up the API. Would you mind pointing me where's the user list site? Thanks.

**Comment by serac** [comment]
http://jasig.github.io/cas/Mailing-Lists.html

**Comment by yellowcola** [comment]
Thanks, @serac

**Comment by leleuj** [comment]
@yellowcola: Does the resolver was enough to match your need?

**Comment by yellowcola** [comment]
@leleuj I tried that option, but found it's not the best approach for our requirement. We don't want to create a principal when our user account is not associated to an external provider account.

I end up write a wrapper to the ClientAuthenticationHandler.

Thanks for checking in.

**Comment by mmoayyed** [comment]
@leleuj Looks like we might want to open up the ClientAuthenticationHandler ?

**Comment by leleuj** [comment]
It does make sense to me. It shouldn't be too complicated...

**Comment by leleuj** [comment]
@yellowcola @mmoayyed: How do you feel about this PR? https://github.com/Jasig/cas/pull/949

**Comment by mmoayyed** [comment]
Merged via  #949

**Comment by yellowcola** [comment]
@leleuj & @mmoayyed, thanks for open up API. That simplifies my code significantly.

**Comment by mmoayyed** [comment]
@yellowcola very good. You should be able to try with a SNAPSHOT release already. Feel free to open up other API related issues.
