### ISSUE TITLE
Support OpenId Connect via PAC4J

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#902]
Seems like Pac4j 1.7 has started to support openid connect. Since CAS already takes advantage of this library for oauth, etc it would be good to dedicate perhaps another module to support openid connect  from the cas server perspective.

Tagging @leleuj so he's aware of the request.

**Comment by leleuj** [comment]
Yes, I'm on it, it will go into the `cas-server-support-pac4j` module which is based on `pac4j` (I just released v1.7.0 which supports OpenID Connect) and supports "authentication delegation".

**Comment by mmoayyed** [comment]
Thank you for the summary. This will be a valuable addition to CAS.

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/910

**Comment by mmoayyed** [comment]
Handled by https://github.com/Jasig/cas/pull/910
