### ISSUE TITLE
login error tips do not work on the login page when logining error

### ISSUE THREAD

**Issue by icanfly** [Jasig/cas#907]
I have found that code like this(AuthenticationViaFormAction.java):
messageContext.addMessage(new MessageBuilder().code("error.invalid.loginticket").build());

I think severity (property of MessageBuilder) should be set like this:
messageContext.addMessage(new MessageBuilder().code("error.invalid.loginticket").error().build());

above code will be work good for error tips when login error 

I'm sorry my fork code is dirty(I have modify some places just for my project) to pull, so just submit some bugs I found.

I will organize a new branch code to pull when I find some issues next time. :-)

**Comment by icanfly** [comment]
source tag : v4.0.0

**Comment by mmoayyed** [comment]
Thank you for the report. I have confirmed this and will post a pull shortly.
