### ISSUE TITLE
Message Authentication

### ISSUE THREAD

**Issue by rdev5** [Jasig/cas#911]
It probably wouldn't be a bad idea to add message authentication here (https://github.com/Jasig/cas/blob/master/cas-server-extension-clearpass/src/main/java/org/jasig/cas/extension/clearpass/EncryptedMapDecorator.java#L387) for integrity purposes.

**Comment by mmoayyed** [comment]
This form of enabling clearpass is now deprecated:
https://github.com/Jasig/cas/blob/master/cas-server-extension-clearpass/src/main/java/org/jasig/cas/extension/clearpass/EncryptedMapDecorator.java#L55

See development docs for more info.

**Comment by mmoayyed** [comment]
http://jasig.github.io/cas/development/integration/ClearPass.html
