### ISSUE TITLE
CRLDistributionPointRevocationChecker should support LDAP when crlURL points to an LDAP server

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#926]
A crl url can be http, https or ftp. We should consider supporting LDAP urls as well.

**Comment by serac** [comment]
Someone mentioned that use case on cas-user a while back, but it's a substantial feature that I didn't have the resources to spend at the time. That's to say it is probably a welcome feature, but a relatively expensive one.

**Comment by mmoayyed** [comment]
Someone pointed out to me that Apache CFX is doing this sort of thing and I am going to try their code sample in a bit. Should have a pull shortly.

**Comment by mmoayyed** [comment]
Seems like it would be a very useful feature in AD environments.
