### ISSUE TITLE
Solution of CAS cluster(High Availability)

### ISSUE THREAD

**Issue by dodolzg** [Jasig/cas#929]
To implement CAS cluster, we need to resolve these problem:
1, share ticket storage in cluster nodes
2, share session(webflow session) in cluster nodes
Step 1 has been resolved by cas-server-integration-memcached.
For step 2, I read the guide from wiki: https://github.com/Jasig/cas/wiki/High-Availability-%28HA%29-Guide#session-affinity. It is just session sticky. When node A crash, request will go to node B, but node B has no session info about the users that belongs to node A. Actually it is not High Availability.

I'm not sure whether  tomcat-redis-session-manager is effective, cause webflow session is different from standard session in catalina.

**Comment by leleuj** [comment]
The web session affinity is only useful during the login process and it's not the case any more in the future CAS v4.1.
Your CAS server must be highly available (several nodes) but it must be the same for your tickets storage backend (see the "Cache-based Storage Backend" part).

**Comment by leleuj** [comment]
Please ask any question on the CAS mailing list: http://jasig.github.io/cas/Mailing-Lists.html

**Comment by LiJohnson** [comment]
where is webflow-session stored ? in-memory ?
