### ISSUE TITLE
SPNEGO Constants IllegalCastException

### ISSUE THREAD

**Issue by seanrbaker** [Jasig/cas#947]
#794 may have resulted in a runtime incompatibility for the NTLMSSP_SIGNATURE definition.  It's not defined as a Byte[], whereas the source data which it needs to be compared with is encoded byte[], resulting in an IllegalCastException (though only at runtime -- tricky!).  Multiple ways this could be addressed; I'm happy to issue a PR for casting the user data or for redoing the static definition.

**Comment by mmoayyed** [comment]
This method retrieves the original bye array from source:

```java
    private byte[] consumeByteSourceOrNull(final ByteSource source) {
        try {
            if (source == null || source.isEmpty()) {
                return null;
            }
            return source.read();
        } catch (final IOException e) {
            logger.warn("Could not consume the byte array source", e);
            return null;
        }
```

Could we encode the byte array here and send it? The method you'd need to encode is added in this PR #928

**Comment by mmoayyed** [comment]
I forgot to ask, what is the encoding?

**Comment by seanrbaker** [comment]
Sorry, just saw there's a typo in the original report -- that it should say that the NTLMSSP_SIGNATURE is *now* defined as Byte[], not 'not'.

Put succinctly:  SpnegoConstants is currently creating a Byte[], while the incoming data from JCIFS is byte[].  My own suggestion would be to simply amend the comparison to use Byte[i].byteValue(), but if re-encoding the data has other values I have no objection.

**Comment by mmoayyed** [comment]
Thanks!
