### ISSUE TITLE
SPNEGO Fails Due to Null Principal

### ISSUE THREAD

**Issue by seanrbaker** [Jasig/cas#948]
#818 brought in pre-clearing of null Credentials before issuing a ticket.  When that takes place, it's constructing a HashMap of the existing Credentials to iterate over, all of which happens prior to the AuthenticationManager doing its magic.  Unfortunately, the hashCode function in the SpnegoCredential relies upon the Principal in order to construct it's hash, and as this isn't populated yet, it throws an NPE when it can't find the Principal (which is populated by the AuthMgr).

Lots of ways to address this from simple to complex.  Locally I've moved on in testing by simply overriding the hashCode function to use a static value whenever the Principal is null, but I'm happy to issue a PR for whatever manner of fix seems the most appropriate to the group.

**Comment by mmoayyed** [comment]
Confirmed bug. 

I think the fix you propose to use a static value whenever the Principal is null, is a fine idea. Look forward to the PR.
