### ISSUE TITLE
Only allow configured parameters in POST requests

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#958]
The idea is to block GET requests where credentials (username and password) are sent.

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/959

**Comment by mmoayyed** [comment]
@leleuj we should be able to close this issue while 2.0.2 appears in Central. When that happens, are you planning to issue a new PR?

**Comment by leleuj** [comment]
Yes, I'm waiting for the 2.0.2 release to send a new PR.

**Comment by mmoayyed** [comment]
Great, thanks. Looks like it showed up.

**Comment by leleuj** [comment]
A tiny PR: https://github.com/Jasig/cas/pull/965 to close this issue.
