### ISSUE TITLE
Mark jboss as deprecated on web page

### ISSUE THREAD

**Issue by lathspell** [Jasig/cas#966]
According to the cas-server-integration-jboss/pom.xml this module is deprecated:

```
    <name>Apereo CAS JBoss Cache Integration - DEPRECATED</name>
    <description>
        The CAS cas-server-integration-jboss module is deprecated and will be removed from subsequent CAS releases.
        You should not attempt to include this module in your CAS Maven overlays, and rather try to use alternative
        methods for your distributed ticket registry needs, such as the cas-server-integration-ehcache or
        cas-server-integration-memcached modules.
    </description>
```
The web page does not mention this, though. It should also contain an advice not to use jboss cache.

    http://jasig.github.io/cas/4.0.x/installation/JBoss-Cache-Ticket-Registry.html

**Comment by mmoayyed** [comment]
Because the page you are looking at refers to the docs for CAS 4.x, while the pom you see refers to a different version. The warning you seek is here http://jasig.github.io/cas/development/installation/JBoss-Cache-Ticket-Registry.html
