### ISSUE TITLE
with QueryDatabaseAuthenticationHandler  WHAT: 'principal' cannot be null. Check the correctness of @Audit annotation at the following audit point: execution(public abstract transient org.jasig.cas.authentication.Authentication org.jasig.cas.authentication.AuthenticationManager

### ISSUE THREAD

**Issue by mdreamfly** [Jasig/cas#968]
ERROR

WHAT: 'principal' cannot be null.
Check the correctness of @Audit annotation at the following audit point: execution(public abstract transient org.jasig.cas.authentication.Authentication org.jasig.cas.authentication.AuthenticationManager

    <bean id="dataSource"
          class="com.mchange.v2.c3p0.ComboPooledDataSource"
          p:driverClass="com.mysql.jdbc.Driver"
          p:jdbcUrl="jdbc:mysql://127.0.0.1:3306/sso"
          p:user="root"
          p:password="" />

    
    <bean id="passwordEncoder"
          class="org.jasig.cas.authentication.handler.DefaultPasswordEncoder"
          c:encodingAlgorithm="SHA1"
          p:characterEncoding="UTF-8" />

    <bean id="dbAuthHandler"
          class="org.jasig.cas.adaptors.jdbc.QueryDatabaseAuthenticationHandler"
          p:dataSource-ref="dataSource"
          p:sql="select password from users where username=? and active=1" />

**Comment by leleuj** [comment]
Please use the CAS mailing list for any questions: http://jasig.github.io/cas/Mailing-Lists.html

**Comment by mdreamfly** [comment]
mailling-Lists  Wisc-list?  I can't find cas-user -_- 'All Forums' display nothing....

**Comment by mmoayyed** [comment]
See http://jasig.github.io/cas top of the page.
