### ISSUE TITLE
CAS 3.5.x unable to suppress error messages displayed on login page

### ISSUE THREAD

**Issue by jquin014** [Jasig/cas#969]
Seems that with CAS 3.5.x error messages are not suppressed or redirected to CAS Unavailable page. The error message is displayed on the login page above the username field. An example if LDAP is configured for backend authentication and you supply an incorrect hostname when the user hits submit on the login page the communication error for the ldap is displayed on the login screen.

**Comment by mmoayyed** [comment]
This is simple to solve. You want to include a message in the language bundle for the error you receive. For example, if the error you receive is `org.springframework.jdbc.BadSqlGrammarException`, then simply add a code with that key in, and respond with the appropriate value.

**Comment by mmoayyed** [comment]
org.springframework.jdbc.BadSqlGrammarException=XYZ has happened. Do this and that.

**Comment by jquin014** [comment]
So just to verify the entries are added to the messages_en.properties file?  Attempted this but still encountered the same issue.  Here is the exact error when I inserted a false host name in the ldap configuration of the deployer xml file.

org.springframework.dao.DataAccessResourceFailureException: Failed to borrow DirContext from pool.; nested exception is org.springframework.ldap.CommunicationException: FALSEldap5.fiu.edu:636; nested exception is javax.naming.CommunicationException: FALSEldap5.fiu.edu:636 [Root exception is java.net.UnknownHostException: FALSEldap5.fiu.edu

The entries I added to the messages_en.properties file were the following:
# LDAP Communication Error
org.springframework.ldap.CommunicationException=Unable To Reach LDAP Server
org.springframework.dao.DataAccessResourceFailureException=Unable To Access Ldap Resource
javax.naming.CommunicationException=Unable To Reach Ldap Server
java.net.UnknownHostException=Unknown Ldap Server

**Comment by mmoayyed** [comment]
OK, thanks for the report. I'll look into this a bit more.

**Comment by mmoayyed** [comment]
I have resolved the issue. You should now be able to do something like:

DataAccessResourceFailureException=...

The fix will be available in 3.6
