### ISSUE TITLE
org.jasig.cas.authentication.HandlerResult ignoring argument

### ISSUE THREAD

**Issue by mbohun** [Jasig/cas#981]
`org.jasig.cas.authentication.HandlerResult` ctor ignoring the argument `warnings`: https://github.com/Jasig/cas/blob/4.0.x/cas-server-core/src/main/java/org/jasig/cas/authentication/HandlerResult.java#L68

git branch: **`4.0.x`**

**Comment by leleuj** [comment]
You're right: the same issue occurs on master as well: https://github.com/Jasig/cas/blob/master/cas-server-core/src/main/java/org/jasig/cas/authentication/HandlerResult.java#L90

Would you mind sending pull requests to fix that?

**Comment by mmoayyed** [comment]
In the interest of moving forward with the release, I'll take care of this.
