### ISSUE TITLE
REST API endpoint /v1/login always returns HTML instead of json with url key and proper value

### ISSUE THREAD

**Issue by tangrammer** [Jasig/cas#990]
Hi guys, 
I'm very confused about the behaviour of following api call
POST https://ps-pre.posting-engine.ch/cas/login
with body 
```
"{\"gateway\":\"true\",\"auto\":\"true\",\"service\":\"https%3A%2F%xxx.ch%2Fconfback%2Fapi%2Fv1%2Fauth%2Fcallback%3Fclient_name%3DCasClient\"}"`
`
``

**I can't understand yet why I always get html success body instead of json when using curl** but when I use a browser client **it works fine** 



these are my headers (showing here a clojure map type format output)
```
 :headers
  {"Origin" "https://ps-pre.posting-engine.ch",
   "User-Agent"
   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36",
   "Accept-Encoding" "gzip, deflate",
   "Accept-Language" "de,es;q=0.8,en;q=0.6,en-US;q=0.4",
   "Cookie"
   "JSESSIONID=ajzr2whh7ypu9b20op0zivz2; ASC=TGT-263-EenxmGc4uWBrvqNcOLp4AVcrGdgf5ur67UCfOCk5UQ5TqnUlEa-posting-stack-cas",
   "Content-Type" "application/x-www-form-urlencoded",
   "Connection" "keep-alive",
   "Accept" "application/json, text/plain, */*",
   "Referer" "https://xxx.ch/configurator/",
   "Host" "xxx.ch"}},
```

I can't understand yet why I always get html success body instead of json


this is my config in login-webflow.xml
```
    <decision-state id="postRedirectDecision">
        <if test="requestScope.response.responseType.name() == 'POST'" then="postView" else="redirectView" />
    </decision-state>

```

**Comment by mmoayyed** [comment]
I recommend you post the cas mailing list first. There was a similar issue reported a while back that answers your question. If you search the archives, you'll find it.

**Comment by tangrammer** [comment]
Thanks @mmoayyed  for pointed me the place of the solution but still didn't find the proper answer ...
can you tell me which keywords I could use to search?

**Comment by mmoayyed** [comment]
Does this help?
https://groups.google.com/forum/#!searchin/jasig-cas-user/Dmitriy$20Kopylenko$20rest/jasig-cas-user/q5TrpVUY7Kw/sB6sNcnRakAJ

**Comment by tangrammer** [comment]
thanks @mmoayyed for your help!
my problem was the body value 
it was `"{\"gateway\":\"true\",\"auto\":\"true\",\"service\":\"https%3A%2F%xxx.ch%2Fconfback%2Fapi%2Fv1%2Fauth%2Fcallback%3Fclient_name%3DCasClient\"}"`

but should be without `{}``
