### ISSUE TITLE
CodeHaus Problem

### ISSUE THREAD

**Issue by farzadkh** [Jasig/cas#995]
I was in a middle of a project deploying CAS, unfortunately all the builds today are terminating with a 301 Error on downloading modules because CodeHaus services are down. Is there any solution?

Downloading: http://oss.sonatype.org/content/repositories/releases//org/apache/maven/surefire/surefire-api/2.4.3/surefire-api-2.4.3.jar
178/178b
178b downloaded  (surefire-api-2.4.3.jar)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - RETRYING
Downloading: http://oss.sonatype.org/content/repositories/releases//org/apache/maven/surefire/surefire-api/2.4.3/surefire-api-2.4.3.jar
178/178b
178b downloaded  (surefire-api-2.4.3.jar)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - IGNORING

**Comment by mmoayyed** [comment]
Consult with the codehaus website. They have instructions on how to setup redirects. 

What is failing? I dont see any codehaus specific dependencies here.

**Comment by farzadkh** [comment]
http://oss.sonatype.org/content/repositories/releases//org/apache/maven/surefire/surefire-api/2.4.3/surefire-api-2.4.3.jar

It sets a redirect. The problem is that the redirects are not going to work anymore. They did last night but not today!

**Comment by mmoayyed** [comment]
OK, why are you then not using Maven Central?

Is this not what you're looking for?
http://search.maven.org/#browse|-735274163

**Comment by farzadkh** [comment]
I'm a novice in OpenSource. I just tried to build the CAS using Maven WAR overlay to setup a CAS server on windows and I get to a bunch of troubles. I don't know how to change the repsoitory or redirect it. I've just followed the instructions from https://wiki.jasig.org/display/CASUM/Best+Practice+-+Setting+Up+CAS+Locally+using+the+Maven+WAR+Overlay+Method
and http://jasig.github.io/cas/4.0.x/installation/Maven-Overlay-Installation.html

**Comment by mmoayyed** [comment]
Start with this template here plz first. 
https://github.com/UniconLabs/simple-cas4-overlay-template

Post additional questions to the cas-user list. if there is an actual issue, we'll investigate and open up one.
